### ISSUE TITLE
中文版 探索中的卡片是否可以加入

### ISSUE THREAD

**Issue by gmlworld** [shuzijun/leetcode-editor#1]
中文版 探索中的卡片是否可以加入

**Comment by shuzijun** [comment]
> 中文版探索中的卡片是否可以加入

可以，后续版本更新可以加上，可能需要一定的时间

**Comment by shuzijun** [comment]
> 中文版探索中的卡片是否可以加入

新版本中支持了探索中的题目，但是文字部分暂时没有想到怎么支持

**Comment by gmlworld** [comment]
功能已经满足，实现可以考虑在 treeView的每个treeItem上设置ToolTip中放置一些说明，鼠标放上去就会有一些说明

**Comment by shuzijun** [comment]
因为列表请求中没有返回题目描述，无法直接展示。
