### ISSUE TITLE
中文版标题为英文

### ISSUE THREAD

**Issue by zenppl** [shuzijun/leetcode-editor#101]
设置的中文leetcode，但是标题是英文的

**Comment by zenppl** [comment]
![image](https://user-images.githubusercontent.com/24288460/70875749-0387ce80-1ff2-11ea-9700-aed0f542d71f.png)

**Comment by wyy2008cmcn** [comment]
我这边有时是中文 有时是英文  不知道什么原因

**Comment by BoomManPro** [comment]
我这边也是,感觉这个问题挺严重的哈,严重影响自定义模板生成代码.

**Comment by glorinli** [comment]
接口返回是英文，不知道是不是要加参数。

**Comment by shuzijun** [comment]
获取翻译内容的接口请求内容更新了，下个版本修复
