### ISSUE TITLE
搜索时候要把scroll bar一边向下拉一边找目标题目

### ISSUE THREAD

**Issue by ohkimchi** [shuzijun/leetcode-editor#11]
比如我搜索538，点了enter。538没有直接出现在可视区，我要向下拉到有高亮标记的才可以。
可以让和搜索词相关的目标题目们自动filtered出来，置顶在搜索栏下面的区域吗？

**Comment by shuzijun** [comment]
使用的版本号是多少？最新版为3.5，更新一下再试试。如果还是不能出现在可视区，麻烦提供一下屏幕分辨率

**Comment by ohkimchi** [comment]
@shuzijun 写这个issue前刚更新，现在搜索的没上面的问题了，刚刚试的时候不知道为什么不work。btw希望那个可以搜multiple tags的功能未来能实现，比如说可以自动filter出题目同时含有array，binary search，dp tag的那个功能。谢谢作者啦！

**Comment by shuzijun** [comment]
@ohkimchi  新版4.0已经发布，支持tag搜索
