### ISSUE TITLE
无法login，按login按钮时出现login cookie窗口

### ISSUE THREAD

**Issue by zhast460** [shuzijun/leetcode-editor#120]
无法login，按login按钮时出现login cookie窗口
![image](https://user-images.githubusercontent.com/12053298/72243251-676bda00-3626-11ea-943e-b0603a344b7c.png)

如果无视这个窗口，继续操作的话，会出现下面错误信息：
![image](https://user-images.githubusercontent.com/12053298/72243283-81a5b800-3626-11ea-8355-c6d8e2058d81.png)

**Comment by shuzijun** [comment]
登陆参考：https://github.com/shuzijun/leetcode-editor/blob/master/doc/LoginHelp_ZH.md  
如果是中国站的，在用户名密码填写错误或者其他原因无法直接登陆时，会降级为cookie登陆

**Comment by niufenjujuexianhua** [comment]
@shuzijun 我也遇到相同的问题。我是使用美国版的leetcode。我按照上面的登录参考，但是打开chrome console显示的页面和登录参考里的不一样（如下图），我找了好久，没有找到cookie的页面。可以麻烦在登录参考里增加一些更详细的步骤吗？相信也会帮助到很多和我一样的使用者。非常谢谢！
![image](https://user-images.githubusercontent.com/10080722/72567773-8bc4f200-3884-11ea-885b-b368ee29d886.png)

**Comment by fywudi** [comment]
@niufenjujuexianhua @shuzijun  
I run into the same problem. The trick is you need to click any button from leetcode page then the cookies will show up.
 Log into leetcode.com in a browser. In Chrome, right click and select "Inspect". Switch to tab "Network", "XHR". Then click any button on leetcode.com(now should be on the left split screen). Now you should be able to see the cookie as showed above.

**Comment by shuzijun** [comment]
如果有问题可以添加描述再打开这个Issues
