### ISSUE TITLE
Support for multiple test cases

### ISSUE THREAD

**Issue by Kelvinson** [shuzijun/leetcode-editor#123]
Hi @shuzijun ,

I have used leetcode-editor with Intellij for a while and it's a great experince to solve LC problems on Intellij,  I want to thank you very much!  One point that may be improved is that  running multiple test cases is not supported currently, can you give me some pointers to get started if I want to contribute on this feature, e.g, can you tell me where is the functions that is relevant to read in test cases from the test case window showed below:

![Screen Shot 2020-01-14 at 4 07 55 PM](https://user-images.githubusercontent.com/16152743/72382789-09073000-36e8-11ea-92b1-d2a26882a5a6.png)

**Comment by shuzijun** [comment]
I will fix this.   
If you want to contribute to this project, I recommend reading the [IntelliJ Platform SDK](http://www.jetbrains.org/intellij/sdk/docs/welcome.html). The getting started chapter is [Building Plugins](http://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system.html) and [Plugin Structure](http://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure.html).  
After doing the above work,taking this question as an example, you can start reading from [TestcaseAction](https://github.com/shuzijun/leetcode-editor/blob/master/src/main/java/com/shuzijun/leetcode/plugin/actions/tree/TestcaseAction.java)

**Comment by Kelvinson** [comment]
Thanks for your quick response and commit, could I know when will the next release with this new feature  will come out, I am looking forward to try it, huge thanks!

**Comment by shuzijun** [comment]
Try this version [v6.2](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.2)

**Comment by Kelvinson** [comment]
Thank you very much!
