### ISSUE TITLE
US地区无法login

### ISSUE THREAD

**Issue by RebeccaYang0124** [shuzijun/leetcode-editor#131]
可能是第一次密码写错了，preference-》plugin里无法改密码（输入密码点apply毫无反应，并不真的apply updated 密码）
uninstall + reinstall 之前的信息还在，还是无法更新密码
文档里只有CN地区的work around，请问有解决方法吗？

**Comment by shuzijun** [comment]
国际站的密码目前没有作用，由于登录有验证码，现在是使用的cookie登录。点击登录按钮，会弹出一个输入cookie的输入框，参考[登录帮助](https://github.com/shuzijun/leetcode-editor/blob/master/doc/LoginHelp_ZH.md)

**Comment by RebeccaYang0124** [comment]
登陆成功了，非常感谢！
