### ISSUE TITLE
Change session

### ISSUE THREAD

**Issue by mjain01** [shuzijun/leetcode-editor#134]
There is no method to change session in intellij plugin

**Comment by shuzijun** [comment]
If you need to switch users, you can change the user name in the configuration.

**Comment by taoweicn** [comment]
Maybe his point was this:
![image](https://user-images.githubusercontent.com/25795549/78148915-fccd7c00-7467-11ea-81c4-a8abeef768aa.png)
And so was I. @shuzijun
