### ISSUE TITLE
cookie is NULL. 

### ISSUE THREAD

**Issue by tiranz** [shuzijun/leetcode-editor#139]
latest plugin from 19 Feb. IntelliJ latest stable (2019.2 )and Pycharm latest stable (2019.3) . It seems the plugin is not working for the english leetcode.com site.
I constantly getting the "cookie is NULL"  when i try to login with my premium account.
this was confirm on 2 different Ubuntu 18.04 OSes with  Intellij and OSX with pycharm.

**Comment by shuzijun** [comment]
Did not reproduce the problem, please provide some steps and screenshots.

**Comment by tiranz** [comment]
It seems you have a work around for the login, i just see it: 
https://github.com/shuzijun/leetcode-editor/blob/master/doc/LoginHelp.md#cookie-login 
the https://plugins.jetbrains.com/plugin/12132-leetcode-editor link is in a loop, guiding to it self in the "introduction" More tutorial please visit： here .
to make it clear, maybe you can put all the installation related links (guides and then issues ) on one page at the introduction ?
 on https://plugins.jetbrains.com/plugin/12132-leetcode-editor.

**Comment by Gary-code** [comment]
I think the reason is your password is wrong. However, I solve it after reseting the password
