### ISSUE TITLE
Feature Request: Sort the questions based on different filters.

### ISSUE THREAD

**Issue by Dinesh94Singh** [shuzijun/leetcode-editor#142]
Like the actual website, requesting a feature, where we can filter the list of questions based on frequently asked questions + Company based filter.

**Comment by shuzijun** [comment]
There is currently no sorting function, filtering reference:
![search](https://user-images.githubusercontent.com/27667179/76716645-fbb00580-676b-11ea-981b-676644bc68da.png)
