### ISSUE TITLE
6.2版本一直无法加载题目

### ISSUE THREAD

**Issue by SuWeidong19** [shuzijun/leetcode-editor#145]
![image](https://user-images.githubusercontent.com/17515318/76617564-853fb780-6561-11ea-8835-9aa2e1ef9dc8.png)

代理和用户密码没错无

**Comment by shuzijun** [comment]
试一下这个版本 [v6.4-beta](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.4-beta)

**Comment by zhangjun2009** [comment]
还是不行

**Comment by shuzijun** [comment]
新的beta版本已更新,下载链接[v6.4-beta](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.4-beta),这个版本的网络请求与IDE保持一致，代理与IDE保持一致，设置方法与检测参考[settings-http-proxy](https://www.jetbrains.com/help/idea/settings-http-proxy.html).
