### ISSUE TITLE
【已解决】info:请先登录 一直未解决

### ISSUE THREAD

**Issue by cooooooder** [shuzijun/leetcode-editor#150]
使用的是leetcode.com网站， 账号密码肯定是正确的。可以把题目加载出来，但提交代码就说提示未登录。 
![image](https://user-images.githubusercontent.com/14940635/77518361-a1741a80-6eb8-11ea-8d95-f08b4a12b753.png)
用cookie登录方式应该只能用于中文站。 换修改JCEFFilePath 可是根本就不能修改这个。 求大佬解答

**Comment by cooooooder** [comment]
![image](https://user-images.githubusercontent.com/14940635/77527313-e0a96800-6ec6-11ea-8d8e-dda1d7f0f2e8.png)
把dependent file放在JCEFFilePath中也不行呀

**Comment by shuzijun** [comment]
leetcode.com可以使用cookie登陆，但是要注意用英文站的cookie，首先推荐的也是这种方式，兼容性强。
如果要使用JCEF，第二张图需要把natives-mac里的内容复制到natives文件夹下，但是兼容下很差，可能出现无法加载的情况

**Comment by cooooooder** [comment]
> leetcode.com可以使用cookie登陆，但是要注意用英文站的cookie，首先推荐的也是这种方式，兼容性强。
> 如果要使用JCEF，第二张图需要把natives-mac里的内容复制到natives文件夹下，但是兼容下很差，可能出现无法加载的情况

非常感谢您的回复。 已解决~
