### ISSUE TITLE
local debug 其他语言怎么配置

### ISSUE THREAD

**Issue by cooooooder** [shuzijun/leetcode-editor#152]

**Comment by cooooooder** [comment]
教程中只有java的 没怎么看懂 请问c++怎么配置

**Comment by shuzijun** [comment]
配置参考  
```
${question.content}

\#include <iostream>
${question.code}

int main()
{
    Solution solution;
    //solution.XXX
    return 0;
}
```
运行的头文件需要自己引入一下

**Comment by cooooooder** [comment]
c

> 配置参考
> 
> ```
> ${question.content}
> 
> \#include <iostream>
> ${question.code}
> 
> int main()
> {
>     Solution solution;
>     //solution.XXX
>     return 0;
> }
> ```
> 
> 运行的头文件需要自己引入一下

c++感觉有点不一样 java是解释型的 c++是编译的 这样的话 因为每个文件是.cpp结尾的 所以没办法放到main函数里调用 这样的话 是不是每做一题就需要自己手动add一个.h文件
![image](https://user-images.githubusercontent.com/14940635/77914600-bee62180-72c8-11ea-837f-65e0380d0cc0.png)

**Comment by shuzijun** [comment]
![20200331113656](https://user-images.githubusercontent.com/27667179/77984420-15447600-7344-11ea-88e2-81a417f99ff4.png)
单文件运行配置可以参考上图，或者是否能配合单元测试使用

**Comment by shuzijun** [comment]
先关闭这个Issues，如果有问题可以再次打开

**Comment by ly0558** [comment]
你好，请问rider这个插件怎么配置呢，修改了custom template之后，每道题一个Main函数，会报错： ”程序定义了多个入口点“，请问是我配置有问题吗，有办法解决吗？我的模板实例如下：
`public class StringToIntegerAtoi{
      public static void main(String[] args) {
           Solution solution = new Solution();
           
      }
      //leetcode submit region begin(Prohibit modification and deletion)
public class Solution {
    public int MyAtoi(string s)
    {
    }
}
//leetcode submit region end(Prohibit modification and deletion)

  }`

**Comment by ly0558** [comment]
> @ly0558 是用的什么语言？也可以使用语言的单元测试能力，不一定是要main方法

好的，谢谢你。我用的是C#
