### ISSUE TITLE
题目语言设置

### ISSUE THREAD

**Issue by crazelee** [shuzijun/leetcode-editor#153]
原本题目语言不是英文的吗，怎么升级了变成中文了，这个怎么设置回英文题目
![image](https://user-images.githubusercontent.com/9527020/78109794-82cbd180-742c-11ea-9e93-81626cce0682.png)

**Comment by shuzijun** [comment]
File | Settings | Tools | leetcode plugin URL 选择 leetcode.com

**Comment by seniorcandy** [comment]
中文标题太醒目了，不适合在办公室使用  :(

**Comment by shuzijun** [comment]
@seniorcandy 可以把颜色调一下

**Comment by seniorcandy** [comment]
> @seniorcandy 可以把颜色调一下

好的，  不过希望未来在隐蔽性方面的需求  也考虑一下， 这样就能神不知鬼不觉地刷题了哈哈

**Comment by crazelee** [comment]
好吧，我记得之前中文LeetCode也是英文题目的
