### ISSUE TITLE
升级依赖 或 提供更多的模版配置项

### ISSUE THREAD

**Issue by qbosen** [shuzijun/leetcode-editor#154]
我在尝试使用`velocity template`自动生成本地测试用例代码，以便在`IDE`进行快速测试。

所以需要更详细的代码信息，比如
1. 方法名
2. 返回值类型
3. 参数列表
4. 默认 test case

我观察到`velocityTool`是继承自`StringUtils`，然后尝试进行了一些设置:
```
#set($methodName = $velocityTool.removePattern($question.code, ".*\s(?=\w+\()"))
#set($methodName = $velocityTool.removePattern($methodName, "\(.*"))
#set($returnType = $velocityTool.removePattern($question.code, ".*\s(?=\w+\s\w+\()"))
#set($returnType = $velocityTool.substringBefore($returnType, " "))
#set($params = $velocityTool.removePattern($question.code, ".*\("))
#set($params = $velocityTool.removePattern($params, "\).*"))
...
```
本地测试后，很遗憾的发现，插件中的`velocityTool`是基于非常古老的`commons-lang`而非常用的`commons-lang3`，不支持相关正则操作。

希望可以**升级相关依赖** 或 **提供更多的模版配置项**。

**Comment by shuzijun** [comment]
已替换为commons-lang3，可以尝试安装[v6.4-beta](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.4-beta)
