### ISSUE TITLE
自定义模版UI控件 显示不正确

### ISSUE THREAD

**Issue by qbosen** [shuzijun/leetcode-editor#158]
设置面板中，`code template` 如果输入了较多的内容，会在输入区域上下产生大量空白。
下图展示了70行输入内容时的现实效果。

![image](https://user-images.githubusercontent.com/15816040/78865454-3b6ac400-7a70-11ea-88a2-eaa349c99acd.png)

**Comment by shuzijun** [comment]
问题已修复，[v6.4](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.4)
