### ISSUE TITLE
关于refresh

### ISSUE THREAD

**Issue by ohkimchi** [shuzijun/leetcode-editor#16]
我在ide里刷完两题后，用filter找Top 100 并且 To do的题，我刚刚写完的那两题没有自动更新status为solved。等我手动refresh题库后，再用filter Top 100 List 并且 To do，那两道做过的题的status这下自动更新为solved了。每次我submit完，可以让题目的status自动refresh吗？

**Comment by shuzijun** [comment]
@ohkimchi 
目前逻辑submit之后题目的状态是会更新的，可以看到如果提交通过，题目前会出现✔。
如果是选择了TODO且状态发生变化时直接refresh，可能发生的情况是在提交未通过的情况下状态变为Attempted,此时肯定是需要处理此题目的，如果直接refresh，则在当前列表下找不到此题目了，这种用户体验也不是很好。
为了避免重复的refresh,优化了filter的更新操作，如果状态发成了变化，想移除当前列表，可以重新选一下filter。可以尝试一下这个版本 [V4.1](https://github.com/shuzijun/leetcode-editor/blob/master/doc/leetcode-editor-V4.1.zip)

**Comment by ohkimchi** [comment]
好的，完美！
