### ISSUE TITLE
got Illegal cookie name error after the plugin updated to v6.4, and no way to reset cookie etc.

### ISSUE THREAD

**Issue by a69e** [shuzijun/leetcode-editor#161]

**Comment by shuzijun** [comment]
If you only log in through cookies, the simplest solution is to modify "loginName" in the configuration, it can be any value.  
Or you can find the configuration file leetcode-config.xml, its path refer to "[Configuration directory](https://www.jetbrains.com/help/idea/2020.1/tuning-the-ide.html?_ga=2.210010069.1914418212.1586743197-289891745.1508759713#)", the configuration file is in "options", you can delete the contents of "userCookie".

**Comment by a69e** [comment]
Thanks!

shuzijun <notifications@github.com> 于2020年4月13日周一 下午9:49写道：
