### ISSUE TITLE
IDEA2020.1安装不上

### ISSUE THREAD

**Issue by fengchenzhihun1** [shuzijun/leetcode-editor#162]
环境：win10
IDE：jb2020.1

**Comment by shuzijun** [comment]
安装方式参考[plugins ](https://www.jetbrains.com/help/idea/plugins-settings.html)

**Comment by Cynaith** [comment]
2020.1 安装之后加载不出题目

**Comment by shuzijun** [comment]
> 2020.1 安装之后加载不出题目

提供一下操作步骤和相应的错误截图

**Comment by c0deptr** [comment]
> 2020.1 安装之后加载不出题目

我的可以，题目在注释那里

**Comment by Cynaith** [comment]
可以了，我一开始在官网下载包安装了几次都不行，最后在IDEA里面安装的

**Comment by fengchenzhihun1** [comment]
重启了几遍ide，然后重装了好几次，最后成功了！。。。具体失败原因不知道是啥，也没报错！
