### ISSUE TITLE
CPP的code Template会屏蔽#include

### ISSUE THREAD

**Issue by youtal** [shuzijun/leetcode-editor#163]
因为默认模板没有添加头文件，所以我在模板的前面自己加了一句#include <bits/stdc++.h>，但是每次打开新的一题，就只剩下<bits/stdc++.h>

**Comment by youtal** [comment]
初步判定是由于‘#’字符的原因，如果某单词前出现单个‘#’,则次单词将会被屏蔽；若某行出现连续两个‘#’，则本行两个‘#’后的内容均会被屏蔽（包括换行符）。

**Comment by youtal** [comment]
在#号和include中间空一个可以解决这个问题，虽然看着不舒服就是了

**Comment by shuzijun** [comment]
由于 **#** 是velocity语法的关键字导致的，可以在#前加\,例如 **\#include <bits/stdc++.h>**
