### ISSUE TITLE
点击 open solution 显示 error 无权限

### ISSUE THREAD

**Issue by Yunme** [shuzijun/leetcode-editor#165]
点击 open solution 显示 error 无权限

**Comment by shuzijun** [comment]
leetcode.com部分解决方案只有付费用户可以查看，界面展示:
![20200426092845](https://user-images.githubusercontent.com/27667179/80294922-82f78c80-87a0-11ea-9668-1f7b73aba6fb.png)

**Comment by Yunme** [comment]
那个问题不是付费的问题。重新登录后又好了。估计是 登录 cookie 的问题。
