### ISSUE TITLE
运行失败, 序列化后丢失'<'

### ISSUE THREAD

**Issue by liucaisi** [shuzijun/leetcode-editor#17]
> 运行失败:bLine 11: error: not a statement for (int = 0; i length; i++){ ^

貌似序列化后，"<"号不见了

**Comment by shuzijun** [comment]
可以提供一下源码和相应的问题么

**Comment by liucaisi** [comment]
> 可以提供一下源码和相应的问题么

53题
`    public int maxSubArray(int[] nums) {
        int length = nums.length;
        if (length < 1) {
            return Integer.MIN_VALUE;
        }

        int currentSum = 0;
        int maxSum = Integer.MIN_VALUE;

        for (int =0; i < length; i++) {
            currentSum = 0;
            for (int j = i; j < length; j++) {
                currentSum += nums[j];
            }
            if ( maxSum < currentSum) {
                maxSum = currentSum;
            }
        }
        return maxSum;
    }`

尝试过将<转义为&lt;后，<能在代码中打印处理啊，但是还是运行失败

**Comment by liucaisi** [comment]
> 可以提供一下源码和相应的问题么

已经解决
