### ISSUE TITLE
能否将运行失败最后的提交测试用例也打印出来

### ISSUE THREAD

**Issue by Leonhardt92** [shuzijun/leetcode-editor#170]

**Comment by bmxklYzj** [comment]
@shuzijun 插件很赞。但当前能实现部分用例不过的时候不打印失败用例吗。找了一圈leetcode网页和插件都没有一个可以关的地方。因为错误用例打印出来会限制自己的思维，形成依赖。感觉是否可以配置成一个开关，用户按需配置？
