### ISSUE TITLE
Kotlin语言版本过低

### ISSUE THREAD

**Issue by 512DIDIDI** [shuzijun/leetcode-editor#172]
你好 请问目前内置的kotlin版本是多少 好多实例化方法缺失 例如hashMapOf啥的 用的还是Java库的HashMap 可以方便升级下吗 谢谢

**Comment by shuzijun** [comment]
提交后的运行环境是leetcode提供的，建议反馈给leetcode

**Comment by 512DIDIDI** [comment]
> 提交后的运行环境是leetcode提供的，建议反馈给leetcode

好的 谢谢
