### ISSUE TITLE
提交的代码不存在

### ISSUE THREAD

**Issue by xurunyu** [shuzijun/leetcode-editor#178]
在editor区域run submit都提示
info: 提交的代码不存在
插件内可以提交代码

**Comment by shuzijun** [comment]
打开的项目，文件夹下存在一个类似.idea/leetcode/editor.xml的文件,不同ide可能不同。  
检查editor提交的文件在这个xml中存不存在。

**Comment by helloqhq** [comment]
我也碰到类似问题了，要提交的文件在.idea/leetcode/editor.xml中

<img width="1019" alt="图片" src="https://user-images.githubusercontent.com/7424819/83213925-f7ee2580-a195-11ea-8868-87f7f2c68ccf.png">

**Comment by shuzijun** [comment]
@helloqhq 这个题目是如何打开的?看文件名称少了序号

**Comment by Ting97** [comment]
从Explore打开就会少序号
