### ISSUE TITLE
点击run_code后 题目的结果都是null

### ISSUE THREAD

**Issue by littlebai3618** [shuzijun/leetcode-editor#180]
5:53 下午	info
				运行成功:
				测试用例:"abcabcbb"
				测试结果:null
				期望结果:3
				stdout:

自行测试时可以输出期望结果的

**Comment by ruster-cn** [comment]
同样的问题，求解决

**Comment by shuzijun** [comment]
提供下使用的语言，题目及代码

**Comment by ruster-cn** [comment]
golang
![image](https://user-images.githubusercontent.com/58843667/83848516-9521fe80-a740-11ea-8746-6a194a24ed0b.png)

**Comment by shuzijun** [comment]
@ruster-cn 看图片中测试结果为1,没看到测试结果:null的情况

**Comment by ruster-cn** [comment]
> @ruster-cn 看图片中测试结果为1,没看到测试结果:null的情况

哦，对。我一直以为stdout 是测试结果，😂。我的问题，感谢大佬
