### ISSUE TITLE
如何在本地调试

### ISSUE THREAD

**Issue by easthorse** [shuzijun/leetcode-editor#184]
实例中以第一题为例，在main中输入了两个数组并调用Solution类中的twoSum，但若是遇到复杂的数据类型比如链表、二叉树，不方便自己编写输入用例时，应该怎么做？

**Comment by shuzijun** [comment]
这种场景目前只能手动构造对象。如有兴趣可以看下其他同学提供的小工具https://github.com/xfl03/TinyProjects/blob/master/LeetCodeExecutor/LeetCodeExecutor.java
