### ISSUE TITLE
中文站可以登录成功,英文一直登录失败

### ISSUE THREAD

**Issue by androidfans** [shuzijun/leetcode-editor#19]
![image](https://user-images.githubusercontent.com/6452650/56577243-1847ca00-65fd-11e9-8e8a-b49050a15ffa.png)
改了密码也不行, 有没有log可以看

**Comment by androidfans** [comment]
题可以正常拉取下来

**Comment by shuzijun** [comment]
@androidfans  可以尝试先点击退出之后再登录。如果不行可以尝试先登陆一下网页版，再次登陆，同时英文与中文是两套账号体系，确认一下用户名密码是否正确。

**Comment by androidfans** [comment]
先点退出再登录确实OK了.  这个是不是bug呢.  只有英文站会这样, 中文站不会

**Comment by shuzijun** [comment]
@androidfans  是因为中文网站与英文网站的登陆机制是一样的，同一个session下，会有验证冲突

**Comment by androidfans** [comment]
还有个问题 C++没有代码提示, 连括号自动补全都没有 是不是要装什么插件

**Comment by shuzijun** [comment]
用的哪个软件？

**Comment by androidfans** [comment]
Android Studio

**Comment by androidfans** [comment]
还有个问题,  用这个插件的工作党会碰到一个很蛋疼的问题, 就是公司网代理. IDE已经配置了代理, 但是插件好像并没有去读取IDE的代理配置.  我还得专门用一个全局代理工具才能使用

**Comment by shuzijun** [comment]
我对这个软件不是很了解，可以尝试google一下Android Studio支持C++的自动补全，我看到了相关介绍，但是不太确认是否对你有用。

**Comment by androidfans** [comment]
我直接新建一个C++文件是有自动补全的  直接双击插件的就不行

**Comment by shuzijun** [comment]
确实不会读取代理，如果有这方面的需求，后续可以支持一下

**Comment by shuzijun** [comment]
我尝试搜索自动补全的问题，发现Android Studio对C++的支持是以项目配置的？我不知道我这个理解对不对

**Comment by androidfans** [comment]
是的 好像路径被配置到cmake里面.  但是你这个路径是temp.  还挺麻烦. 看来用不了C++了

**Comment by shuzijun** [comment]
可以尝试新建一个项目,将缓存目录设置到项目路径的源码下，缓存里面里会生成源码文件

**Comment by androidfans** [comment]
感谢 这个方法应该可行. 我试试

**Comment by shuzijun** [comment]
@androidfans  [V4.2](https://raw.githubusercontent.com/shuzijun/leetcode-editor/master/doc/leetcode-editor-V4.2.zip)已添加支持代理，生效方式为配置IDEA的代理后再插件配置页勾选prox。目前只支持http方式。
