### ISSUE TITLE
v6.5版本更新后图标过于庞大

### ISSUE THREAD

**Issue by Muyaaaa** [shuzijun/leetcode-editor#198]
无法正常使用插件功能

**Comment by shuzijun** [comment]
麻烦提供下使用的IDE版本和错误的界面

**Comment by Muyaaaa** [comment]
> 麻烦提供下使用的IDE版本和错误的界面

版本：2018.3.3 x64
![1](https://user-images.githubusercontent.com/59350830/86193875-a6afc800-bb7f-11ea-8973-6e7eafd9f2de.png)
![2](https://user-images.githubusercontent.com/59350830/86193877-a7485e80-bb7f-11ea-9a99-27e78a78b777.png)

**Comment by Muyaaaa** [comment]
![1](https://user-images.githubusercontent.com/59350830/86193927-bcbd8880-bb7f-11ea-91eb-466c26ecba55.png)
![2](https://user-images.githubusercontent.com/59350830/86193936-c0510f80-bb7f-11ea-9c8b-f1a1324652e2.png)

**Comment by Muyaaaa** [comment]
![1](https://user-images.githubusercontent.com/59350830/86194032-07d79b80-bb80-11ea-8a2e-d3a67a90adc3.png)
![2](https://user-images.githubusercontent.com/59350830/86194034-0908c880-bb80-11ea-81c6-16f9e9d656ca.png)

**Comment by shuzijun** [comment]
已修复图标兼容问题，更新到[v6.6](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.6) 再试一下
