### ISSUE TITLE
是否可以将题目更友好的展示

### ISSUE THREAD

**Issue by zenppl** [shuzijun/leetcode-editor#2]
现在题目中带了很多html标签，还有转义符，看上去不太友好。

**Comment by shuzijun** [comment]
> 现在题目中带了很多html标签，还有转义符，看上去不太友好。

正在做这个，下个版本将移除这些标签和转义符，请关注更新

**Comment by shuzijun** [comment]
> 现在题目中带了很多html标签，还有转义符，看上去不太友好。

新版本已更新，优化了题目的描述

**Comment by zenppl** [comment]
👍我这边刚把项目run起来，加了jsoup准备提交，结果发现已经改好啦哈哈
