### ISSUE TITLE
请问c++引入头文件有什么好的解决方案吗

### ISSUE THREAD

**Issue by androidfans** [shuzijun/leetcode-editor#20]
不引入头文件参数vector之类的一直红, 引入头文件的话,提交前还要删除一下

**Comment by shuzijun** [comment]
默认删除头文件预计下个版本支持，目前会默认删除注释部分

**Comment by androidfans** [comment]
所以现在的解决方案就是要自己处理是吧.
下个版本支持的话 希望能够打开题目时就默认引入c++所有头文件, 提交时自动删除

**Comment by shuzijun** [comment]
目前的解决方案只能是自己删除。
后续引用或者删除的项可能会开放配置出来，因为每种语言引用的方式或者删除方式都是不一样的

**Comment by androidfans** [comment]
好的 了解.  感谢
