### ISSUE TITLE
华为市场的插件版本是6.4，请问什么时候能更新到6.6呢

### ISSUE THREAD

**Issue by crazyMarky** [shuzijun/leetcode-editor#200]
华为市场的插件版本是6.4，请问什么时候能更新到6.6呢

**Comment by crazyMarky** [comment]
https://marketplace.rnd.huawei.com/detail?identifier=leetcode-editor

**Comment by shuzijun** [comment]
目前发布的渠道只有github和[jetbrains-plugins](https://plugins.jetbrains.com/plugin/12132-leetcode-editor)，其他渠道咨询下网站维护人员
