### ISSUE TITLE
Markdown 图片格式化异常

### ISSUE THREAD

**Issue by 4ucl** [shuzijun/leetcode-editor#203]
**题解详情 Markdown 中的图片不能正常展示。**

以 [28. 实现 strStr()](https://leetcode-cn.com/problems/implement-strstr/) 的题解 [KMP 算法详解](https://leetcode-cn.com/problems/implement-strstr/solution/kmp-suan-fa-xiang-jie-by-labuladong/) 为例。该题解第一张图片的原始 Markdown 为 
```
![brutal](https://pic.leetcode-cn.com/023ce6af45af247b3c140ca0ebc0ac6d93b1fa081a1ae0fa9e1a83d790eabee0-file_1568963023074){:width=400}↵{:align=center}
```
格式化之后变为
```
 [brutal](https://pic.leetcode-cn.com/023ce6af45af247b3c140ca0ebc0ac6d93b1fa081a1ae0fa9e1a83d790eabee0-file_1568963023074){:width=400}
{:align=center}
```

其中 `{:width=400}↵{:align=center}` 没被正则匹配到（从目前的正则表达式看，之前的格式可能是 `{:width="400"}`，不过现在似乎没有 `"`），导致没有替换为空。

https://github.com/shuzijun/leetcode-editor/blob/57ea3ec8bfcb1958fca4d1b1007b5d21da37c411/src/main/java/com/shuzijun/leetcode/plugin/manager/ArticleManager.java#L115

另外，最前面的 `!` 被替换成了空，导致图片无法展示。

https://github.com/shuzijun/leetcode-editor/blob/57ea3ec8bfcb1958fca4d1b1007b5d21da37c411/src/main/java/com/shuzijun/leetcode/plugin/manager/ArticleManager.java#L154

**感谢作者提供的插件，用起来很不错**

**Comment by shuzijun** [comment]
第一个应该是格式发生了变化没有匹配到.  
第二个是因为ide渲染git图片会导致卡死，故意去掉的。
这个图片链接不符合预期，但gifMatcher写的有点问题，导致!被去掉了，下个版本修复一下。

**Comment by 4ucl** [comment]
低版本 IDEA 的 Markdown 插件确实经常卡死，不过最新版 `IntelliJ IDEA 2020.1.3 (Ultimate Edition) ` 还没遇到卡死的情况。

当然，兼容旧版也有必要。

**Comment by shuzijun** [comment]
新版的Markdown好像更改了展示的实现，等2020.2正式发布可以试下展示的效果
