### ISSUE TITLE
文件名能够这样定义吗？

### ISSUE THREAD

**Issue by LjyYano** [shuzijun/leetcode-editor#204]
![image](https://user-images.githubusercontent.com/9548512/87038857-e54d1e80-c220-11ea-9105-9d3f8d2204e4.png)

类似于这样的，同时生成的文件没有包名，每次都要手动导入~~~

**Comment by shuzijun** [comment]
codeFileName可以配置为
```xml
L$!velocityTool.leftPadZeros(${question.frontendQuestionId},4)_$!velocityTool.snakeCaseName(${question.titleSlug})
```  
但是首字母无法大写。

包名可以在codeTemplate中配置
