### ISSUE TITLE
邮箱验证问题

### ISSUE THREAD

**Issue by Ysoretarted** [shuzijun/leetcode-editor#207]
您尚未验证自己的帐户
			在验证电子邮件之前，您无法将代码提交给评判系统。
			您可以在个人资料页面中重新发送验证电子邮件或更改电子邮件。

如上，可是我leetcode中文官网上，明明已经验证了邮箱。   而且配置的网站是 leetcode-cn.com

**Comment by shuzijun** [comment]
试一下在网页上是否能够提交代码

**Comment by Ysoretarted** [comment]
在网页上是可以提交代码的...

**Comment by Ysoretarted** [comment]
不好意思，是我多个账号搞混了
