### ISSUE TITLE
open content会导致idea卡死。

### ISSUE THREAD

**Issue by goolulu** [shuzijun/leetcode-editor#210]
会一直md文件加载，转圈圈一段时间后idea卡死。

版本
![image](https://user-images.githubusercontent.com/35801463/88007430-8cdf2080-cb40-11ea-91a0-eb326679371e.png)

**Comment by shuzijun** [comment]
具体题目编号提供一下。
一般造成卡死的主要原因是ide对md里的图片渲染能力有限。

**Comment by goolulu** [comment]
> 具体题目编号提供一下。
> 一般造成卡死的主要原因是ide对md里的图片渲染能力有限。

随机点了几个，都出现这种问题

**Comment by shuzijun** [comment]
检查下markdown插件是否正常，正常情况下只有包含图片的才可能卡死。

**Comment by goolulu** [comment]
> 检查下markdown插件是否正常，正常情况下只有包含图片的才可能卡死。

果然是markdown插件问题。。
