### ISSUE TITLE
题目编号是中文并且有空格如何处理？

### ISSUE THREAD

**Issue by kookx** [shuzijun/leetcode-editor#211]
<img width="550" alt="WX20200722-121856@2x" src="https://user-images.githubusercontent.com/16603225/88133823-92f30100-cc15-11ea-994e-4c2c49629ed4.png">
<img width="310" alt="WX20200722-121842@2x" src="https://user-images.githubusercontent.com/16603225/88133836-9c7c6900-cc15-11ea-9505-a685645c154a.png">

**Comment by shuzijun** [comment]
参考[自定代码](https://github.com/shuzijun/leetcode-editor/blob/master/doc/CustomCode_ZH.md)
另外$!velocityTool提供了一些基本的字符串操作方法，使用方式为$!velocityTool.xxxx， 支持方法除插件内列举的外，另外支持的参考[StringUtils](https://github.com/apache/commons-lang/blob/master/src/main/java/org/apache/commons/lang3/StringUtils.java)
