### ISSUE TITLE
一直登陆不成功

### ISSUE THREAD

**Issue by Willdas** [shuzijun/leetcode-editor#212]
用户名和密码已填写正确

**Comment by Willdas** [comment]
已解决 登陆按钮可以提示下

**Comment by zxyscz** [comment]
> 已解决 登陆按钮可以提示下

请问如何解决的，我现在也遇到这个问题

**Comment by Willdas** [comment]
> > 已解决 登陆按钮可以提示下
> 
> 请问如何解决的，我现在也遇到这个问题
![image](https://user-images.githubusercontent.com/26112941/88611060-cf61a980-d0ba-11ea-8c0b-0ef785ce3963.png)
点开插件页面，上面一排按钮中有一个左按钮、右按钮、刷新等按钮，左侧的按钮是点击进行登陆，右侧按钮点击进行退出。

**Comment by sophie-okk** [comment]
希望把上面那个登录按钮，提示得更加明显一些。
否则，用户第一反应就是去配置页面username/password框里配，然而死活都不能成功，导致体验很差。

**Comment by julian102** [comment]
用户体验极差 这块必须改一下

**Comment by shuzijun** [comment]
已修改未登录提示为:请先登录(点击登录按钮进行登录)

**Comment by chenbensheng** [comment]
这个插件 这2天 登录不了

**Comment by shuzijun** [comment]
> 这个插件 这2天 登录不了

提供登录的网站，登录方式和相关错误提示
