### ISSUE TITLE
本地调式需要配置吗

### ISSUE THREAD

**Issue by aoteman5255661** [shuzijun/leetcode-editor#215]

**Comment by aoteman5255661** [comment]
调试打开后，要配置，怎么配置

**Comment by shuzijun** [comment]
参考[自定义代码生成介绍](https://github.com/shuzijun/leetcode-editor/blob/master/doc/CustomCode_ZH.md).
运行的环境的还是依赖IDE，本插件只是提供生成代码,生成的模板可以参考上面的介绍。
