### ISSUE TITLE
Intellij 更新到最新版后 Markdown显示不正常

### ISSUE THREAD

**Issue by dabirdweius** [shuzijun/leetcode-editor#219]
Intellij更新到最新之后
```
IntelliJ IDEA 2020.2 (Ultimate Edition)
Build #IU-202.6397.94, built on July 27, 2020
```
所有Markdown都会有些显示的不正常 包括题目 solution
具体触发条件可以是先打开.md 然后切换回code 然后再撤换回.md就会显示不出来：
![image](https://user-images.githubusercontent.com/36577220/89113116-7e86e380-d421-11ea-98cc-d1fd5baef8ff.png)
有时还会闪退

**Comment by shuzijun** [comment]
检查下Markdown插件是否正常

**Comment by dabirdweius** [comment]
联系了intellij那边 他们叫我试试加“-Dsun.java2d.uiScale.enabled=false” 在jvm参数里面 加了之后还是不行
现在我发了些log过去 之后我会回来update

**Comment by dabirdweius** [comment]
1. 在mac上没这个问题
2. 在windows上 disable了这个leetcode插件之后 markdown也没问题
3. 于是intellij那边叫我联系你好了

**Comment by shuzijun** [comment]
初步排查应该是引用的[JCEF三方库](https://github.com/shuzijun/Journey)与[2020版本引入的JCEF](https://jetbrains.org/intellij/sdk/docs/reference_guide/jcef.html)冲突导致,稍后提供一个快照版本,去除这个依赖

**Comment by shuzijun** [comment]
快照已编译通过,https://github.com/shuzijun/leetcode-editor/actions/runs/203974579  
下载页面中的leetcode-editor-snapshot，下载完成后解压得到leetcode-editor-0.0.zip插件安装包,然后选择通过本地文件安装插件。  
由于快照版本号是0.0,会收到更新通知,可以先忽略,等待正式版本发布后再更新到新的正式版。  

经过实践,原版本会复现不显示问题，新版本也有概率出现的这种情况，但在未安装插件的情况下也有概率出现，暂时没有排查到根本原因.
