### ISSUE TITLE
希望支持一个题目一个文件夹

### ISSUE THREAD

**Issue by BoomManPro** [shuzijun/leetcode-editor#220]
因为在golang中同包下不允许存在相同方法,但是leetcode中有很多题目的方法名是相同的.

**Comment by shuzijun** [comment]
可以尝试开启custom template,在codeFileName上加上前置路径，例如,根据题目标记建一个文件夹
```
${question.titleSlug}/[$!{question.frontendQuestionId}]${question.title}
```

**Comment by BoomManPro** [comment]
@shuzijun thanks, This solution can be added to Readme.md
