### ISSUE TITLE
VScode 代码运行报错，相同代码LeetCode运行没有问题

### ISSUE THREAD

**Issue by chloechen8** [shuzijun/leetcode-editor#226]
1.LC53.maximum-subarray
<img width="339" alt="LCerror1" src="https://user-images.githubusercontent.com/54644860/89701635-5f310e80-d96b-11ea-8170-1d3be92ef975.png">
<img width="615" alt="LCerror1_1" src="https://user-images.githubusercontent.com/54644860/89701636-62c49580-d96b-11ea-84a8-0143be571da6.png">
错误信息：
`
53.maximum-subarray.java:11: error: missing return statement
    }
    ^
1 error
`

2.LC238.product-of-array-except-self
<img width="333" alt="LCerror2" src="https://user-images.githubusercontent.com/54644860/89701644-766ffc00-d96b-11ea-8903-974fb6f3bbf3.png">
<img width="734" alt="LCERROR2_2" src="https://user-images.githubusercontent.com/54644860/89701646-78d25600-d96b-11ea-80de-05f68f17eade.png">
错误信息：
`
Error: Could not find or load main class 238.product-of-array-except-self
Caused by: java.lang.ClassNotFoundException: 238.product-of-array-except-self
`

VScode版本:
Version: 1.47.3 (system setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Leetcode 版本：extension里面直接下载的

3. 当时选择打开文件的时候，选择了加入workspace，请问从哪里可以用重新设置打开文件选项？

Thanks

**Comment by shuzijun** [comment]
不是本项目提供的，vscode可以去https://github.com/shuzijun/vscode-leetcode 讨论
