### ISSUE TITLE
使用第三方登录  这个入口 好像没有

### ISSUE THREAD

**Issue by jaedongjuly** [shuzijun/leetcode-editor#227]
**Desc**
Start a discussion or ask for help

**Software versions(*Help* -> *About*)(Optional)**
- Product: [e.g IDEA 2020.2]
- Runtime version:[e.g 11.0.7+10-b944.20 amd64]
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS:[e.g Windows 10]

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:
  ```
  
  ```

**Comment by shuzijun** [comment]
不支持使用三方登录

**Comment by jaedongjuly** [comment]
> 不支持使用三方登录

ok
