### ISSUE TITLE
v6.7 版本 插件和浏览器没法同时登录 力扣 

### ISSUE THREAD

**Issue by lijiedong** [shuzijun/leetcode-editor#228]
**Describe the bug**

**To Reproduce**

**Software versions(*Help* -> *About*)**
- Product: [e.g IDEA 2020.2]
- Runtime version:[e.g 11.0.7+10-b944.20 amd64]
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS:[e.g Windows 10]

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:
  ```
  
  ```

**Comment by shuzijun** [comment]
参考#222
