### ISSUE TITLE
submit 或者runcode后右键题目失效

### ISSUE THREAD

**Issue by zhanghao1024** [shuzijun/leetcode-editor#229]
**Describe the bug**

**To Reproduce**

**Software versions(*Help* -> *About*)**
- Product: [e.g IDEA 2020.2]
- Runtime version:[e.g 11.0.7+10-b944.20 amd64]
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS:[e.g Windows 10]

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:
  ```
  
  ```

**Comment by shuzijun** [comment]
没有复现这个问题,补充一下issues中的复现步骤、版本信息和问题截图

**Comment by zhanghao1024** [comment]
idea版本2020.1.2 leetcode版本6.7
经常出现右键点击无效的情况
![image](https://user-images.githubusercontent.com/63036156/91020012-7a1aa880-e624-11ea-9ca6-a4fabc8ce173.png)

**Comment by shuzijun** [comment]
右键点击的有效区域是列表节点的文字上，确认下失效的情况下鼠标是否在别的区域。

**Comment by zhanghao1024** [comment]
好像是这样。。。没点在文字上
