### ISSUE TITLE
可以添加代理功能吗

### ISSUE THREAD

**Issue by phlamenco** [shuzijun/leetcode-editor#23]
因为内网需要通过代理才能访问外网，在设置了IDEA的代理后仍然无法使用插件（超时），请问可以支持一下代理设置吗？

**Comment by shuzijun** [comment]
已收到相关需求,后续增加 https://github.com/shuzijun/leetcode-editor/issues/19#issuecomment-485775730

**Comment by shuzijun** [comment]
@phlamenco  [V4.2](https://raw.githubusercontent.com/shuzijun/leetcode-editor/master/doc/leetcode-editor-V4.2.zip)已添加支持代理，生效方式为配置IDEA的代理后再插件配置页勾选prox。目前只支持http方式。
