### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by chinafuhai** [shuzijun/leetcode-editor#232]
提交代码后报这个错误
	info
			运行失败:
			SyntaxError: invalid syntax
			^
			def lengthOfLongestSubstring(self, s: str) -> int:
			Line 2  (Solution.py)
			测试用例:"abcabcbb"
			stdout:

**Comment by shuzijun** [comment]
请按照问题模板提供题目和提交代码的相关信息
