### ISSUE TITLE
使用 cookie 登录失败

### ISSUE THREAD

**Issue by patchBig** [shuzijun/leetcode-editor#233]
![image](https://user-images.githubusercontent.com/25219300/90328847-5dea8c00-dfd2-11ea-8625-2ebcac52a1e7.png)
粘贴 cookie 到 login 弹窗内，提示登录失败

**Comment by shuzijun** [comment]
复制时不要复制Cookie:这几个字符，检查右下角叹号是否有具体错误。

**Comment by patchBig** [comment]
辛苦了 今天可以了 ε(┬┬﹏┬┬)3
