### ISSUE TITLE
[已解决] IDEA 2020.2 题目无法打开

### ISSUE THREAD

**Issue by ViKingGeeker** [shuzijun/leetcode-editor#234]
**Describe the bug**

> IDEA 2020.2版本 

- open question打不开

- open content打不开

- 双击题目无法打开

右下角小括号包含两个异常
- stacktrace.txt 
_保存文件错误
java.io.IOException: 系统找不到指定的路径。_
- induced.txt
_Caused by: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/intellij/openapi/fileEditor/OpenFileDescriptor.<init> must not be null_

**Comment by shuzijun** [comment]
检查一下TempFilePath路径是否存在和是否有权限进行读写操作

**Comment by ViKingGeeker** [comment]
> 
> 
> 检查一下TempFilePath路径是否存在和是否有权限进行读写操作

您说得对，我之前TempFilePath路径选得是没有读写权限的c:/programfile目录，改了就好了
