### ISSUE TITLE
C++ code template issue

### ISSUE THREAD

**Issue by mc-marcocheng** [shuzijun/leetcode-editor#235]
When I type "#include <bits/stdc++.h>" in the code template, the generated code doesn't contain the "#include". (The code becomes " <bits/stdc++.h>")

Luckily I found a way to get around: I typed "/#include <bits/stdc++.h>" and it generates the correct code: "#include <bits/stdc++.h>". But the situation, to me, isn't ideal. Thanks.

**Comment by shuzijun** [comment]
I'm sorry about that. The function of the template is dependent on [velocity](https://velocity.apache.org/engine/2.2/user-guide.html), "#" is the keyword, I cannot modify this definition, you can escape it with "\\".
