### ISSUE TITLE
希望可以调整代码的保存位置

### ISSUE THREAD

**Issue by ActonMartin** [shuzijun/leetcode-editor#238]
**Is your feature request related to a problem? Please describe.**
在我使用的过程中发现，虽然设置了临时目录，但是代码文件，题解题目的md文件都是在设置的文件夹下面的子文件夹里面进行保存的，希望可以调整逻辑，代码就在设置的当前目录进行保存，其他的题解题目的md文件可以保存在另外的子文件夹里面，这样我就可以只需要写.gitignore文件过滤掉不需要上传的文件了，不用重新移动代码文件了。

**Comment by caomu** [comment]
我也希望有这个功能
我用java ，如果在多个文件中新建了同名的子类，ide经常搞不清我调用的是哪个

**Comment by zooltd** [comment]
+1
