### ISSUE TITLE
需要两个快捷键Run code, Submit

### ISSUE THREAD

**Issue by ohkimchi** [shuzijun/leetcode-editor#24]
现在是我要右键题目然后选择Run Code or Submit，大佬可不可以加两个快捷键，比如Ctrl + Command + R, Ctrl + Command + S，谢谢啦。

**Comment by shuzijun** [comment]
**File** -> **Settings** ->**Keymap** ->**Plug-ins** ->**leetcode editor** 可以绑定对应操作的快捷键

**Comment by ohkimchi** [comment]
解决了，谢谢！
