### ISSUE TITLE
Markdown display error when right click on open solution

### ISSUE THREAD

**Issue by fengyinqiao** [shuzijun/leetcode-editor#240]
- Product: IDEA 2018.3
- VM:OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- OS:Windows 10

markdown display error:
![image](https://user-images.githubusercontent.com/58540165/91952184-6dd4d080-ed33-11ea-8510-6566122b44a6.png)

**Comment by shuzijun** [comment]
提供下题目变化和对应的解题标题

**Comment by fengyinqiao** [comment]
@shuzijun 53、最大子序和

**Comment by shuzijun** [comment]
在2018.3上没有复现此问题,检查下markdown版本是否有新版本和在文档目录下图片p__max_{0_leq_i_leq_n_-_1}_{_f_i__}_.png是否存在。  
在IDEA早期版本中，markdown插件加载图片对内存消耗很大，可能有其他未知产生。
![20200903100748](https://user-images.githubusercontent.com/27667179/92063282-6b26b980-edcd-11ea-973c-54ce5de55942.png)
