### ISSUE TITLE
打卡每日一题会出现超时

### ISSUE THREAD

**Issue by songjiang951130** [shuzijun/leetcode-editor#241]
**Describe the bug**
今日每日一题：https://leetcode-cn.com/problems/binary-tree-paths/submissions/
也就是problem列表里面第一个：
event log日志如下：
3:09 下午	info: 已提交,请稍等
3:09 下午	info: 等待结果超时
3:09 下午	info: 已提交,请稍等
3:10 下午	info: 等待结果超时
然后直接去网站看发现是已经提交成功了

最后建议每日一题可以领取积分

**Software versions(*Help* -> *About*)**
- Product:  IDEA 社区版 2020.2
- Runtime version:java 14
- VM: OpenJDK 64-Bit Server VM 
- OS:mac

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:
  ```
  class Solution {
    public List<String> binaryTreePaths(TreeNode root) {
        List<String> result = new LinkedList<>();
        if (root == null) {
            return result;
        }
        path(root, result, "");
        return result;
    }

    private void path(TreeNode root, List<String> result, String path) {
        if (root == null) {
            return;
        }
        if (root.left == null && root.right == null) {
            path +=root.val;
            result.add(path);
            return;
        }
        path = path +root.val +"->";
        path(root.right, result, path);
        path(root.left, result, path);
    }
}
  ```

**Comment by shuzijun** [comment]
测试一下，可以正常返回。应该是当时服务器在15s内没有返回结果，会提示等待结果超时。
签到等与解题无很大关系的功能暂时没有考虑。

**Comment by songjiang951130** [comment]
> 测试一下，可以正常返回。应该是当时服务器在15s内没有返回结果，会提示等待结果超时。
> 签到等与解题无很大关系的功能暂时没有考虑。

当时试了好几次都不行，难道是当时服务器不行嘛
