### ISSUE TITLE
idea  使用此插件 Java代码自动提示是不是不对

### ISSUE THREAD

**Issue by guoxianwei-ying** [shuzijun/leetcode-editor#242]
**Describe the bug**

**To Reproduce**

**Software versions(*Help* -> *About*)**
- Product: [e.g IDEA 2020.2]
- Runtime version:[e.g 11.0.7+10-b944.20 amd64]
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS:[e.g Windows 10]

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:
  ```
  
  ```
![2a6bcd2140a25ee1d36fff103fa0d47](https://user-images.githubusercontent.com/66160167/92233263-8afbd180-eee2-11ea-9004-397b7396619d.png)

**Comment by shuzijun** [comment]
代码提示是依赖于IDEA的功能,插件没有相关功能，建议检查项目配置的运行环境
