### ISSUE TITLE
Save list of files generated by the plugin into TempFilePath

### ISSUE THREAD

**Issue by ryanzlu** [shuzijun/leetcode-editor#248]
**Is your feature request related to a problem? Please describe.**
I normally commit the TempFilePath into a repo. When I clone the repo into a new computer, the leetcode context menu would not show up for old files.

**Describe the solution you'd like**
In https://github.com/shuzijun/leetcode-editor/pull/169, it is said the list of generated files are stored within com.shuzijun.leetcode.plugin.setting.ProjectConfig.InnerState#projectConfig. Thus potentially we can save the list into a file like all.json and load from the file as needed.

**Comment by shuzijun** [comment]
Whether to display the data of the editor menu is saved in the project's .idea/leetcode/editor.xml file, you can submit this file to the remote end, but the directory in this file is a bound physical directory, which requires a new computer and the original computer The project directory remains the same.

**Comment by ryanzlu** [comment]
Thanks! Committing .idea/leetcode/editor.xml solves the issue!
