### ISSUE TITLE
登录失败，一直提示请先登录，

### ISSUE THREAD

**Issue by SiMaLaoShi** [shuzijun/leetcode-editor#249]
我用.cn在谷歌浏览器上登录是可以的，账号密码没错，可以用cook登录但是没有看到有这个选项，run的时候一直提示请先登录
![image](https://user-images.githubusercontent.com/28924681/93289411-e0a07a00-f810-11ea-8875-1b3f86388e75.png)

**Comment by shuzijun** [comment]
参考##212
