### ISSUE TITLE
Feature to hide related topics (like "hashtable", "dp") for new questions

### ISSUE THREAD

**Issue by Zackhardtoname** [shuzijun/leetcode-editor#253]
**Is your feature request related to a problem? Please describe.**
The related topics server as hints and decrease the difficulty of the problems.

**Describe the solution you'd like**
Have a setting that lets us choose whether to hide them for new questions

**Additional context**

**Comment by shuzijun** [comment]
enable **Custom code template**
CodeTemplate replaces **${question.content}** with **$question.content.replaceAll("Related\sTopics.*","")**

**Comment by Zackhardtoname** [comment]
Oh that works! Thank you!
