### ISSUE TITLE
创建这些文件夹是出于什么考虑呢？leetcode/editor/cn

### ISSUE THREAD

**Issue by TianYongwei** [shuzijun/leetcode-editor#256]
![image](https://user-images.githubusercontent.com/8191867/96219867-4a4fa780-0fba-11eb-8238-a5bdcd3eda14.png)

**Comment by shuzijun** [comment]
在默认路径后追加leetcode/editor是为了方便清理数据与防止用户误删数据，在工具栏中有一个功能是清理所有缓存数据的。
/cn与/en是区别两个网站的数据，两个网址存储的部分数据文件名是一样的，防止相互覆盖。

**Comment by TianYongwei** [comment]
好的 谢谢。
