### ISSUE TITLE
[Feature] Signing in using GitHub Authentication?

### ISSUE THREAD

**Issue by Rainyforest** [shuzijun/leetcode-editor#258]
Does this plugin only support username password login？ I wish there could be a way to log in using GitHub account.

**Comment by blangero** [comment]
Hi @Rainyforest ,

During login there'll be a popup for Cookie, I tried with wrong password and correct Cookie and it works perfectly.
Kindly give it a try!

Regards,
Blan

**Comment by adme30** [comment]
可以试试[LeetCode Assistant](https://plugins.jetbrains.com/plugin/16770-leetcode-assistant/documentation), 免费使用。

**Comment by shuzijun** [comment]
You can use other methods to log in on the pop-up web page.
