### ISSUE TITLE
关于代码缓存

### ISSUE THREAD

**Issue by objcoding** [shuzijun/leetcode-editor#259]
**Is your feature request related to a problem? Please describe.**
想问下，可以将leetcode已做过的题的代码拉下来么？

**Describe the solution you'd like**

**Additional context**

**Comment by zhonghanwen** [comment]
如果拉下来，是否可以做本地存储

**Comment by shuzijun** [comment]
可以通过Submissions查看历史提交记录,但是只包括代码部分。
本地的代码都是保存在文件中，文件路径在配置中的TempFilePath
