### ISSUE TITLE
可以在题目列表部分加一个计时器吗

### ISSUE THREAD

**Issue by ohkimchi** [shuzijun/leetcode-editor#26]
比如设置一个时间限制，半个小时。等过了半个小时题目还没Success，就提示超时。目的是提高做题效率。提前谢谢大佬

**Comment by shuzijun** [comment]
没有一个操作是能说明已经开始做题了，后期可能会加上文件打开时间，但现在主要优化方向在自定义格式上

**Comment by josonle** [comment]
> 没有一个操作是能说明已经开始做题了，后期可能会加上文件打开时间，但现在主要优化方向在自定义格式上

可以仅仅是设置一个计时器，由用户手动点击代表开始做题
