### ISSUE TITLE
Submit Time Limit Exceeded

### ISSUE THREAD

**Issue by ShuningWan** [shuzijun/leetcode-editor#260]
**Describe the bug**
Submit TwoSum Question

**To Reproduce**
Submit TwoSum Question
![image](https://user-images.githubusercontent.com/31086770/98910198-d42d5a80-24fd-11eb-9b21-8faa139132ee.png)

**Software versions**
- Product: IDEA 2017.2.5
- Runtime version:[e.g 11.0.7+10-b944.20 amd64]
- VM: HotSpot 64Bit -25.131-b11
- OS:Windows 10

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:

![image](https://user-images.githubusercontent.com/31086770/98910537-49009480-24fe-11eb-9512-f36553e58df6.png)

**Comment by shuzijun** [comment]
This is restricted by leetcode

**Comment by ShuningWan** [comment]
I thought it was a problem with the test case, thank you

**Comment by ShuningWan** [comment]
> This is restricted by leetcode

I thought it was a problem with the test case, thank you
