### ISSUE TITLE
问题的标题可以支持中文吗?

### ISSUE THREAD

**Issue by zhonghanwen** [shuzijun/leetcode-editor#261]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
![图片](https://user-images.githubusercontent.com/12220537/99080353-26ed3c00-25fc-11eb-8b57-8536bf852d6b.png)

**Comment by shuzijun** [comment]
配置里URL选择leetcode-cn.com支持中文，leetcode.com网站不支持

**Comment by zhonghanwen** [comment]
@shuzijun 配置里URL已经选的是leetcode-cn.com了

**Comment by zhonghanwen** [comment]
更新最新版本已解决这个问题，感谢！！！
