### ISSUE TITLE
多语言解题

### ISSUE THREAD

**Issue by yummy-zc** [shuzijun/leetcode-editor#262]
想同时使用 java 和 JavaScript 同时来解题，如何做到

**Comment by shuzijun** [comment]
在打开题目前在配置界面更改code type

**Comment by 321927153** [comment]
> 在打开题目前在配置界面更改code type

![image](https://user-images.githubusercontent.com/24849723/107953182-baf0ea00-6fd5-11eb-9428-0282ac100df5.png)
在配置界面找不到code style选项
