### ISSUE TITLE
Only Java solution can be used?

### ISSUE THREAD

**Issue by candyflossc** [shuzijun/leetcode-editor#264]
**Desc**
Start a discussion or ask for help

**Software versions(*Help* -> *About*)(Optional)**
- Product: [e.g IDEA 2020.2]
- Runtime version:[e.g 11.0.7+10-b944.20 amd64]
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS:[e.g Windows 10]

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:
  ```
  
  ```

**Comment by candyflossc** [comment]
How to switch to python solution?

**Comment by shuzijun** [comment]
https://github.com/shuzijun/leetcode-editor#configuration-configuration-for-first-installation
switch: Code Type

**Comment by candyflossc** [comment]
> https://github.com/shuzijun/leetcode-editor#configuration-configuration-for-first-installation
> switch: Code Type

Thank you for your reply. But I mean the solution page as follows. The provided solution is still java even though I have set the code type as python.
![Screenshot](https://user-images.githubusercontent.com/41686792/100443670-1b624080-30e5-11eb-8931-05cd047e24de.png)

**Comment by shuzijun** [comment]
Not supported temporarily, can be used as a future enhancement.
