### ISSUE TITLE
显示filter完的题目数量

### ISSUE THREAD

**Issue by ohkimchi** [shuzijun/leetcode-editor#27]
在那个交集符号n的右边可以显示题目的数量吗，比如我filter by tag，选了heap, 列出了32道题，所以在n的右边显示(32)。

如下
Difficulty˘ Status˘ Lists˘ Tags˘ ⧠ 口 n (32)

**Comment by shuzijun** [comment]
更新4.2版本已支持展示题目数量[v4.2](https://raw.githubusercontent.com/shuzijun/leetcode-editor/master/doc/leetcode-editor-V4.2.zip)

**Comment by ohkimchi** [comment]
thank you shuzijun!
