### ISSUE TITLE
${question.content}优化

### ISSUE THREAD

**Issue by qiforan** [shuzijun/leetcode-editor#271]
观察到 `${question.content}` 是由单行注释（ `//` ）构成，但是看起来不够舒服，希望：

1. 多行注释版本，即 `/**/`。

2. 注释内容和 注释符号 之间能否保存一定数量的空格。

3. 优化单词排版，使之不被换行符割裂。

**Comment by houhaibushihai** [comment]
插楼问一个问题，我在插件设置中将`CodeTemplate`设置为仅保留题目预留代码。保存退出后。

![截屏2020-12-23 13.12.56.png](http://ww1.sinaimg.cn/large/ec19beedly1glxq7s0mogj20q00au74k.jpg)

接下来做题的时候，效果如下：

![截屏2020-12-23 13.13.31](http://ww1.sinaimg.cn/large/ec19beedly1glxq663mkwj21220bgwf8.jpg)

我是想问第`1`行和第`7`行，可以删除掉吗？因为我在`debug`的时候前面有`--BEGIN--`占了一行，导致提交后反馈的`bug`所在行和本地IDEA中的行号不一致。

希望插件可以默认不加载第`1`行和第`7`行。

**Comment by shuzijun** [comment]
> 插楼问一个问题，我在插件设置中将`CodeTemplate`设置为仅保留题目预留代码。保存退出后。
> 
> ![截屏2020-12-23 13.12.56.png](https://camo.githubusercontent.com/b534bc62293d051609b82e2a7b8872d3cf18fcfb01b282e53479dabce7192cbb/687474703a2f2f7777312e73696e61696d672e636e2f6c617267652f65633139626565646c7931676c78713773306d6f676a3230713030617537346b2e6a7067)
> 
> 接下来做题的时候，效果如下：
> 
> ![截屏2020-12-23 13.13.31](https://camo.githubusercontent.com/c626c7cc07685af048b391e52d6dac140b1f46cebd9665b584a58c14981f73a9/687474703a2f2f7777312e73696e61696d672e636e2f6c617267652f65633139626565646c7931676c78713636336d6b776a323132323062677766382e6a7067)
> 
> 我是想问第`1`行和第`7`行，可以删除掉吗？因为我在`debug`的时候前面有`--BEGIN--`占了一行，导致提交后反馈的`bug`所在行和本地IDEA中的行号不一致。
> 
> 希望插件可以默认不加载第`1`行和第`7`行。

参考#89

**Comment by houhaibushihai** [comment]
谢谢！帮到我了。成功解决！

shuzijun <notifications@github.com> 于2020年12月25日周五 下午5:51写道：

**Comment by tianwg** [comment]
> 观察到 `${question.content}` 是由单行注释（ `//` ）构成，但是看起来不够舒服，希望：
> 
>     1. 多行注释版本，即 `/**/`。
> 
>     2. 注释内容和 注释符号 之间能否保存一定数量的空格。
> 
>     3. 优化单词排版，使之不被换行符割裂。

同意， 希望`{question.content}`可以可以直接做成
/**
<html>
*/
包含html 格式的内容。 Intellij 最新版本支持的 Javadoc  rendered view 可以完美还原问题格式，可以不用多open content这一步了。 本地改了一下，看着还算舒服：

<img width="903" alt="image" src="https://user-images.githubusercontent.com/3421474/113598846-bf1baa00-960b-11eb-81ec-37e6c0868910.png">

**Comment by pangjac** [comment]
Issue 1,
使用 如下设置没有问题
![image](https://user-images.githubusercontent.com/13987136/117857381-b6e20a80-b25a-11eb-847c-1b7163283906.png)
但如果尝试把 `${question.code}` 改为 `$question.code.replaceAll("//leetcode\ssubmit\sregion.*","")` (参考 #89 ) 则会出现compile-error ： class interface or enum expected error 报错位置为package leetcode.editor.en; 所在的line

Issue 2.
无法定制化package name, package name 必须为 xxx.leetcode.editor.cn; 如果manually设置package name 比如 src.smarteditor; 并且不再customconfig中设置package name 仍然会自动设置package name 为 leetcode.editor.cn; 并自动create a new package.

**Comment by 2292384454** [comment]
> > > 观察到 `${question.content}` 是由单行注释（ `//` ）构成，但是看起来不够舒服，希望：
> > > ```
> > > 1. 多行注释版本，即 `/**/`。
> > > 
> > > 2. 注释内容和 注释符号 之间能否保存一定数量的空格。
> > > 
> > > 3. 优化单词排版，使之不被换行符割裂。
> > > ```
> > 
> > 
> > 同意， 希望`{question.content}`可以直接做成
> > /**
> > html
> > */
> > 生成comment的时候包含html 格式的内容。 Intellij 最新版本支持的 Javadoc rendered view 可以完美还原问题格式，可以不用多open content这一步了。 本地改了一下，看着还算舒服：
> > <img alt="image" width="903" src="https://user-images.githubusercontent.com/3421474/113598846-bf1baa00-960b-11eb-81ec-37e6c0868910.png">
> 
> 您好 请问可以share一下如何不用open content渲染题目图片的方法吗？ 感谢！

在 com/shuzijun/leetcode/plugin/manager/CodeManager.java 中做如下修改：
1、注释掉第 45 行代码，即 CodeManager()  构造函数中的这个if语句中第一句代码
![image](https://user-images.githubusercontent.com/30790929/123539510-b64ef600-d76c-11eb-9fd3-380285ecc795.png)
2、修改第 308 行为 sb.append("<p>");
重新buildPlugin，把压缩包拖进IDEA中即可覆盖原有插件。
在设置界面做类似如下设置：
![image](https://user-images.githubusercontent.com/30790929/123539591-134aac00-d76d-11eb-913a-658c3cae3142.png)
开启IDEA的阅读模式即可。
这样最大的好处在于可以显示图片了，对于阅读需要图片描述的题目更方便了，效果如下：
![image](https://user-images.githubusercontent.com/30790929/123539808-16926780-d76e-11eb-9e1e-ba88de6e9de4.png)
