### ISSUE TITLE
一个关于题目编号的小特性

### ISSUE THREAD

**Issue by MomentDerek** [shuzijun/leetcode-editor#275]
首先是《剑指offer》等本地化系列的题目，题目编号会有问题，我觉得可以弄一个编号的转换规则列表，通过正则进行转换，这个转换用户可以自定义，也可使用默认的
嗯……不大清楚是靠文件名识别题目的还是怎么，如果这个问题不解决，这些本地化的题目都没法提交答案，会显示“提交的代码不存在”
如果是这样的话，应该在生成题目的代码文件时，进行转换会比较好吧，将这个信息写入json里面，或者直接在json文件里面缓存文件名，以便给用户提供手动修改的可能？
![image](https://user-images.githubusercontent.com/40252940/104515851-5507f000-562e-11eb-8d86-393d8f33f05a.png)
![image](https://user-images.githubusercontent.com/40252940/104515877-60f3b200-562e-11eb-9536-8b37735bc7f6.png)

**Comment by shuzijun** [comment]
详细描述下出现的场景，通过插件提交测试未出现描述的异常。

**Comment by MomentDerek** [comment]
嗯……我看了大概懂了，我在类前面加了题目的编号，我类名是这样写的：
`$!{question.frontendQuestionId}_$!velocityTool.camelCaseName(${question.titleSlug})`
是为了回来找题目的时候好找来着……如果是按照你在leetcode-question中的例子来配置确实没这个问题

**Comment by MomentDerek** [comment]
那我还是关了这两个issue吧……
