### ISSUE TITLE
一个关于题目信息获取的特性

### ISSUE THREAD

**Issue by MomentDerek** [shuzijun/leetcode-editor#276]
还有一个问题，很多题目的执行函数名和题目名不是一一对应的，在生成模板的时候可能会存在一些问题，可不可以将这个函数名提取出来，然后变成可以使用的模板参数？也是使用正则之类的
比如这个，第240号题目
![image](https://user-images.githubusercontent.com/40252940/104516930-25f27e00-5630-11eb-819b-c8025f953757.png)

**Comment by shuzijun** [comment]
java可以参考https://github.com/shuzijun/leetcode-question，可以详细描述下存在的问题
