### ISSUE TITLE
最新版本的clion不支持

### ISSUE THREAD

**Issue by dencesun** [shuzijun/leetcode-editor#281]
**Describe the bug**
![image](https://user-images.githubusercontent.com/9604835/106540845-bd663500-653b-11eb-9711-5c0dcedc2900.png)

![image](https://user-images.githubusercontent.com/9604835/106540873-c9ea8d80-653b-11eb-883c-8371226ad452.png)

**To Reproduce**

**Software versions(*Help* -> *About*)**
- Product: [e.g IDEA 2020.2]
- Runtime version:[e.g 11.0.7+10-b944.20 amd64]
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS:[e.g Windows 10]

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:
  ```
  
  ```

**Comment by shuzijun** [comment]
参考#197 进行检查
