### ISSUE TITLE
Feature request - Ability to choose a session?

### ISSUE THREAD

**Issue by harishzen** [shuzijun/leetcode-editor#282]
**Is your feature request related to a problem? Please describe.**
Leetcode has the ability to choose a session in a single user login 

**Describe the solution you'd like**
This is very useful when you are revising the solved questions again .
Need a way to choose the session in the IDE

**Additional context**

**Comment by shuzijun** [comment]
![20210205132642](https://user-images.githubusercontent.com/27667179/106993522-d8dc7480-67b5-11eb-9d99-fcede3c27805.png)
This function?

**Comment by harishzen** [comment]
Yeah . You are right. This was what was needed. A little burried inside but works for me.
