### ISSUE TITLE
module not specified

### ISSUE THREAD

**Issue by YuwenHu** [shuzijun/leetcode-editor#284]
**Desc**
When I clicked the run button, idea shows me the error below. Should I download or renew anything for this leetcode plugin?
<img width="959" alt="leetcode_plugin" src="https://user-images.githubusercontent.com/31275560/107138236-415e5980-694e-11eb-9892-d7e9d30bb13a.PNG">

**Software versions(*Help* -> *About*)(Optional)**
IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 30, 2020
Licensed to IntelliJ IDEA Evaluator
Expiration date: February 25, 2021
Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 976M
Cores: 4
Non-Bundled Plugins: io.zhile.research.ide-eval-resetter

**Comment by Kingdom111111** [comment]
怎么解决， 我这边也是在idea里， 通过main方法， 无法启用调试

**Comment by shuzijun** [comment]
> 怎么解决， 我这边也是在idea里， 通过main方法， 无法启用调试


@Kingdom111111 阅读下 [自定义代码](https://github.com/shuzijun/leetcode-editor/blob/master/doc/CustomCode_ZH.md), 里面有个demo
