### ISSUE TITLE
希望可以把leetcode返回的调试结果都打印出来

### ISSUE THREAD

**Issue by caomu** [shuzijun/leetcode-editor#285]
现在在event log中展示的stdout， 如果过长都会被收到 【show balloon】里面， 希望这个地方可以控制成全部显示出来
即使不能完全显示，也最好能生成在log文件中，可以查看。
否则复制粘贴出去查看，换行会消失，看不太清楚

**Comment by shuzijun** [comment]
![event log](https://user-images.githubusercontent.com/27667179/108301571-3ec8f300-71dd-11eb-92af-fa5c99f1d8d3.png)
完整日志在event log中查看

**Comment by caomu** [comment]
![image](https://user-images.githubusercontent.com/4708137/108788918-6264b280-75bc-11eb-9769-d6d06a410630.png)
你好，在这种情况下，信息就展示不全了（是不是这种情况下leetcode也没有完全返回呢？）
此外，这种情况下要通过show ballon弹窗里面复制粘贴出来才能看内容，而此时复制粘贴出来的内容是没有换行符的。
请问，有没有好的方法优化一下呢？

**Comment by shuzijun** [comment]
测试了一下，确实会被截断，在网页中提交后展示也会被截断，但实际api返回的值是完整的。
搜索了一下论坛，发现show ballon里内容丢失回车与被截断已经有人反馈，参考https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000379004-Event-log-truncates-long-messages
对应的issue：https://youtrack.jetbrains.com/issue/IDEA-156267?_ga=2.188896750.459958067.1613974790-834966169.1613974790
这个需要等待JetBrains修复完善

**Comment by caomu** [comment]
都是17年的issue了，等着他修复是不知道等到什么时候了。。。
有没有什么办法放到日志文件里面去就好了
