### ISSUE TITLE
leetcode plugin 提示警告信息"请先登录"

### ISSUE THREAD

**Issue by mp-canglangshui** [shuzijun/leetcode-editor#286]
问题描述：

安装完leetcode 插件，并且设置完URL:leetcode-cn.com,loginName 和登录密码后，运行test-case，总是提示"请先登录"

![image](https://user-images.githubusercontent.com/64787499/107607703-eb9eef80-6c74-11eb-8640-8f421dd5cf7f.png)

运行环境：
os：win10
intellij idea 2019.3
leetcode-editor 6.7

**Comment by shuzijun** [comment]
参考#212
