### ISSUE TITLE
代码模板设置package leetcode.editor.cn.lesson${question.frontendQuestionId}后，运行代码时，提示代码不存在

### ISSUE THREAD

**Issue by mp-canglangshui** [shuzijun/leetcode-editor#289]
1、代码模板中设置了含表达式的包名“package leetcode.editor.cn.lesson${question.frontendQuestionId};”后，设置如图
![image](https://user-images.githubusercontent.com/64787499/108501085-b5541680-72eb-11eb-8d75-5c9ead7dd2d7.png)

2、当我runcode的时候，提示“提交的代码不存在”
![image](https://user-images.githubusercontent.com/64787499/108501409-357a7c00-72ec-11eb-8130-321409f6e07e.png)

3、需要把包名里面的变量删除后，才能解决。

4、也不算bug吧，使用习惯不一样，用户体验不是很好

**Comment by shuzijun** [comment]
测试没有问题。检查一下操作步骤是否有有误：
1.更换模板后需要重新生成代码文件，影响提交代码的是代码文件名与代码内的两行标识
2.检查右键时提交题目是否选择正确
3.可以尝试在代码区直接在右键菜单里run code
