### ISSUE TITLE
关于生成本地文件的问题

### ISSUE THREAD

**Issue by ghosx** [shuzijun/leetcode-editor#29]
我建议将文件组织成 /src/包名/Main.java 的形式，其中包名以题目url一部分组成，如：
https://leetcode-cn.com/problems/longest-palindromic-substring/
包名为 ：longest_palindromic_substring

**Comment by ghosx** [comment]
Main.java 文件具体如下：
```java 
public class Main {
    public static void main(String[] args) {
        
    }
}

class Solution {
    public String longestPalindrome(String s) {

    }
}
```

望采纳~

**Comment by shuzijun** [comment]
关于文件格式生成后续将提供模板配置方式
