### ISSUE TITLE
建议增加配置项，控制是否展示Related Topics

### ISSUE THREAD

**Issue by boatrainlsz** [shuzijun/leetcode-editor#293]
问题描述：
在题目描述中，会出现Related Topics提示，个人认为这项或者去掉，或者增加一个配置。
不过，Related Topics应该就是注释的一部分？这样就不好改了，总之这是一点小建议，请钧鉴。
![image](https://user-images.githubusercontent.com/18243785/110058985-576d0780-7d9e-11eb-9e5c-9a8bcca516b5.png)

**Comment by shuzijun** [comment]
参考#60

**Comment by boatrainlsz** [comment]
@shuzijun 十分感谢
