### ISSUE TITLE
双击题目生成的文件缺少package

### ISSUE THREAD

**Issue by ICLXL** [shuzijun/leetcode-editor#295]
![image](https://user-images.githubusercontent.com/30027321/111094373-20ed7480-8576-11eb-805d-e3e509c99903.png)
问题:生成的java文件缺少package
1.已配置Custom Template
系统:Windows 10专业版 20H2
idea version:idea 2020.3

**Comment by shuzijun** [comment]
配置界面截图提供一下

**Comment by ICLXL** [comment]
![image](https://user-images.githubusercontent.com/30027321/111150282-dcd78f80-85c8-11eb-9c96-b8b026a17ec7.png)

**Comment by shuzijun** [comment]
模板中没有配置包名，参考[CustomCode_ZH](https://github.com/shuzijun/leetcode-editor/blob/master/doc/CustomCode_ZH.md)

**Comment by ICLXL** [comment]
谢谢,解决了
