### ISSUE TITLE
CLion中登录成功后运行代码提示“请先登录”

### ISSUE THREAD

**Issue by y2-Whyto** [shuzijun/leetcode-editor#298]
**Desc**

I've already finished configuring the plugin according to readme and push the log-in button before, and it tells me successfully logged in. But when I right-click the problem and select 'run code' or 'testcase', it says please log in first.

我已经按照readme对插件进行了配置，并且在使用前点击了登录按钮，提示“登录成功”。但在题目上右键选择运行代码或者测试样例时又会显示“请先登录”。

![image](https://user-images.githubusercontent.com/42339192/111867744-eee27500-89b0-11eb-8622-691d608c6805.png)

**Software versions**
- Product: CLion 2020.3.3
- Runtime version: 11.0.10+8-b1145.96 x86_64
- VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- OS: macOS Big Sur 11.2.3

**Question(Optional)**
- URL: leetcode-cn.com
- Code Type: C++

**Comment by shuzijun** [comment]
在插件登录成功后，是否又在网页进行了登录？

**Comment by y2-Whyto** [comment]
> 在插件登录成功后，是否又在网页进行了登录？

之前确实是先登录的网页端，之后使用插件登录。
但是刚刚我将浏览器退出之后，在CLion中退出并重新登录，依然会出现上面描述的情况。

**Comment by shuzijun** [comment]
在相同版本下测试未复现此问题，可以尝试一下方式排查：
1.检查账号邮箱是否已经验证，账号在网页端提交代码是否正常
2.检查是否同时在线，leetcode-cn增加了限制，只允许一个在线，参考#222
3.尝试使用其他登录方式，参考[登录帮助](https://github.com/shuzijun/leetcode-editor/blob/master/doc/LoginHelp_ZH.md),leetcode-cn 把密码输错可触发其他两种

**Comment by y2-Whyto** [comment]
> 登录帮助

感谢提醒，我检查了一下我的账号，发现我在CLion上登录的是一个提交了注销申请的账号，我在CLion上利用cookie登录另一个正在使用中的账号（也就是浏览器实际登录的账号）没有问题。实在不好意思，是我自己搞错了，给您添了麻烦。谢谢您🙏
