### ISSUE TITLE
Steps to Integrate and get started

### ISSUE THREAD

**Issue by pradhan1234** [shuzijun/leetcode-editor#3]
Would it be possible for you to list the steps to integrate leetcode-editor with intellj and get started with using the same?

**Comment by pradhan1234** [comment]
I was able to add the plugin, unable to login to my account though

**Comment by pradhan1234** [comment]
Is it possible to change the language test/submit result to English?

**Comment by shuzijun** [comment]
> Is it possible to change the language test/submit result to English?

ok，Provide English documentation later

**Comment by shuzijun** [comment]
@pradhan1234  README.md Added demo.gif, This ([V2.1](https://github.com/shuzijun/leetcode-editor/blob/master/doc/leetcode-editor-V2.1.zip)) version adds English tips.
