### ISSUE TITLE
最新版，拉取代码失败

### ISSUE THREAD

**Issue by witmusk** [shuzijun/leetcode-editor#30]
获取代码失败

java.lang.NullPointerException
	at com.shuzijun.leetcode.plugin.utils.CommentUtils.createComment(CommentUtils.java:13)
	at com.shuzijun.leetcode.plugin.manager.CodeManager.openCode(CodeManager.java:70)
	at com.shuzijun.leetcode.plugin.listener.TreeMouseListener.mouseClicked(TreeMouseListener.java:49)

**Comment by shuzijun** [comment]
提供一下操作的截图及对应的题目

**Comment by witmusk** [comment]
![image](https://user-images.githubusercontent.com/3699893/58305492-da6fd880-7e2a-11e9-81d6-3fe9588a692c.png)

**Comment by witmusk** [comment]
@shuzijun 应该确认是题目的问题。 锁定的题目。

**Comment by lutianfei** [comment]
我也遇到这个问题了

**Comment by shuaixiaomi** [comment]
> 提供一下操作的截图及对应的题目

打开插件就报错
获取代码失败

com.alibaba.fastjson.JSONException: syntax error, pos 1, json : <html>
<body onload="check()">
	<input type="hidden" name="parm_0" value=238794288 id="parm_0">
	<input type="hidden" name="parm_1" value=2119991259 id="parm_1">
	<script type="text/javascript">
    function Z(){var U=['setDate','CPBoA','EuWuh','2692915LPvLJc','EyJtp','BnmBC','alicfw','wAXWR','toGMTString','ZCtne','dRcWF','WPKcA','gsyGC','VdsWn','VOeWP','vkRGS','PKfKs','VIwmN','clientHeight','qGSHB','6|2|0|4|7|8|1|3|5','2382APyAnZ','eOxRB','NaTvv','aKLEt','getDate','JjGpV','location','uOefP','length','szlwY','cookie','WHFvT','host','wiGeS','353784PLKrwL','BUlET',';path=/','NQYEZ','tmuPq','CyuZJ','protocol','split','reRGP','KdxMP','SLEuY','NRYtj','bGnGz','LRjWH','ngiRp','clientWidth','MeUzm','mGkxk','11511150QPbmwW','144ZPJzag','1914666ufUThb','auTOZ','1082904JoefgG','getElementById','YPShL','log','YNynO','mTySG',';expires=','3880AlRztD','NNQHb','5|4|6|0|2|3|8|9|7|1','dLMKj','v1.200309.1','FLGyw',';samesite=none;secure','bFSkT','zlyUs','ugWJY','Fbuli','ABLuu','fpiQy','RvZLO','vNwPb','DjXXN','hZCEl','https:','fyoal','dPGFj','2|5|0|6|1|4|3','GiIZm','charCodeAt','alicfw_gfver','fzCyE','value','ubdGA','BEMgz','DHkIL','LzWrw','reload','parm_0','1294479RTlfGo','VDyTo','ysIEr','14CZcKYt'];Z=function(){return U;};return Z();}(function(M,B){var V=a,j=M();while(!![]){try{var f=-parseInt(V(0x112))/0x1+parseInt(V(0x14d))/0x2+-parseInt(V(0x12b))/0x3*(parseInt(V(0x156))/0x4)+parseInt(V(0x119))/0x5+parseInt(V(0x14f))/0x6*(-parseInt(V(0x115))/0x7)+-parseInt(V(0x139))/0x8*(-parseInt(V(0x14c))/0x9)+parseInt(V(0x14b))/0xa;if(f===B)break;else j['push'](j['shift']());}catch(N){j['push'](j['shift']());}}}(Z,0xe2ccc));function hash32(M,B,j,f,N,j){var h=a,r={'PKfKs':function(g,z){return g>>>z;},'qGSHB':function(g,z){return g^z;},'tmuPq':function(g,z){return g+z;},'GiIZm':function(g,z){return g+z;},'JjGpV':function(g,z){return g%z;},'CPBoA':function(g,z){return g&z;},'eOxRB':function(g,z){return g-z;},'XBRlp':h(0x12a),'NaTvv':function(g,z){return g*z;},'KdxMP':function(g,z){return g<<z;},'LzWrw':function(g,z){return g&z;},'CyuZJ':function(g,z){return g>>>z;},'ZCtne':function(g,z){return g|z;},'dLMKj':function(g,z){return g<<z;},'gsyGC':function(g,z){return g>>>z;},'BEMgz':function(g,z){return g+z;},'VOeWP':function(g,z){return g*z;},'XigdA':function(g,z){return g>>>z;},'SLEuY':function(g,z){return g<<z;},'igwtY':function(g,z){return g>>>z;},'wAXWR':function(g,z){return g+z;},'auTOZ':function(g,z){return g&z;},'ngiRp':function(g,z){return g>>>z;},'vNwPb':function(g,z){return g&z;},'YPShL':function(g,z){return g&z;},'bGnGz':function(g,z){return g<<z;},'BnmBC':function(g,z){return g&z;},'jpGYf':function(g,z){return g+z;},'ugWJY':function(g,z){return g&z;},'DjXXN':function(g,z){return g+z;},'wgyga':function(g,z){return g&z;},'aKLEt':function(g,z){return g>>>z;},'LRjWH':function(g,z){return g|z;},'PAqHz':function(g,z){return g>>>z;},'qltHb':function(g,z){return g+z;},'bFSkT':function(g,z){return g*z;},'ABLuu':function(g,z){return g>>>z;},'szlwY':function(g,z){return g*z;},'reRGP':function(g,z){return g>>>z;},'BUlET':function(g,z){return g>>>z;},'fpiQy':function(g,z){return g&z;},'EuWuh':function(g,z){return g+z;},'VdsWn':function(g,z){return g&z;},'NQYEZ':function(g,z){return g&z;},'WPKcA':function(g,z){return g*z;},'jHvVc':function(g,z){return g>>>z;},'fyoal':function(g,z){return g+z;},'dPGFj':function(g,z){return g+z;},'NNQHb':function(g,z){return g+z;}};f=r['PKfKs'](f^0x4f2b3a41,0x0),N=r[h(0x129)](N,0x4f2b3a41)>>>0x0;var W=r[h(0x13d)](r[h(0x13d)](r[h(0x13d)](r[h(0x13d)](r[h(0x107)](M+'&'+B+'&',j),'&'),f),'&'),N),I,A,C,b,T,x,l,P,d,s;seed=r[h(0x130)](j,0x1f7480),I=r[h(0x117)](W[h(0x133)],0x3),A=r[h(0x12c)](W[h(0x133)],I),C=seed,T=0xcc9e2d51,l=0x1b873593,s=0x0;while(s<A){var u=r['XBRlp'][h(0x140)]('|'),p=0x0;while(!![]){switch(u[p++]){case'0':d=r[h(0x107)](r['NaTvv'](r[h(0x117)](d,0xffff),T),r['KdxMP'](r[h(0x10f)](r[h(0x12d)](r[h(0x13e)](d,0x10),T),0xffff),0x10))&0xffffffff;continue;case'1':C=r[h(0x11f)](r[h(0xf5)](C,0xd),r[h(0x122)](C,0x13));continue;case'2':++s;continue;case'3':b=r['LzWrw'](r[h(0x10d)](r[h(0x124)](r[h(0x10f)](C,0xffff),0x5),r[h(0xf5)](r['XigdA'](C,0x10)*0x5&0xffff,0x10)),0xffffffff);continue;case'4':d=r[h(0x143)](d,0xf)|r['igwtY'](d,0x11);continue;case'5':C=r[h(0x11d)](r[h(0x13d)](r[h(0x10f)](b,0xffff),0x6b64),r['auTOZ'](r[h(0x13d)](r[h(0x147)](b,0x10),0xe654),0xffff)<<0x10);continue;case'6':d=r['ZCtne'](W[h(0x108)](s)&0xff,r[h(0x100)](W[h(0x108)](++s),0xff)<<0x8)|r[h(0x142)](W[h(0x108)](++s)&0xff,0x10)|r[h(0x143)](W[h(0x108)](++s)&0xff,0x18);continue;case'7':d=r[h(0x151)](r[h(0x13d)](r[h(0x124)](d&0xffff,l),r[h(0x143)](r[h(0x12d)](r[h(0x126)](d,0x10),l)&0xffff,0x10)),0xffffffff);continue;case'8':C^=d;continue;}break;}}d=0x0;switch(I){case 0x3:d^=r[h(0x145)](r[h(0x11b)](W[h(0x108)](r['jpGYf'](s,0x2)),0xff),0x10);case 0x2:d^=r['dLMKj'](r['vNwPb'](W[h(0x108)](s+0x1),0xff),0x8);case 0x1:d^=r[h(0xfb)](W[h(0x108)](s),0xff),d=r[h(0x11b)](r[h(0x101)](r[h(0x12d)](r['wgyga'](d,0xffff),T),r[h(0x143)](r[h(0x12e)](d,0x10)*T&0xffff,0x10)),0xffffffff),d=r[h(0x146)](d<<0xf,r['PAqHz'](d,0x11)),d=r['qltHb'](r[h(0xf9)](r[h(0x14e)](d,0xffff),l),r[h(0x142)](r[h(0xfd)](d,0x10)*l&0xffff,0x10))&0xffffffff,C^=d;}return C^=W[h(0x133)],C^=C>>>0x10,C=r[h(0x10f)](r[h(0x13d)](r['vNwPb'](C,0xffff)*0x85ebca6b,r[h(0x117)](r[h(0x134)](r[h(0x141)](C,0x10),0x85ebca6b),0xffff)<<0x10),0xffffffff),C^=r[h(0x13a)](C,0xd),C=r[h(0xfe)](r[h(0x118)](r[h(0x12d)](r[h(0x123)](C,0xffff),0xc2b2ae35),r['dLMKj'](r[h(0x13c)](r[h(0x121)](r['jHvVc'](C,0x10),0xc2b2ae35),0xffff),0x10)),0xffffffff),C^=r[h(0x126)](C,0x10),result=r[h(0x104)](r[h(0x105)](r[h(0x157)](r[h(0x10d)](r[h(0x10d)](C>>>0x0,'|'),j)+'|',f),'|'),N),result;}function setCookie(M,B){var O=a,j={'EyJtp':O(0x106),'MeUzm':O(0x109),'hZCEl':function(b,T){return b+T;},'vkRGS':function(b,T){return b+T;},'mTySG':function(b,T){return b(T);},'uOefP':function(b,T){return b==T;},'zlyUs':';path=/','DHkIL':O(0xf8),'vBwOt':function(b,T){return b+T;},'mGkxk':function(b,T){return b+T;},'pReXq':function(b,T){return b(T);},'wiGeS':function(b,T){return b+T;},'WHFvT':';expires=','YNynO':function(b,T){return b+T;},'FLGyw':function(b,T){return b(T);},'ysIEr':function(b,T){return b+T;},'PHiYu':function(b,T){return b+T;},'VIwmN':function(b,T){return b(T);},'ubdGA':function(b,T){return b+T;},'RvZLO':O(0xf6)},f=j[O(0x11a)][O(0x140)]('|'),N=0x0;while(!![]){switch(f[N++]){case'0':var r=j[O(0x149)];continue;case'1':W[O(0x116)](j['hZCEl'](W[O(0x12f)](),B));continue;case'2':var W=new Date();continue;case'3':I?(document[O(0x135)]=j['vkRGS'](j['vkRGS'](j[O(0x125)](j[O(0x102)](A,'=')+j[O(0x154)](escape,M),j[O(0x132)](B,null)?'':O(0x155)+W[O(0x11e)]()),j[O(0xfa)]),j[O(0x10e)]),document[O(0x135)]=j['vBwOt'](j[O(0x125)](j[O(0x125)](j[O(0x14a)](r,'=')+j['pReXq'](escape,C),B==null?'':j['wiGeS'](j[O(0x136)],W[O(0x11e)]())),O(0x13b)),O(0xf8))):(document[O(0x135)]=j[O(0x153)](j['hZCEl'](j['hZCEl'](A,'='),j[O(0xf7)](escape,M))+(j[O(0x132)](B,null)?'':j[O(0x102)](O(0x155),W[O(0x11e)]())),j[O(0xfa)]),document[O(0x135)]=j[O(0x114)](j[O(0x138)](j['PHiYu'](r,'='),j[O(0x127)](escape,C))+(B==null?'':j[O(0x10c)](j[O(0x136)],W[O(0x11e)]())),j['zlyUs']));continue;case'4':var I=O(0x103)===document[O(0x131)][O(0x13f)]?!![]:![];continue;case'5':var A=O(0x11c);continue;case'6':var C=j[O(0xff)];continue;}break;}}function a(M,B){var j=Z();return a=function(f,N){f=f-0xf4;var r=j[f];return r;},a(M,B);}function check(){var R=a,M={'VDyTo':R(0xf4),'fzCyE':R(0x111),'NRYtj':function(C,b,T){return C(b,T);},'dRcWF':'parm_1','Fbuli':function(C,b,T,x,l,P,d){return C(b,T,x,l,P,d);}},B=M[R(0x113)][R(0x140)]('|'),j=0x0;while(!![]){switch(B[j++]){case'0':var f=document['documentElement'][R(0x148)];continue;case'1':window['location'][R(0x110)](!![]);continue;case'2':var N=document['documentElement'][R(0x128)];continue;case'3':var r=document[R(0x150)](M[R(0x10a)])[R(0x10b)];continue;case'4':console['log'](document['cookie']);continue;case'5':console[R(0x152)](document[R(0x131)][R(0x13f)]);continue;case'6':var W=window['location'][R(0x137)];continue;case'7':M[R(0x144)](setCookie,A,0x1);continue;case'8':var I=document[R(0x150)](M[R(0x120)])[R(0x10b)];continue;case'9':var A=M[R(0xfc)](hash32,W,r,I,f,N,I);continue;}break;}}
    </script>
</body>
</html>
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1436)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1322)
	at com.alibaba.fastjson.JSON.parse(JSON.java:152)
	at com.alibaba.fastjson.JSON.parse(JSON.java:162)
	at com.alibaba.fastjson.JSON.parse(JSON.java:131)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:223)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.getQuestion(QuestionManager.java:203)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.lambda$getQuestionByTitleSlug$1(QuestionManager.java:331)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by shuaixiaomi** [comment]
![image](https://user-images.githubusercontent.com/77660384/201862507-856201a7-8e65-4db1-a274-7e7426c9db4a.png)

**Comment by shuaixiaomi** [comment]
突然又好了，神奇

**Comment by Fyutong** [comment]
> 突然又好了，神奇

我也遇到了这个问题
