### ISSUE TITLE
代码模板无效

### ISSUE THREAD

**Issue by SiMaLaoShi** [shuzijun/leetcode-editor#300]
最近可能力扣更新了，模板无效
![image](https://user-images.githubusercontent.com/28924681/112087296-a9989000-8bc8-11eb-948d-0cff665a4158.png)

![image](https://user-images.githubusercontent.com/28924681/112087407-dd73b580-8bc8-11eb-9f00-31f401f271f1.png)
经过测试只有部分题目是这样

**Comment by shuzijun** [comment]
已经写了，这个题目没有java的代码
