### ISSUE TITLE
安装插件后右下角找不到插件

### ISSUE THREAD

**Issue by rubyuu** [shuzijun/leetcode-editor#301]
插件版本6.9
IntelliJ IDEA 2020.2.2 (Ultimate Edition)
macOS 10.15.6

重启IDE, 重装插件都试过了

**Comment by shuzijun** [comment]
界面截图

**Comment by rubyuu** [comment]
![Uploading WX20210323-152920@2x.png…]()

**Comment by rubyuu** [comment]
<img width="1792" alt="WX20210323-152920@2x" src="https://user-images.githubusercontent.com/48358221/112109983-3a816280-8bed-11eb-867b-858892de91bd.png">

**Comment by TLizzie** [comment]
同版本同问题

**Comment by shuzijun** [comment]
参考https://www.jetbrains.com/help/idea/documentation-tool-window.html

**Comment by TLizzie** [comment]
解决了 谢谢
