### ISSUE TITLE
请问能否增加给对应题目创建文件夹的功能配置项？

### ISSUE THREAD

**Issue by alexzhou** [shuzijun/leetcode-editor#304]
比如以go语言举例：
同一个文件夹下面不能有不同的package , 但是相同的package 下又不能有相同的重复声明function  (比如82，83题function 都是deleteDuplicates)，所以会碰到Goland 的错误提示。只能手动处理下: 给某个问题手动创建个文件夹，在把对应的代码文件放进去，不知作者考不考虑加入一个这样的功能

**Comment by shuzijun** [comment]
参考[自定义代码](https://github.com/shuzijun/leetcode-editor/blob/master/doc/CustomCode_ZH.md),在文件名上加上路径应该可以，例如${question.titleSlug}/${question.titleSlug}

**Comment by alexzhou** [comment]
wow , you save my day,谢谢回复
