### ISSUE TITLE
今天更新最新版本以后，题目变成英文了

### ISSUE THREAD

**Issue by thatJerrywu2020** [shuzijun/leetcode-editor#305]
**Describe the bug**
在本地目录里也是，之前都是中文命名的.java文件
今天更新以后再打开都是英文命名，并且之前做过的题目打开也是空的了，因为他在本地新建了一个英文名的文件。
求解。PS：今天改了code localdebug模板，是这个原因吗？

**Comment by shuzijun** [comment]
如果改了模板，文件名定义与原来不一致，会重新创建文件的
