### ISSUE TITLE
Support IDEA 2021.1

### ISSUE THREAD

**Issue by zhanggang807** [shuzijun/leetcode-editor#312]
Following exceptions happened soon after this one, most probably they are induced.   2021-04-08T15:35:05.191 java.lang.RuntimeException: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/intellij/openapi/fileEditor/OpenFileDescriptor.<init> must not be null 	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:157) 	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:428) 	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:433) 	at com.shuzijun.leetcode.plugin.utils.FileUtils.openFileEditorAndSaveState(FileUtils.java:267) 	at com.shuzijun.leetcode.plugin.manager.CodeManager.openCode(CodeManager.java:50) 	at com.shuzijun.leetcode.plugin.listener.TreeMouseListener$1.run(TreeMouseListener.java:54) 	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998) 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497) 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228) 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178) 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688) 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634) 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64) 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165) 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228) 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668) 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665) 	at java.base/java.security.AccessController.doPrivileged(Native Method) 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665) 	at java.base/java.lang.Thread.run(Thread.java:834) Caused by: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/intellij/openapi/fileEditor/OpenFileDescriptor.<init> must not be null 	at com.intellij.openapi.fileEditor.OpenFileDescriptor.$$$reportNull$$$0(OpenFileDescriptor.java) 	at com.intellij.openapi.fileEditor.OpenFileDescriptor.<init>(OpenFileDescriptor.java) 	at com.shuzijun.leetcode.plugin.utils.FileUtils.lambda$openFileEditorAndSaveState$2(FileUtils.java:269) 	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218) 	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21) 	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200) 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781) 	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$7(ApplicationImpl.java:428) 	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:134) 	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84) 	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133) 	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46) 	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189) 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776) 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727) 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721) 	at java.base/java.security.AccessController.doPrivileged(Native Method) 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746) 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969) 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839) 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449) 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808) 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448) 	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781) 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496) 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by w450434204** [comment]
我也遇到了，今天手贱插件升级，该插件使用不了了。请大神看看

**Comment by w450434204** [comment]
将插件版本由6.8版本更新至6.9版本，解决问题

**Comment by zhanggang807** [comment]
插件版本 就是6.9

**Comment by shuzijun** [comment]
> 插件版本 就是6.9

操作系统是什么？同时检查下配置的文件路径

**Comment by zhanggang807** [comment]
> > 插件版本 就是6.9
> 
> 操作系统是什么？同时检查下配置的文件路径
感谢问题解决了~
操作系统是macOS，是配置文件路径丢失了，可能是系统自删除的，因为使用的是系统的临时目录
改成自定义的了，防止以后再有目录丢失问题
