### ISSUE TITLE
[Enhancement] Customize "open in web" browser.

### ISSUE THREAD

**Issue by MijazzChan** [shuzijun/leetcode-editor#314]
**Is your feature request related to a problem? Please describe.**
Is it possible to configure the "open in web" action to use customized browser?

**Describe the solution you'd like**
Just like the way of configuring git-bash, maven binary. "Open in web" can be customized to "Firefox.exe path"(windows) or "google-chrome-stable path"(linux). 

**Additional context**

**Comment by shuzijun** [comment]
The SDK default behavior, refer to https://www.jetbrains.com/help/idea/settings-tools-web-browsers.html#defaultBrowser

**Comment by MijazzChan** [comment]
Thx.
