### ISSUE TITLE
题目描述无法展示图片

### ISSUE THREAD

**Issue by peakchen90** [shuzijun/leetcode-editor#323]
目前是通过代码注释的方式去描述题目，但是一些题目中包含图片，图片无法展示出来，看作者是否可以通过webview的方式把题目渲染出来（就比如说11题里就包含了图片）

**Comment by shuzijun** [comment]
使用open content

**Comment by shuzijun** [comment]
> 感谢前辈的设计和implementation, 请问能再详细介绍一下如何用open content 渲染题目图片吗？(我使用leetcode.com) 感谢！

在题目上右键会出现open content菜单，打开后是一个markdown文件，利用idea自带的markdown插件就可以看到图片了

**Comment by peakchen90** [comment]
get

**Comment by KeqiangWang** [comment]
> > 感谢前辈的设计和implementation, 请问能再详细介绍一下如何用open content 渲染题目图片吗？(我使用leetcode.com) 感谢！
> 
> 在题目上右键会出现open content菜单，打开后是一个markdown文件，利用idea自带的markdown插件就可以看到图片了
请问作者大大，还是无法显示是什么原因？pycharm本身设置的原因么

![image](https://user-images.githubusercontent.com/7007590/151691014-4e18886a-f1fe-4af6-8669-192bce51e554.png)
