### ISSUE TITLE
希望可以半屏编辑代码，半屏显示题目

### ISSUE THREAD

**Issue by yhsmer** [shuzijun/leetcode-editor#327]
首先这个插件非常好用，但是我觉得如果像vscode的leetcode插件那样，半屏编辑代码，半屏显示题目，使用体验会好很多

**Comment by shuzijun** [comment]
可以使用idea的分屏实现，拖动描述到上方或者左侧，例如
![分屏](https://user-images.githubusercontent.com/27667179/118209189-c51e6980-b49a-11eb-8a38-0e6ef9fc2a35.png)

**Comment by yhsmer** [comment]
感谢，这个确实可以，但是每次我都需要open question、open content、切换分屏三个步骤，如何能自动分屏显示就好了，像vscode中leetcode一样，编辑区不显示题目，只显示时间作者，题目在另外一个半屏显示

**Comment by inertiagrade** [comment]
可以试试 [LeetCode Assistant](https://plugins.jetbrains.com/plugin/16770-leetcode-assistant)

**Comment by realdeal9527** [comment]
我也希望有这个功能，附议附议附议。
主要是刷一些做过的题，做得很快，每次都要点一下其实还是挺麻烦的。

**Comment by realdeal9527** [comment]
如果提供这个功能，我立马请喝咖啡，穷学生只请得起这个了233333

**Comment by 1PLee** [comment]
如何取消这个自动双屏显示呀？我只想显示代码
