### ISSUE TITLE
希望去掉 保存文件位置后面的部分公共前缀 leetcode/cn  leetcode/en 

### ISSUE THREAD

**Issue by yanjinbin** [shuzijun/leetcode-editor#338]
希望去掉 保存文件位置后面的部分公共前缀 leetcode/cn  leetcode/en 
这个属于插件自动帮我创建好
实际上我不需要 这个前缀

**Comment by shuzijun** [comment]
为了插件在清理缓存文件时不误删其他文件，这个默认的文件夹不能被去掉。

**Comment by yanjinbin** [comment]
> 为了插件在清理缓存文件时不误删其他文件，这个默认的文件夹不能被去掉。

那希望自定义吧  挺难受的 自己可以魔改么?

**Comment by shuzijun** [comment]
修改后构建即可。https://github.com/shuzijun/leetcode-editor/blob/993a2b9d8fdaa2bd381e8eb0fbacc639b65892c5/src/main/java/com/shuzijun/leetcode/plugin/setting/PersistentConfig.java#L67

**Comment by actforjason** [comment]
@shuzijun Pro版怎么办？

**Comment by actforjason** [comment]
解决了，修改重编译了leetcode-editor-pro-2022.1.1.jar文件，替换`AppData\Roaming\JetBrains\PyCharm2021.3\plugins\leetcode-editor-pro\lib`里文件即可。
https://drive.google.com/file/d/1ajbEAlECqlNFfIclsDQPqGCafuP8qxJo/view?usp=sharing

**Comment by actforjason** [comment]
其实误删了也没事，JetBrain系列软件都有`显示历史记录`的功能，可以复原，不过跟系统的垃圾箱不接轨好像。

**Comment by shuzijun** [comment]
> 其实误删了也没事，JetBrain系列软件都有`显示历史记录`的功能，可以复原，不过跟系统的垃圾箱不接轨好像。

https://github.com/shuzijun/leetcode-editor/blob/993a2b9d8fdaa2bd381e8eb0fbacc639b65892c5/src/main/java/com/shuzijun/leetcode/plugin/actions/toolbar/ClearAllAction.java#L71

通过这种方式删除的不清楚是不是会有历史记录，还是尽量防止一个目录下，防止误删其他文件。

**Comment by actforjason** [comment]
![image](https://user-images.githubusercontent.com/57058325/157359362-a8a599da-2fbc-4ae5-8d91-70018627af15.png)
