### ISSUE TITLE
goland里没有代码提示

### ISSUE THREAD

**Issue by qiaocco** [shuzijun/leetcode-editor#339]
**Desc**
goland里写代码没有提示，而且代码会飘红
![image](https://user-images.githubusercontent.com/25075484/121379569-bb433580-c976-11eb-98c4-c8c1e9f3e6c3.png)

**Software versions(*Help* -> *About*)(Optional)**
- Product: goland 2021.1
- Runtime version:11.0.11+9-b1341.57 amd64
- VM:Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
- OS:linux

**Comment by Sc-glong** [comment]
我用goland安装这个插件后也是这样

**Comment by shuzijun** [comment]
如果是正常项目安装完插件后无提示和报错，提供下示例项目。
如果是从插件拉取题目后，题目代码无提示和报错，需要根据各语言特征，结合自定义模板和idea的配置构建一个项目。

**Comment by qiaocco** [comment]
leetcode 206: https://leetcode-cn.com/problems/reverse-linked-list/
解法一： 提交正确，但是goland飘红
```
func reverseList(head *ListNode) *ListNode {
	cur := head
	var prev *ListNode
	for cur != nil {
		next := cur.Next
		cur.Next = prev
		prev = cur
		cur = next
	}
	return prev
}

```
解法二：goland不飘红，但是提交报错：`Line 62: Char 37: cannot use param_1 (type *leetcode.ListNode) as type *ListNode in argument to __helper__ (solution.go)`
```
package main

type ListNode struct {
	Val  int
	Next *ListNode
}


func reverseList(head *ListNode) *ListNode {
	cur := head
	var prev *ListNode
	for cur != nil {
		next := cur.Next
		cur.Next = prev
		prev = cur
		cur = next
	}
	return prev

}

```

**Comment by shuzijun** [comment]
提交不能带package main，生成的代码里有两行标记，不能删除。详情参考[CustomCode](https://github.com/shuzijun/leetcode-editor/blob/master/doc/CustomCode_ZH.md)

**Comment by qiaocco** [comment]
我修改模板， 让它自动加上package main了，可以解决一部分问题了。多谢～
