### ISSUE TITLE
复制代码到Solution文件，提交的时候没有及时更新到

### ISSUE THREAD

**Issue by ironyreunion** [shuzijun/leetcode-editor#34]
idea 2017 在本地src文件写好代码，复制到插件提供的Solution文件中，然后submit，会是复制前的Solution文件。没有及时同步到代码，不知道为什么，请大神帮忙解释下

**Comment by shuzijun** [comment]
复制之后手动保存一下

**Comment by ironyreunion** [comment]
可是idea是自动保存的吧，我还特意关掉idea里的文件再submit的

**Comment by shuzijun** [comment]
在某些情况下idea的数据是没有刷新到硬盘的，提交的时候是直接从硬盘读取的文件。如果保存后submit的代码还是不对，可以先确认下本地文件中代码是否正确。

**Comment by yklove** [comment]
能否增加一个优化，提交前或者运行前自动保存一下 :joy:

**Comment by ironyreunion** [comment]
> 在某些情况下idea的数据是没有刷新到硬盘的，提交的时候是直接从硬盘读取的文件。如果保存后submit的代码还是不对，可以先确认下本地文件中代码是否正确。

谢谢解答辣
