### ISSUE TITLE
对于树结构，大佬考虑下能否支持本地调试呢？

### ISSUE THREAD

**Issue by ebenrose78** [shuzijun/leetcode-editor#340]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by shuzijun** [comment]
描述一下具体的场景与需求

**Comment by 2292384454** [comment]
你可以先做一下 leetcode 297题，那道题的答案其实就可以满足你的需求。我的 TreeNode 类提供了一个根据层序遍历创建二叉树的方法，重写了toString方法实现二叉树按照层序遍历数组形式输出，你可以直接把它加到你的刷题目录下直接用。 地址：https://github.com/2292384454/Auxiliary-class-for-debugging-tree-problems-in-LeetCode 。这种功能我觉得可能不会往插件里面加也没有必要。

**Comment by PowerDi** [comment]
> 你可以先做一下 leetcode 297题，那道题的答案其实就可以满足你的需求。我的 TreeNode 类提供了一个根据层序遍历创建二叉树的方法，重写了toString方法实现二叉树按照层序遍历数组形式输出，你可以直接把它加到你的刷题目录下直接用。 地址：https://github.com/2292384454/Auxiliary-class-for-debugging-tree-problems-in-LeetCode 。这种功能我觉得可能不会往插件里面加也没有必要。

心疼，我自己没有能力能改成c++的版本
