### ISSUE TITLE
What are the steps to debugging locally for python?

### ISSUE THREAD

**Issue by datavistics** [shuzijun/leetcode-editor#342]
**Desc**
I didnt understand what to put into the settings from the gif. Can you let me know what the steps are?

Specifically is there a way to get `method_name`?

```
s = Solution()
s.method_name(test_var)
```
![image](https://user-images.githubusercontent.com/22736772/123045441-faa86200-d40b-11eb-9769-dd21acbd3fe5.png)

**Software versions(*Help* -> *About*)(Optional)**
- Product: IDEA 2020.2
- OS: Mac BigSur

**Comment by shuzijun** [comment]
The gif shows the function of using the template. I cannot give the specific python configuration, but you can use the template to create an ide based on the characteristics of python to know the running content. The configuration page provides some constants that can be used in the template. Refer to [velocity](https://velocity.apache.org/engine/2.3/user-guide.html) for the usage of the template.
