### ISSUE TITLE
查看题解、内容时文件也会放到源码目录

### ISSUE THREAD

**Issue by andymiaomiao** [shuzijun/leetcode-editor#350]
当查看题解，内容时；.md,.txt文件也会放到配置的src目录下，这个可以调整吗？
<img width="287" alt="截屏2021-07-08 下午3 04 22" src="https://user-images.githubusercontent.com/17276697/124877739-f0868600-dffd-11eb-82f8-0ff3983add59.png">

**Comment by shuzijun** [comment]
已经更换了目录还没发版，参考提交#343
