### ISSUE TITLE
题目描述中的相关标签是否可以隐藏或者提供折叠功能，看到标签就已经给了解题思路了

### ISSUE THREAD

**Issue by huzhongcaijia** [shuzijun/leetcode-editor#354]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by shuzijun** [comment]
参考#60

**Comment by huzhongcaijia** [comment]
> 参考#60
谢了   问题已解决  不过还是希望未来的版本能直接把这个配置写在  模板变量上
