### ISSUE TITLE
The next version only supports 2020.1+

### ISSUE THREAD

**Issue by shuzijun** [shuzijun/leetcode-editor#355]
It is expected that the next 7.x version will only support 2020.1+.
On IntelliJ Platform JCEF is supported in 2020.1+, which can bring a better display experience, such as [markdown-editor](https://github.com/shuzijun/markdown-editor).
It is difficult to adapt to the previous version, I am very sorry.

**Comment by adalein** [comment]
可以试试 [LeetCode Assistant](https://plugins.jetbrains.com/plugin/16770-leetcode-assistant/chinese-documentation)，免费使用

**Comment by Gagarinwjj** [comment]
Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 27, 2021
macOS 11.5
is not support yet!

**Comment by shuzijun** [comment]
> Android Studio Arctic Fox | 2020.3.1
> Build #AI-203.7717.56.2031.7583922, built on July 27, 2021
> macOS 11.5
> is not support yet!

@Gagarinwjj Refer https://github.com/shuzijun/markdown-editor/issues/4#issuecomment-889752419
