### ISSUE TITLE
java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSONObject

### ISSUE THREAD

**Issue by mistbor** [shuzijun/leetcode-editor#36]
Windows环境
idea intelliJ
刷新按钮时，报错

**Comment by shuzijun** [comment]
是通过什么样的形式安装的?
参考:https://github.com/shuzijun/leetcode-editor/issues/31#issuecomment-497622096

**Comment by mistbor** [comment]
下载安装包，导入进idea，另外，还有一个问题：做好题目之后，submit时一直报错，可是将做好的题粘贴到官网进行编译运行时不会报错且正常通过。

**Comment by shuzijun** [comment]
submit 提示的错误信息是什么

**Comment by shuzijun** [comment]
如果有问题可以添加描述再打开这个Issues
