### ISSUE TITLE
打开题目后提示要编辑

### ISSUE THREAD

**Issue by zhijian-pro** [shuzijun/leetcode-editor#361]
![image](https://user-images.githubusercontent.com/31313340/128355481-1d43f2a4-e078-4152-b5a2-157d9840f441.png)

这样是正常的吗 还有 func 那个报错

**Comment by shuzijun** [comment]
这是由于创建的文件不在当前project的路径内，可以参考文档https://www.jetbrains.com/help/idea/non-project-files-access-dialog.html
func的报错是不符合当前语言的格式，可以参考自定义模板文档创建符合go语法的模板
