### ISSUE TITLE
Android Studio Arctic Fox | 2020.3.1  题目标题显示乱码

### ISSUE THREAD

**Issue by tianhe-github** [shuzijun/leetcode-editor#362]
Android Studio Arctic Fox | 2020.3.1  题目标题显示乱码 如图👇👇👇👇

![image](https://user-images.githubusercontent.com/35953595/128662493-1cf28bca-5a46-4d4b-9b1d-3f633d352676.png)

**Comment by shuzijun** [comment]
用同版本测试没什么问题，贴一下Help->About 和  Help -> Edit Custom VM Options的信息，检查是否有有相关字符集的配置

**Comment by tianhe-github** [comment]
Android Studio Arctic Fox | 2020.3.1  安装后好像更新了字体，重新在Appearance指定设置个字体后恢复。
