### ISSUE TITLE
Cannot open the unlocked problems in IntelliJ

### ISSUE THREAD

**Issue by ohkimchi** [shuzijun/leetcode-editor#37]
I cannot open the unlocked problems in IntelliJ. Maybe there is some issues with premium account users. 

For example, the problem with problem 1099, see attached file.

![intelliJ](https://user-images.githubusercontent.com/20204988/61851717-50a3c080-aeea-11e9-8c62-49557557693a.PNG)
![leetcode screenshot](https://user-images.githubusercontent.com/20204988/61851718-50a3c080-aeea-11e9-8f12-76215ddddf8e.PNG)

**Comment by shuzijun** [comment]
install [V4.3](https://raw.githubusercontent.com/shuzijun/leetcode-editor/dev/doc/leetcode-editor-V4.3.zip)

**Comment by ohkimchi** [comment]
I installed the V4.3, problems with $ sign are not openable..

**Comment by shuzijun** [comment]
This version has only verified leetcode-cn.com, no premium users can't verify  leetcode.com

**Comment by ohkimchi** [comment]
那就等大佬出国际版的fix啦😈
