### ISSUE TITLE
如图，更新7.0以后，右键中没有LeetCode Editor Menu了

### ISSUE THREAD

**Issue by whileGreatHair** [shuzijun/leetcode-editor#372]
![image](https://user-images.githubusercontent.com/47522759/129691057-70b82072-b96c-4b85-b434-3327b2672564.png)

**Comment by whileGreatHair** [comment]
![image](https://user-images.githubusercontent.com/47522759/129704915-2ea10104-4515-4949-a082-995acff19030.png)

右键菜单设置好像没问题，但是就是不显示..不知道是bug还是我个人问题？

**Comment by shuzijun** [comment]
尝试从右侧面板重新打开一下题目，然后检查一下项目的文件.idea/leetcode/editor.xml，看是否有题目对应的路径配置

**Comment by whileGreatHair** [comment]
> 尝试从右侧面板重新打开一下题目，然后检查一下项目的文件.idea/leetcode/editor.xml，看是否有题目对应的路径配置

已经解决了，谢谢。重新加载任意题目就能解决，其他题目也会同时解决。
