### ISSUE TITLE
题号搜索问题

### ISSUE THREAD

**Issue by zhuliangyu** [shuzijun/leetcode-editor#379]
比如搜索题号700, 现在的逻辑是先显示1700, 然后第二次搜索才是700的题目. 我觉得可以反过来, 如果用户搜索700题号, 先给700的题目, 如果用户继续点击搜索再显示1700的题目. 不知道是否可以采纳, 谢谢. 
![image](https://user-images.githubusercontent.com/11518998/130305431-bcfacfe1-7aa4-43bd-ae98-92be622f7d5b.png)

**Comment by shuzijun** [comment]
第一次搜索是以当前定位的题目向下搜索，第一次出现1700是因为当前定位的题目大于700

**Comment by fatFire** [comment]
> 第一次搜索是以当前定位的题目向下搜索，第一次出现1700是因为当前定位的题目大于

但是这样并不好用，能修改成题主描述的形式吗。

**Comment by LJLintermittent** [comment]
是的，希望可以直接准确定位，包括向上搜索
