### ISSUE TITLE
能否将题目描述的“ // ”双斜杠式注释替换成 “ /* */ ”式的注释呢？

### ISSUE THREAD

**Issue by Ergofly** [shuzijun/leetcode-editor#382]
**如题**
将现在使用的

//我是
//注释

这种类型注释改为

/*
 *我是
 *注释
 */

或者照顾不同人的需求，提供一个选择不同注释方法 or ~~自定义注释方法~~ 的入口

**Comment by shuzijun** [comment]
7.x版本在配置页有这个配置

**Comment by Ergofly** [comment]
> 7.x版本在配置页有这个配置

好的，谢谢
