### ISSUE TITLE
登录问题 JCEF

### ISSUE THREAD

**Issue by normoon** [shuzijun/leetcode-editor#385]
**无法使用**
一直提示 
Not Support JCEF: Your environment does not support JCEF, cannot use LeetCode Editor.Check the Registry 'ide.browser.jcef.enabled'.

请问怎么解决？

**环境**
Android Studio 4.2.2
LeetCode Editor 7.3

**Comment by shuzijun** [comment]
参考https://github.com/shuzijun/markdown-editor/issues/4

**Comment by royliu1990** [comment]
俺也一样，邮箱注册的账号
