### ISSUE TITLE
提交题目与真正的题目不匹配

### ISSUE THREAD

**Issue by zhengjunren** [shuzijun/leetcode-editor#390]
更新了 7.4 版本之后，在 IDEA 中提交的题目与 LeetCode 中的题目不匹配。
例如，在 IDEA 中提交 1646 题，但在 LeetCode 网页的提交记录中查看到的是 1539 题

**Comment by zhengjunren** [comment]
![image](https://user-images.githubusercontent.com/49715922/130480365-1bf9565e-1d43-4360-a056-e4752db6ae43.png)
![image](https://user-images.githubusercontent.com/49715922/130480403-e83ca392-15c6-465b-b79e-85a8d04d3130.png)

**Comment by YoRHaAlter** [comment]
今天的第787题出现了同样的问题，不知道提交到哪个题目上去了
