### ISSUE TITLE
Submit/Run code出错

### ISSUE THREAD

**Issue by hzheng56** [shuzijun/leetcode-editor#391]
**Describe the bug**
先感谢下大佬的插件！
Submit和Runcode出错（不会出现在提交记录中）

**To Reproduce**
1. leetcode editor menu -> submit or run code

**Software versions(*Help* -> *About*)**
- Product: IDEA 2020.2
- Runtime version:[e.g 11.0.7+10-b944.20 amd64]
- VM: OpenJDK 11
- OS: MacOS BigSur

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:
  ```
info
运行失败:
Line 7: error: cannot find symbol [in __Driver__.java]
int ret = new Solution().numFriendRequests(param_1);
^
symbol:   method numFriendRequests(int[])
location: class Solution
测试用例:null
stdout:
null

info
运行失败:
'ages' must consist of values from 1 to 120 only
测试用例:[0,1,0]
stdout:
null
  ```

**Comment by shuzijun** [comment]
提供具体的代码和题目

**Comment by CheungQ** [comment]
和提交串题是一个问题，这边报错信息是力扣返回的方法入参类型不符应该

**Comment by shuzijun** [comment]
> 和提交串题是一个问题，这边报错信息是力扣返回的方法入参类型不符应该

嗯，找到问题了，是页面显示的编号和实际的编号不一致
