### ISSUE TITLE
Testcase功能有bug？

### ISSUE THREAD

**Issue by moye12325** [shuzijun/leetcode-editor#394]
**Describe the bug**
在Testcase中测试用例能通过，但是实际上应该是不能通过的
![image](https://user-images.githubusercontent.com/43414308/130542147-f829df8c-cfa1-4160-90dc-311628c3e1c0.png)

**To Reproduce**

**Software versions(*Help* -> *About*)**
- Product: IntelliJ IDEA 2021.1.2  leetcode editor 7.4
- 
- Runtime version:[e.g 11.0.7+10-b944.20 amd64]
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS:[e.g Windows 10]

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:
  ```
  
  ```

**Comment by shuzijun** [comment]
看测试用例的提交，是运行成功，并不是解答成功，提示的测试结果与期望结果是不一致的
