### ISSUE TITLE
8.0-Beta说明

### ISSUE THREAD

**Issue by shuzijun** [shuzijun/leetcode-editor#396]
leetcode网站上的api更改了很多，一次获取全部题目的接口不知道还能坚持多久。为了能和官网保持同步，以后的新版本更换为与官网一致的分页查询，后续版本为8.x。
-------
由于近期leetcode的api更改，无法获取全部题目与QuestionID，导致目前很多交互与筛选都无法正常使用。
短时间无法修改完成新的交互方式，发布Beta版本，先保证正常的获取题目与提交功能，Beta版本不会提交到插件库，如需使用先通过git下载安装

**Comment by kimutaku001** [comment]
beta版本怎么安装的？需要本地编译吗

**Comment by shuzijun** [comment]
> beta版本怎么安装的？需要本地编译吗

https://github.com/shuzijun/leetcode-editor/releases

**Comment by kimutaku001** [comment]
> > beta版本怎么安装的？需要本地编译吗
> 
> https://github.com/shuzijun/leetcode-editor/releases

thx

**Comment by LeafTyrion** [comment]
大佬，7.3 版本的用着就一切正常，功能和 7.4 也差不多

**Comment by shuzijun** [comment]
> 大佬，7.3 版本的用着就一切正常，功能和 7.4 也差不多

如果api能继续使用，7.3是可以用的

**Comment by BloodSid** [comment]
大佬，我6.9也用的一切正常
