### ISSUE TITLE
更新到7.4版本，run code 显示请求失败！

### ISSUE THREAD

**Issue by 1981795167** [shuzijun/leetcode-editor#399]
**Describe the bug**

**To Reproduce**

**Software versions(*Help* -> *About*)**
- Product: [e.g IDEA 2020.2]
- Runtime version:[e.g 11.0.7+10-b944.20 amd64]
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS:[e.g Windows 10]

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:
  ```
  
  ```

**Comment by CaiNiaoCYY** [comment]
+1

**Comment by 1981795167** [comment]
用了beta版本好了
