### ISSUE TITLE
leetcode面板没有登录或者刷新按钮

### ISSUE THREAD

**Issue by DoubleW2w** [shuzijun/leetcode-editor#409]
**BUG描述**

我使用的工具是  IntelliJ IDEA Ultimate 2020.3.1 
我从该网站[https://plugins.jetbrains.com/plugin/12132-leetcode-editor/versions](https://plugins.jetbrains.com/plugin/12132-leetcode-editor/versions)下载7.3版本的leetcode-editor插件，并通过 `Install Plugs from Disk...` 的方式导入插件，并在插件设置中填好必要信息，回到面板查看并没有登录或者刷新按钮

![image](https://user-images.githubusercontent.com/73921620/133720381-64027253-5ef7-4159-a713-b7d8165c0587.png)

**Software versions(*Help* -> *About*)**
- Product:  IntelliJ IDEA 2020.3.1 (Ultimate Edition)
- Runtime version: 11.0.9.1+11-b1145.63 amd64
- VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- OS: Windows 10

**Comment by shuzijun** [comment]
右上角**三个点**,选择**Show Toolbar**
