### ISSUE TITLE
开启多个project时登录状态异常

### ISSUE THREAD

**Issue by ppassion** [shuzijun/leetcode-editor#422]
**流程描述**

1. 登录后正常使用插件，假设是projectLeet
2. open另一个project，把projectLeet关掉
3. 再次open projectLeet，插件内显示需要登录，但是点击登录会提示‘已经登录’

目前的解决方法是，点击sign out之后再重新sign in

**Comment by shuzijun** [comment]
提示完已经登录会自动刷新列表的，或者在新project直接刷新即可，不需要退出后再登录
