### ISSUE TITLE
Can't Log in in Windows 10 and macOS

### ISSUE THREAD

**Issue by GuodongZhu** [shuzijun/leetcode-editor#423]
**Describe the bug**
I can successfully pull the questions and solutions, but can't log in and submit my solution. 

- Product: IDEA 2021.2.3
- Runtime version: Java 8
- OS: Windows 10 and macOS
- plugin: I'm using the latest leetcode-editor plugin from Marketplace (7.3)

Did other user see the same issue as me?

**Comment by shuzijun** [comment]
Is there a login error?
Suggest to try the new version [v8.0-Beta](https://github.com/shuzijun/leetcode-editor/releases/tag/v8.0-Beta)

**Comment by GuodongZhu** [comment]
> Is there a login error? Suggest to try the new version [v8.0-Beta](https://github.com/shuzijun/leetcode-editor/releases/tag/v8.0-Beta)

Thanks for your prompt reply! It's only showing: "info please log in first".

I also tried to install v8.0-Beta, however my ide complaints that "fail to load plugin descriptor from file"

**Comment by shuzijun** [comment]
Have you tried to click this button?
![登录](https://user-images.githubusercontent.com/27667179/140012432-b1fd5fad-7852-4645-be1c-372aded3e9dc.png)

**Comment by GuodongZhu** [comment]
Yes. After I click the button, it asks me to provide the cookie info. From your documentation my understanding is that cookie option is only valid for leetcode-cn.com but I'm using leetcode.com.

**Comment by shuzijun** [comment]
Both can be used, you can try to open JCEF and use the pop-up browser to log in.
![JCEF](https://user-images.githubusercontent.com/27667179/140243763-1350e2a2-7850-48b3-953f-565044cd1e3c.png)

**Comment by GuodongZhu** [comment]
This JCEF works for me. Thanks a lot for your help!
