### ISSUE TITLE
Not Support JCEF

### ISSUE THREAD

**Issue by BugCui** [shuzijun/leetcode-editor#424]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/48312085/140041170-2c2371ae-2859-41ad-a79b-c84087dbf930.png">

Mac OS 
Zulu JDK 11

**Comment by starriddle** [comment]
碰到过同样地问题，用的 ubuntu JDK，后来发现是这些JDK不支持，使用IDEA内置的jbr就能支持了，看它目前最新的版本号 ”JBR-11.0.13.7-1751.19-jcef“ 就明白了

**Comment by BugCui** [comment]
> 

感谢，可惜我用的M1芯片，idea自带JDK跑起来卡的不行不行的~  😭

**Comment by shuzijun** [comment]
> 感谢，可惜我用的M1芯片，idea自带JDK跑起来卡的不行不行的~ 😭

可以试试在[JetBrainsRuntime/releases](https://github.com/JetBrains/JetBrainsRuntime/releases)上下载一个arm版本带JCEF的试试，切换参考["Selecting the JDK version the IDE will run under"](https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under)

**Comment by BugCui** [comment]
谢谢！

> > 谢谢，可惜我用的M1芯片，自带JDK跑起来卡的不行的~ 😭
> 
> 可以在[JetBrainsRuntime/releases](https://github.com/JetBrains/JetBrainsRuntime/releases)上下载一个arm版本带JCEF的学习方法，切换参考[“Selecting the JDK version the IDE will run under”](https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under)

谢谢
