### ISSUE TITLE
some features request + some bugs ?

### ISSUE THREAD

**Issue by K85** [shuzijun/leetcode-editor#429]
# Feature Request
i use ideavim to code and i bind LeetCodeEditor.MenuAction and LeetCodeEditor.ToolBarAction, so my workflow is:
use mouse to choose a problem from the problem set, and then use my keyboard to code and submit (I bind some shortcuts to LeetCodeEditor.SubmitAction). And i should open the EventLog to see the detail formatted response (since in the balloon window, the text is not formatted and I muse use mouse to click "More" to see all the text). After that, I should use my keyboard to close the EventLog. And then use mouse to choose another new problem.

### **feature: add some shortkeys for select problem**
in the problem set, it's ok to use the search function which the IDEA provided to search specific problem, but I don't know why it's not support to use ENTER key to open the problem.

### **feature: auto popup the EventLog to show the compile/testcases/response details**
the balloon window is too small and can't afford all the text (and it's not supprot formatted).
if I want to get the details, I must open my EventLog by using IDEA.GotoAction

### **support select a new problem by keyboard**
i must open the problem set and choose problem by my mouse. what i expected is that I can use shortcuts to open a popup-problem-set in the middle of my IDE and use my keyboard to select an interesting problem (of course use ENTER instead of mouse to open the problem).
For example: I use my keyboard to perform LeetCodeEditor.findProblem, then show the problem-set-popup in the middle of IDE, and I can search and select a new problem.

## **confirm again before the plugin DO clearcache action !**
sometimes it's possible to perform clearcache by mistake.

# Maybe Bugs

### **bug1 ?**
After I restart my IDE, the LeetCodeEditor won't auto re-login. (though the plugin will warn me), why not re-login automatically ?

### **bug2 ?**
Chinese can't display correctly in *.lcv tabs. (it's ok to display chinese in 'open question', 'open content', 'open solution', )

### **bug 3?**
the LeetCodeEditot can't identify the problem to submit correctly.
When I open some problems in the problem set, the plugin only remember the last problem I opened as the target of submit action. (I use the SubmitAction in action group leetcode.NavigatorActionsMenu !!!)
But, the plugin can identify correctly if i only use my mouse to click the 'Submit' button in the toolbar.

**Comment by shuzijun** [comment]
The above functions will be added in the future.

> After I restart my IDE, the LeetCodeEditor won't auto re-login. (though the plugin will warn me), why not re-login automatically ?

Logging in is a very heavy operation，The China site also involves only single sign-on， It is expected that users can manually and know that they are logged in. Of course, you can add an optional configuration for automatic login in the future.

> Chinese can't display correctly in *.lcv tabs. (it's ok to display chinese in 'open question', 'open content', 'open solution', )

Add or modify -Dfile.encoding=utf-8 in Help->Edit Custom VM options

> the LeetCodeEditot can't identify the problem to submit correctly.
When I open some problems in the problem set, the plugin only remember the last problem I opened as the target of submit action. (I use the SubmitAction in action group leetcode.NavigatorActionsMenu !!!)
But, the plugin can identify correctly if i only use my mouse to click the 'Submit' button in the toolbar.

Try to bind shortcut keys under the leetcode.editor.group group. The NavigatorActionsMenu group is the  question in the navigation that is read, and the editor.group is the question  in the read editor.

**Comment by K85** [comment]
> The above functions will be added in the future.
> 
> > After I restart my IDE, the LeetCodeEditor won't auto re-login. (though the plugin will warn me), why not re-login automatically ?
> 
> Logging in is a very heavy operation，The China site also involves only single sign-on， It is expected that users can manually and know that they are logged in. Of course, you can add an optional configuration for automatic login in the future.
> 
> > Chinese can't display correctly in *.lcv tabs. (it's ok to display chinese in 'open question', 'open content', 'open solution', )
> 
> Add or modify -Dfile.encoding=utf-8 in Help->Edit Custom VM options
> 
> > the LeetCodeEditot can't identify the problem to submit correctly.
> > When I open some problems in the problem set, the plugin only remember the last problem I opened as the target of submit action. (I use the SubmitAction in action group leetcode.NavigatorActionsMenu !!!)
> > But, the plugin can identify correctly if i only use my mouse to click the 'Submit' button in the toolbar.
> 
> Try to bind shortcut keys under the leetcode.editor.group group. The NavigatorActionsMenu group is the question in the navigation that is read, and the editor.group is the question in the read editor.

i always use the "Submit" Action from action group leetcode.NavigatorActionsMenu, it's sad that i should bind another key for submit action.
these are my configs:
map <leader>lm <Action>(leetcode.NavigatorActionsMenu)
map <leader>lt <Action>(leetcode.NavigatorActionsToolbar)

**Comment by K85** [comment]
> 



> > The above functions will be added in the future.
> > > After I restart my IDE, the LeetCodeEditor won't auto re-login. (though the plugin will warn me), why not re-login automatically ?
> > 
> > 
> > Logging in is a very heavy operation，The China site also involves only single sign-on， It is expected that users can manually and know that they are logged in. Of course, you can add an optional configuration for automatic login in the future.
> > > Chinese can't display correctly in *.lcv tabs. (it's ok to display chinese in 'open question', 'open content', 'open solution', )
> > 
> > 
> > Add or modify -Dfile.encoding=utf-8 in Help->Edit Custom VM options
> > > the LeetCodeEditot can't identify the problem to submit correctly.
> > > When I open some problems in the problem set, the plugin only remember the last problem I opened as the target of submit action. (I use the SubmitAction in action group leetcode.NavigatorActionsMenu !!!)
> > > But, the plugin can identify correctly if i only use my mouse to click the 'Submit' button in the toolbar.
> > 
> > 
> > Try to bind shortcut keys under the leetcode.editor.group group. The NavigatorActionsMenu group is the question in the navigation that is read, and the editor.group is the question in the read editor.
> 
> i always use the "Submit" Action from action group leetcode.NavigatorActionsMenu, it's sad that i should bind another key for submit action. these are my configs: map lm (leetcode.NavigatorActionsMenu) map lt (leetcode.NavigatorActionsToolbar)

ok, i add the shortcut for action group "leetcode.editor.group". 
anything goes well. (the difference is that leetcode.editor.group didn't have the "Favorite")

**Comment by shuzijun** [comment]
fix [v8.2](https://github.com/shuzijun/leetcode-editor/releases/tag/v8.2)
