### ISSUE TITLE
题解公式解析错误 

### ISSUE THREAD

**Issue by imxf-git** [shuzijun/leetcode-editor#436]
题目： [5]最长回文子串
官方题解
公式解析异常：分段函数大括号解析异常，如果内容是true，题解中会被删掉

![b15ce3ab88476878e3d8346bd577d6e](https://user-images.githubusercontent.com/49446063/145331309-6e9c9a21-ccb9-4094-b5c6-305ce9658920.png)

**修改前：**
![c0d7daefbfdad843f0064e6c10ea8a1](https://user-images.githubusercontent.com/49446063/145331547-05749024-2262-4036-bef1-aa3322f4f5c5.png)

**修改后：**
![917867ae16226803bec17b49b31b485](https://user-images.githubusercontent.com/49446063/145331557-f3f30754-8fc1-4f60-b186-a85e7648d322.png)

**Comment by shuzijun** [comment]
#419 已经修复，安装一下[v8.0-Beta.2](https://github.com/shuzijun/leetcode-editor/releases/tag/v8.0-Beta.2)

**Comment by imxf-git** [comment]
已经收到您的邮件.

**Comment by imxf-git** [comment]
> #419 已经修复，安装一下[v8.0-Beta.2](https://github.com/shuzijun/leetcode-editor/releases/tag/v8.0-Beta.2)

能解析了，但是cases重复了

![image](https://user-images.githubusercontent.com/49446063/145337856-ffed46af-dc64-4100-a83b-dfe08be18754.png)
![image](https://user-images.githubusercontent.com/49446063/145337999-8e376690-a29f-427f-8e7a-75f42996d558.png)

**Comment by imxf-git** [comment]
已经收到您的邮件.
