### ISSUE TITLE
LeetCode Editor无法加载题目

### ISSUE THREAD

**Issue by leetcodeFei** [shuzijun/leetcode-editor#441]
![image](https://user-images.githubusercontent.com/96102655/145940692-95676973-1e24-4c18-95dc-ac4c7efeb308.png)
![image](https://user-images.githubusercontent.com/96102655/145940768-cf8ce2ba-e434-486e-9b71-69ee014d2076.png)

nen能正常登录，但点击加载，无法加载到题目

**Comment by shuzijun** [comment]
右下角，检查有没有红色叹号，里面左右翻翻，找到对应的报错

**Comment by leetcodeFei** [comment]
![image](https://user-images.githubusercontent.com/96102655/145942909-d301e5bf-664f-4d3d-b794-3fa03ee3050c.png)
是有个报错，8.0版本

**Comment by shuzijun** [comment]
安装插件的时候选择整个zip包，不要解压

**Comment by leetcodeFei** [comment]
哦，可以了，感谢~
