### ISSUE TITLE
请问下插件是否支持调试运行

### ISSUE THREAD

**Issue by maxshine** [shuzijun/leetcode-editor#443]
**Desc**
Start a discussion or ask for help

**Software versions(*Help* -> *About*)(Optional)**
- Product: [2021.3]
- Runtime version:[11.0.13+7-b1751.19 x86_64 amd64]
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS:[macOS 12.0.1]

**Question(Optional)**
- URL:[leetcode.com]
- Code Type:[JAVA]
- code:
  ```
  请问下插件的“运行代码”是否支持调试，类似leetcode界面上的调试功能？谢谢
  ```

**Comment by shuzijun** [comment]
不支持。利用IDE调试参考[自定义代码](https://github.com/shuzijun/leetcode-editor/blob/master/doc/CustomCode_ZH.md)

**Comment by maxshine** [comment]
> 不支持。利用IDE调试参考[自定义代码](https://github.com/shuzijun/leetcode-editor/blob/master/doc/CustomCode_ZH.md)

请问使用custom template是需要购买pro还是通过配置界面点击弹出的二维码支付？

**Comment by shuzijun** [comment]
> 请问使用custom template是需要购买pro还是通过配置界面点击弹出的二维码支付？

不需要，两个版本都可以，弹框可以直接关了

**Comment by maxshine** [comment]
>  
> 
> > 请问使用custom template是需要购买pro还是通过配置界面点击弹出的二维码支付？
> 
> 
> 
> 不需要，两个版本都可以，弹框可以直接关了

谢谢
