### ISSUE TITLE
8.0的风格，找不到tag了，不太习惯

### ISSUE THREAD

**Issue by huangge1199** [shuzijun/leetcode-editor#450]
更喜欢7.3版本的树结构，可不可以在树结构的基础上做列表

**Comment by shuzijun** [comment]
目前网站已更换为分页获取方式，原来的树形结构需要获取到所有题目，不能确定获取所有题目的api什么时候会下线。
如果喜欢原来的树形结构，在api可用的状态下可以一直使用。

筛选tag的功能，可以选择工具栏上的放大镜图标，里面可以筛选tag

**Comment by JerrickLewis7190** [comment]
It seems that the api is back online. I used the 7.3 version  and all the problems show up. Is it possible to add this back in the next release?
