### ISSUE TITLE
更新到8.0后，感觉有些不习惯

### ISSUE THREAD

**Issue by pengjizhi** [shuzijun/leetcode-editor#451]
主要有两个地方
1.锁定功能去哪里了呢？因为用的模板每次把题转化为了英文标题，且没有题的编号，有时候想去看看以前做的题是哪个题，需要锁定，但是找不到
2.排序功能，感觉不是很直观，里面有个属性是frequency，这个貌似全部都是0

感谢做出的贡献！上班摸鱼神器！

**Comment by shuzijun** [comment]
1.原锁定功能的前提是有全部题目，目前没有全部题目了，后续将配合搜索添加新锁定功能。
2.排序功能需要注意图标![](https://raw.githubusercontent.com/shuzijun/leetcode-editor/master/src/main/resources/icons/sortAsc.svg),标识正在按照这个属性正序或者倒序排列，排列逻辑与网页一致。frequency属性为会员才可以看到，非会员全是0.

**Comment by actforjason** [comment]
建议`frequency`可以关闭，很多人不一定有vip
