### ISSUE TITLE
8.0版本的Explore哪里去了？

### ISSUE THREAD

**Issue by taichushouwang** [shuzijun/leetcode-editor#452]
以前刷题的时候，都是看Explore下面的题目。现在8.0之后找不到Explore了，请问哪里去了？
另外在LeetCode网站上怎么能找到Explore这个栏目？

**Comment by shuzijun** [comment]
网页地址:https://leetcode.com/explore/,中文应该是对应:https://leetcode-cn.com/leetbook/
这个标签下除了题目，主要内容是一些解题相关的思路，里面包含很多图片与视频，无法完美展示，就把这个功能下线了，里面的题目都是可以在题库中找到的。

**Comment by taichushouwang** [comment]
@shuzijun 但是里面有“面试，怎能错过这些经典”这种分类，对于现在找工作的，还是挺有用的ORZ

**Comment by taichushouwang** [comment]
@shuzijun “腾讯”和“算法面试题汇总”我找到了，但是“字节跳动”没有找到，请问如何可以看得到对应的链接呢？

> 网页地址:https://leetcode.com/explore/, 中文应该是对应:https://leetcode-cn.com/leetbook/ 这个标签下除了题目，主要内容是一些解题相关的思路，里面包含很多图片与视频，无法完美展示，就把这个功能下线了，里面的题目都是可以在题库中找到的。

**Comment by shuzijun** [comment]
原来插件是很早的api了，现在在界面上找不到了。。。。
你可以试试筛选里的lists
