### ISSUE TITLE
questions list does not refresh after clear search

### ISSUE THREAD

**Issue by ycchen24** [shuzijun/leetcode-editor#457]
**Describe the bug**
after removing text from find questions input box or click clear find, questions list does not populate all list

**To Reproduce**
1. Click on 'Find question'
1. type in searched questions number like `123`
1. questions `123. Best Time to Buy and Sell Stock III` populate under question list window
1. removed the search from `Find questions` input box
1. questions list does not refresh
1. click on `Refresh question` or logout/logout
1. question list does not change
1. reopen the pycharm IDE and login again.
1. confirm all question populate under list
[https://share.getcloudapp.com/6quEPqez](https://share.getcloudapp.com/6quEPqez
)
**Software versions(*Help* -> *About*)**
- Product:PyCharm 2021.3.1 (Professional Edition)
- Runtime version:[e.g v8.0]
- OS:macOs Big Sur 11.6.1

**Comment by shuzijun** [comment]
After deleting or emptying, need to press Enter.

**Comment by ycchen24** [comment]
thank you for clarify
