### ISSUE TITLE
Github登录的怎么配置用户名密码

### ISSUE THREAD

**Issue by ltx0720** [shuzijun/leetcode-editor#458]
**Desc**
Start a discussion or ask for help

**Software versions(*Help* -> *About*)(Optional)**
- Product: [e.g IDEA 2020.2]
- Runtime version:[e.g 11.0.7+10-b944.20 amd64]
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS:[e.g Windows 10]

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:
  ```
  
  ```

**Comment by shuzijun** [comment]
开启JCEF，密码不用填写，在弹出的网页里登陆
