### ISSUE TITLE
How can i increase the preview windows font size

### ISSUE THREAD

**Issue by TalonX1** [shuzijun/leetcode-editor#461]
![image](https://user-images.githubusercontent.com/42306998/153694021-ba69e2f3-67f2-49e7-96b8-1e20dbf83345.png)

**Comment by shuzijun** [comment]
reference [settings-editor-font](https://www.jetbrains.com/help/idea/settings-editor-font.html)

**Comment by TalonX1** [comment]
Oh.thank you,it's available.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月12日(星期六) 下午2:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [shuzijun/leetcode-editor] How can i increase the preview windows font size (Issue #461)





 
reference settings-editor-font
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
