### ISSUE TITLE
editor和preview窗口位置

### ISSUE THREAD

**Issue by stepbackforthree** [shuzijun/leetcode-editor#463]
作者你好，想请教一下是否有交换editor和preview窗口位置（左右互换）的功能呢？谢谢！

**Comment by HernandoR** [comment]
相同,希望可以设置为左preview,右edit(与web相同)

**Comment by shuzijun** [comment]
fix [v8.2](https://github.com/shuzijun/leetcode-editor/releases/tag/v8.2)
