### ISSUE TITLE
solution 目录下文件是否能用中文命名

### ISSUE THREAD

**Issue by actforjason** [shuzijun/leetcode-editor#468]
拼音可辨别性不好。
![image](https://user-images.githubusercontent.com/57058325/158001656-9b997dd6-284e-4aa4-adc8-bc60c77c58d8.png)

**Comment by shuzijun** [comment]
这个名称是取的leecode定义的名称，例如*liang-shu-zhi-he-by-leetcode-solution*，取自链接https://leetcode-cn.com/problems/two-sum/solution/liang-shu-zhi-he-by-leetcode-solution/

**Comment by actforjason** [comment]
#474
