### ISSUE TITLE
8.0版本的编辑器窗口，能否和原生的编辑器保持同样的体验？

### ISSUE THREAD

**Issue by sirnple** [shuzijun/leetcode-editor#470]
当前版本 (8.0) 的编辑器，存在几个问题：

1. 不能调试
2. 缺少Hint，比如如果没有import某个类，使用该类的时候没有报红
3. 没有Introduce variable的intention

**Comment by shuzijun** [comment]
参考 [自定义代码生成](https://github.com/shuzijun/leetcode-editor/blob/master/doc/CustomCode_ZH.md)
