### ISSUE TITLE
不认java文件

### ISSUE THREAD

**Issue by huahuayu** [shuzijun/leetcode-editor#48]
你好，这个插件非常好，点赞！初次使用遇到一个问题，点开题目后，java文件上有一个橙色的小j，说明idea不认java文件。
![image](https://user-images.githubusercontent.com/1725060/63321119-61f9b480-c352-11e9-858a-d4b3ebb3a790.png)

忽略这个小j，直接编辑，被提示不属于项目，要我确认编辑，然后编辑的时候没有补全功能。这个体验不太好。
![image](https://user-images.githubusercontent.com/1725060/63321141-7178fd80-c352-11e9-9233-2368ab8628e0.png)

**Comment by shuzijun** [comment]
由于打开的文件是一个独立的文本，不属于当前项目空间，所以才会出现此警告。但是我尝试了一下，代码提示还是正常的。 
![tip](https://user-images.githubusercontent.com/27667179/63327680-421dbd00-c361-11e9-82bc-a00f59acd730.png)  

同时，为了更好的编辑体验与本地调试，在新的5.0版本中新增了自定义代码生成的配置，预计这两周更新。参考链接[自定义生成](https://github.com/shuzijun/leetcode-editor/blob/dev/CustomCode_ZH.md)，如果对新版有更好的建议，欢迎提出。

**Comment by lxxself** [comment]
@shuzijun 感谢你的插件。所以必须打开leetcode项目才能运行咯，技术上没办法实现任意项目中打开运行么？

**Comment by shuzijun** [comment]
@lxxself 由于运行必须依赖JDK才可以，目前没有想到好的方案能够解决；除此之外，还要兼容其他语言的，通用方案就是依赖IDE的项目导入运行所需的环境。

**Comment by youpen** [comment]
@shuzijun , 将缓存目录设置在自己的的工程目录下能否解决这个问题？
同时这样也可以把自己的做题记录上传到github上保存

**Comment by lxxself** [comment]
有个想法是，插件配置好jdk环境，然后插件读取代码然后运行输出显示，不依赖IDEA的运行环境和控制台，IDEA只做代码编写用。这样插件不知道好不好实现。。。。

**Comment by shuzijun** [comment]
@youpen  目前推荐的方案就是这样的，可以参考[自定义代码生成](https://github.com/shuzijun/leetcode-editor/blob/master/CustomCode_ZH.md)

**Comment by shuzijun** [comment]
@lxxself 读取JDK环境配置运行代码没什么问题，但是脱离IDEA的项目就无法调试代码了，而且其他语言都要去实现对应的运行方案。这个方案的实现成本和带来的收益不如依赖项目，如youpen所说，项目可以和git关联，保留本地的解决方案。

**Comment by shuzijun** [comment]
@lxxself 读取JDK环境配置运行代码没什么问题，但是脱离IDEA的项目就无法调试代码了，而且其他语言都要去实现对应的运行方案。这个方案的实现成本和带来的收益不如依赖项目，如youpen所说，项目可以和git关联，保留本地的解决方案。
