### ISSUE TITLE
修改配置失败，保存后再次打开配置还是还是变成了默认配置

### ISSUE THREAD

**Issue by teavamc** [shuzijun/leetcode-editor#480]
IDEA 版本是 2021.2.1 UE 版本
请问是我本地环境问题还是 bug
再请问大哥，我每次的保存有日志吗？ 哪里可以查看？

**Comment by shuzijun** [comment]
参考#442

**Comment by teavamc** [comment]
@shuzijun 确认先点的 apply 再点的 ok

**Comment by teavamc** [comment]
我试下 #442 的流程

**Comment by BiuBiuH** [comment]
2022.1.3 UE版本   插件版本8.3   保存代码模板失效 总是回退到默认模板  有地方可以让我自己去文件设置吗？
