### ISSUE TITLE
搜索题号 会跳出来一堆其他的题号 且 题号的Frequency值不准? 

### ISSUE THREAD

**Issue by pangjac** [shuzijun/leetcode-editor#482]
**Desc**
最近更新了plugin的版本 到8.0, 想请问两件事:
a. 搜索速度非常慢, 比如我现在搜索题号, 以前是非常快的跳出这个题目, 现在要等上近一秒 . 
b. 我想问一下 关联出来的题目都是什么, 搜索1066, 会关联一批题目, 举例如下: 这些题目也不是1066的相关题目. 是因为这些降低了search的速度吗? 
![image](https://user-images.githubusercontent.com/13987136/161145233-0b53bef2-21be-43a2-9f4d-efa45b7618a4.png)

**Software versions(*Help* -> *About*)(Optional)**
- Product: [e.g IDEA 2021.3] Community
- Runtime version:[e.g 11.0.7+10-b944.20 amd64]
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS:[e.g MacOS Catalina 10.15.7 (19H2]

谢谢!

**Comment by shuzijun** [comment]
根本原因是获取题目换成了分页请求。原来网站的题目是可以通过一个请求获取到所有题目，但是随着题目数量增多，网址更改成了分页方式，插件8.0同步改成了这种方式，所以对于问题1，原来是在内存内匹配，现在是通过网络请求查询，会慢很多，搜索结果也是与网址上同步的，具体查询逻辑与网址保持一致。

**Comment by pangjac** [comment]
> 根本原因是获取题目换成了分页请求。原来网站的题目是可以通过一个请求获取到所有题目，但是随着题目数量增多，网址更改成了分页方式，插件8.0同步改成了这种方式，所以对于问题1，原来是在内存内匹配，现在是通过网络请求查询，会慢很多，搜索结果也是与网址上同步的，具体查询逻辑与网址保持一致。

感谢作者的回复! 那么其余的相关题目有什么逻辑关联吗? 还是除了`day`以外其他的题号是随机给出的?
感谢作者的开发, 帮了我们很多!

**Comment by shuzijun** [comment]
能搜出来的题目关联关系没发现规律，不知道力扣是怎么匹配到其他题目的。
