### ISSUE TITLE
idea下通过此插件创建新的代码文件时，能否/是否可以自动创建新的package并将java文件置于其中？

### ISSUE THREAD

**Issue by UnbearableFate** [shuzijun/leetcode-editor#487]
Leetcode默认都是Solution类，如果希望保存自己写的解答而不是临时创建文件的话，放在同一个package（现在默认只会创建package ：leetcode.editor.en）里会发生冲突，
现在能否自动创建新的子package并将java文件置于其中？
如果现存版本中没有实现这个特性，能否可以在将来版本中实现呢？

**Comment by shuzijun** [comment]
参考[自定义代码](https://github.com/shuzijun/leetcode-editor/blob/master/doc/CustomCode_ZH.md)
