### ISSUE TITLE
能不能提供题解的tab，方便我直接在idea里面看答案

### ISSUE THREAD

**Issue by aisi0306** [shuzijun/leetcode-editor#49]

**Comment by shuzijun** [comment]
目前没有这样的计划，现在可以通过open in web菜单，跳转到官网查看

**Comment by raymondsryang** [comment]
希望可以直接在ide看题解 +1

**Comment by wjfwxf** [comment]
希望可以直接在ide看题解 +1

**Comment by 993198101** [comment]
++++1

**Comment by shuzijun** [comment]
功能已添加，可以尝试安装[v6.4-beta](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.4-beta)
