### ISSUE TITLE
PHPstorm的使用

### ISSUE THREAD

**Issue by bourne-3** [shuzijun/leetcode-editor#490]
**Desc**
使用phpstorm2022.3 ，在插件市场安装成功。
但是打开进行编辑时，没有关键字提示，都是以文本显示，问题如何解决？
![image](https://user-images.githubusercontent.com/59307069/167254789-dd59f646-d1dc-4029-92cb-02e3826e3bab.png)

在编辑文本会提示如下信息
![image](https://user-images.githubusercontent.com/59307069/167254952-cdd236ec-88fd-4c1c-8393-26c690bd6914.png)

**Software versions(*Help* -> *About*)(Optional)**
- Product: PHPStorm
- Runtime version: 11.0.13+7-b1751.25 amd64
- VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- OS:[e.g Windows 10]

**Comment by shuzijun** [comment]
编辑文本提示信息的原因https://www.jetbrains.com/help/idea/non-project-files-access-dialog.html
插件创建并打开的文件不属于当前这个项目，建议试下根据配置的文件目录(f:\php_dir\leetcode.....),单独打开一个项目，并配置一下环境变量。

**Comment by bourne-3** [comment]
环境变量具体是配置哪些。我open文件目录(f:\php_dir\leetcode.....),。显示如下
![image](https://user-images.githubusercontent.com/59307069/167258179-092f0eee-8c48-4591-b4fd-dc4dce7d341b.png)

**Comment by shuzijun** [comment]
看了一下php的文件，好像需要加上<?php,可以通过模板增加，例如下面的配置，把现有文件删除后重新打开题目
![image](https://user-images.githubusercontent.com/27667179/167259018-c2fbeaca-9f98-411d-a0e5-ea262c738a01.png)
![image](https://user-images.githubusercontent.com/27667179/167259044-30938b60-50cb-462c-b8d7-6f9d85f82853.png)

**Comment by bourne-3** [comment]
你好，是这样的，已解决。谢谢
