### ISSUE TITLE
登陆问题

### ISSUE THREAD

**Issue by WYZ870513** [shuzijun/leetcode-editor#493]
登陆时cookie复制过去按着方法来，一直登陆不上去

**Comment by gechengze** [comment]
+1 我看今天leetcode-cn.com强制跳转到leetcode.cn了，不知道有没有关系

**Comment by shuzijun** [comment]
参考 #491

**Comment by WYZ870513** [comment]
在设置中勾选JCEF用弹框网页版可以登录

**Comment by WYZ870513** [comment]
> 参考 #491 等下安装新版

好的，辛苦了

**Comment by shuzijun** [comment]
[V8.1](https://github.com/shuzijun/leetcode-editor/releases/tag/v8.1)
