### ISSUE TITLE
OpenSolution打开空白，白板，是我一个人电脑问题还是都有这个问题？

### ISSUE THREAD

**Issue by code-internet** [shuzijun/leetcode-editor#503]
![image](https://user-images.githubusercontent.com/90761309/168044007-b3302388-44a9-4036-a6c0-956130e2ff13.png)

**Comment by shuzijun** [comment]
用的插件版本和idea版本是多少？

**Comment by actforjason** [comment]
题目预览duo多次换选项卡后也会这样变成空白
![image](https://user-images.githubusercontent.com/57058325/168049066-fb598194-d094-4f38-acf5-02dba406a460.png)

**Comment by shuzijun** [comment]
> 题目预览在多次换选项卡后也会这样变成空白 插件8.1，PyCharm 2022.1 (Professional Edition)

2022的JCEF的api有更新，在未完全加载的情况下切换页面，可能会出现空白。先试用一下[2022.2.0](https://github.com/shuzijun/leetcode-editor/releases/tag/v2022.2.0-pub)，优化了一下展示，后续同步新版本

**Comment by code-internet** [comment]
idea 版本 2022.1 
插件版本 8.1
@shuzijun

**Comment by code-internet** [comment]
解决了，刚看了下，好了，谢谢
