### ISSUE TITLE
IDEA 2019.3+ 登录leetcode中文网站失败，leetcode-cn.com已经变更leetcode.cn

### ISSUE THREAD

**Issue by yefuyi** [shuzijun/leetcode-editor#504]
**Describe the bug**

leetcode-cn.com已经变更leetcode.cn，19版本无法登录

**Comment by caoshen** [comment]
> **Describe the bug**
> 
> leetcode-cn.com已经变更leetcode.cn，19版本无法登录

更新插件到8.1版本，然后Settings-tools-leetcode plugin 切换 url 到 leetcode.cn

**Comment by shuzijun** [comment]
#491 有临时解决方案
#497 有相关版本发布说明

**Comment by zekersoft** [comment]
> 

2019.3 更改xml后，重启idea，登录成功
