### ISSUE TITLE
题的类名和题目(md)文件名可否支持自定义

### ISSUE THREAD

**Issue by yonxao** [shuzijun/leetcode-editor#505]
<img width="1423" alt="Snipaste_2022-05-22_17-51-09" src="https://user-images.githubusercontent.com/24690883/169689647-f2ae6d93-4965-475c-af0d-3ffee0e2277b.png">

优化建议（如图）：

1. 因为修改了文件的名称  [1]两数之和.java 为 [0001]两数之和.java,
导致右侧题目内容（md内容）不展现了，其实也同时将 md 文件名
也修改为对应类名的了。建议题目内容展现逻辑可以改为只要文件
名称对应就展现

2. 因为所有题都放在了同一个包内，每个题都有一个类叫 Solution，
而同一个包内不能有两个相同的类名，每次做新题的时候，都需要
将之前的 类名增加一个编号，即 Solution0026。但是之后再做 26 题
的时候，提交的时候又得将 0026 删除才能提交成功，希望这里也优化一下。

**Comment by shuzijun** [comment]
参考[自定义代码模板](https://github.com/shuzijun/leetcode-editor/blob/master/doc/CustomCode_ZH.md)

**Comment by yonxao** [comment]
您好，您的邮件永潇已经收到。如有需要，待他查看后会尽早回复您。--------------------------------------------本邮件为自动回复邮件，不用回复，谢谢。
