### ISSUE TITLE
idea2019.3.5无法升级插件

### ISSUE THREAD

**Issue by CaoDonald** [shuzijun/leetcode-editor#507]
idea2019.3.5目前只能使用6.9的插件,无法升级,手动下包安装显示与idea版本不匹配

**Comment by shuzijun** [comment]
https://github.com/shuzijun/leetcode-editor/issues/491 有临时解决方案
https://github.com/shuzijun/leetcode-editor/issues/497 有相关版本发布说明

低版本IDEA尝试使用6.11
