### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Winter-is-comingXK** [shuzijun/leetcode-editor#508]
![image](https://user-images.githubusercontent.com/33370220/171044067-0277f3cd-8fcc-4b27-afa9-bbea6209e74c.png)

1.如果存在Ques.cpp，再打开一道题不会覆盖Ques.cpp(我把设置中的文件名改成了Ques)，必须删掉Ques.cpp才行，希望能够覆盖掉已存在的文件。

2.希望增加功能，能够在打开一道题目后，可以自定义将一些参数(题目的标题，序号等)传给我写的程序。使得我可以用它来处理CMakeList

**Comment by shuzijun** [comment]
1.不要把所有题目的文件名都设置成同一个，每个题目都应该有一个独立的文件，以提供对应的缓存功能。
2.参考[自定义代码生成](https://github.com/shuzijun/leetcode-editor/blob/master/doc/CustomCode_ZH.md),除了文档中介绍的字段，可以使用的更多信息和工具参考[Question](https://github.com/shuzijun/leetcode-editor/blob/master/src/main/java/com/shuzijun/leetcode/plugin/model/Question.java) [VelocityTool](https://github.com/shuzijun/leetcode-editor/blob/master/src/main/java/com/shuzijun/leetcode/plugin/utils/VelocityTool.java).
