### ISSUE TITLE
Code Template 中的 package 定义和代码生成路径不符

### ISSUE THREAD

**Issue by dynj** [shuzijun/leetcode-editor#509]
**Describe the bug**
Code Template 中的 package 定义和代码生成路径不符

**To Reproduce**
1. Go to Code Template, input `package leetcode;`
2. Click on 'Apply' button.
3. Double click a problem, the created .java file will be created at path `leetcode/editor/en`

**Software versions(*Help* -> *About*)**
- Product:  IDEA 2022.1 Community Edition
- Runtime version: openjdk version "18.0.1.1" 2022-04-22
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS: Apple MacOSX Silicon

  
  ```

**Comment by shuzijun** [comment]
包的定义与路径无关，为了保护其他文件，固定前缀路径为leetcode/editor/(en|cn)

**Comment by BlackWyJiang** [comment]
> 包的定义与路径无关，为了保护其他文件，固定前缀路径为leetcode/editor/(en|cn)

我使用的Code Template 为：
------------------------------
${question.content}
 package leetcode.editor.cn.q$!velocityTool.toPinyinAndTrims(${question.frontendQuestionId}).time$!velocityTool.date("yyyyMMdd");
 public class $!velocityTool.camelCaseName(${question.titleSlug}){
      public static void main(String[] args) {
           
      }
      ${question.code}
}
------------------------------
实际生成的代码为：
`//////////////////用两个栈实现一个队列。队列的声明如下，请实现它的两个函数 appendTail 和 deleteHead ，分别完成在队列尾
//部插
////入整
//////数和
////////在队
//////////列头
////////////部删
//////////////除整
////////////////数的
//////////////////功能。(若队列中没有元素，deleteHead 操作返回 -1 ) 
//////////////////
////////////////// 
//////////////////
////////////////// 示例 1： 
//////////////////
////////////////// 输入：
//////////////////["CQueue","appendTail","deleteHead","deleteHead"]
//////////////////[[],[3],[],[]]
//////////////////输出：[null,null,3,-1]
////////////////// 
//////////////////
////////////////// 示例 2： 
//////////////////
////////////////// 输入：
//////////////////["CQueue","deleteHead","appendTail","appendTail","deleteHead",
//
//////////////"deleteHead"]
//////////////////[[],[],[5],[2],[],[]]
//////////////////输出：[null,-1,null,null,5,2]
////////////////// 
//////////////////
////////////////// 提示： 
//////////////////
////////////////// 
////////////////// 1 <= values <= 10000 
////////////////// 最多会对 appendTail、deleteHead 进行 10000 次调用 
////////////////// 
////////////////// Related Topics 栈 设计 队列 👍 565 👎 0
////////////////
//////////////
////////////
//////////
////////
//////
////
//

package leetcode.editor.cn.q20220712;

public class YongLiangGeZhanShiXianDuiLieLcof {
    public static void main(String[] args) {

    }

    //leetcode submit region begin(Prohibit modification and deletion)
    class CQueue {

        public CQueue() {

        }

        public void appendTail(int value) {

        }

        public int deleteHead() {

        }
    }

/**
 * Your CQueue object will be instantiated and called as such:
 * CQueue obj = new CQueue();
 * obj.appendTail(value);
 * int param_2 = obj.deleteHead();
 */
//leetcode submit region end(Prohibit modification and deletion)

}
`
包声明这一行与预期不符合
预期：package leetcode.editor.cn.qJianZhiOffer09.time20220712;
实际：package leetcode.editor.cn.q20220712;

**Comment by shuzijun** [comment]
@BlackWyJiang $!velocityTool.toPinyinAndTrims(${question.frontendQuestionId})  
question.frontendQuestionId 是题目的编号，看预期是要把标题放进去

**Comment by BlackWyJiang** [comment]
> @BlackWyJiang !velocityTool.toPinyinAndTrims({question.frontendQuestionId}) question.frontendQuestionId 是题目的编号，看预期是要把标题放进去
感谢回复^_^
这个在标准的leetcode题目中是编号，在剑指offer中是中文加编号，所以考虑转成拼音；
至于上面的问题我看过代码后发现可能是我不太熟悉模板语法，time被识别成关键词或者某个函数了；改成下面模板就可以达到目的了；
-----------------
#set($nowName=".time")
${question.content}
package leetcode.editor.cn.q$!velocityTool.toPinyinAndTrims(${question.frontendQuestionId})$nowName$!velocityTool.date("yyyyMMdd");
public class $!velocityTool.camelCaseName(${question.titleSlug}){
public static void main(String[] args) {

}
${question.code}
}

-----------------
