### ISSUE TITLE
preview里面的中文乱码，修改了File Encoding还是不好使

### ISSUE THREAD

**Issue by asuleyhg** [shuzijun/leetcode-editor#510]
![image](https://user-images.githubusercontent.com/32755536/171551592-71734df1-80d8-419f-a55c-b12978296049.png)

**Comment by shuzijun** [comment]
参考##53 修改完成后重启IDE

**Comment by asuleyhg** [comment]
> 参考##53 修改完成后重启IDE

感谢，已修复
