### ISSUE TITLE
2022版本idea log无法换行

### ISSUE THREAD

**Issue by Traserve** [shuzijun/leetcode-editor#511]
之前运行的log是在event log窗口中显示，可以换行。更新为2022版后idea改用notification窗口，无法换行，很影响使用。
![image](https://user-images.githubusercontent.com/17785306/172012447-4c268d03-efc6-4654-80ec-c4d2528f82ce.png)

**Comment by shuzijun** [comment]
有新的log方案，代码还没同步，等下新版本吧

**Comment by shuzijun** [comment]
fix [v8.2](https://github.com/shuzijun/leetcode-editor/releases/tag/v8.2)
