### ISSUE TITLE
Feature request for debugger in leetcode editor in pycharm

### ISSUE THREAD

**Issue by Ankan1998** [shuzijun/leetcode-editor#513]
Leetcode editor works fine but I face issues when there is a coding error and want to debug the code. The support for debugger is not yet available in leetcode editor. 

It would be a complete package if the pycharm debugger can be integrated with the leetcode editor.

**Comment by shuzijun** [comment]
You can refer to [leetcode-question](https://github.com/shuzijun/leetcode-question),Configure a template that conforms to python syntax.
