### ISSUE TITLE
IDEA 2019.3.5版本 登录不了

### ISSUE THREAD

**Issue by luoyi2019** [shuzijun/leetcode-editor#514]
IDEA 2019.3.5版本  插件版本： 6.9    
账号密码是对的 上个月开始突然登录不了 不知道为什么 感觉应该是获取不到token  
点击登录 提示：无法判断登陆状态，请尝试登陆网页版后，再次重试 

但是登录网页之后还是不行

![企业微信截图_16549381956228](https://user-images.githubusercontent.com/54498962/173181355-2f485187-b4ea-4721-9611-0fc1e48d10f1.png)

**Comment by shuzijun** [comment]
https://github.com/shuzijun/leetcode-editor/issues/491 有临时解决方案
https://github.com/shuzijun/leetcode-editor/issues/497 有相关版本发布说明
