### ISSUE TITLE
部分中文乱码

### ISSUE THREAD

**Issue by guochong666** [shuzijun/leetcode-editor#523]
![Snipaste_2022-07-01_14-08-44](https://user-images.githubusercontent.com/46960092/176834615-d3de49e4-f726-47c3-86bb-6f56da3c6b0c.png)
题干描述没问题，显示正常。labuladong 思路 中乱码，代码中的注释也乱码。

**Comment by guochong666** [comment]
-Dfile.encoding=utf-8
已添加，已重启，仍然乱码。

**Comment by shuzijun** [comment]
不是本项目提供的功能
