### ISSUE TITLE
无法debug   点击run 直接提交

### ISSUE THREAD

**Issue by DPSDL** [shuzijun/leetcode-editor#524]
**Describe the bug**

**To Reproduce**

**Software versions(*Help* -> *About*)**
- Product: [e.g IDEA 2020.2]
- Runtime version:[e.g 11.0.7+10-b944.20 amd64]
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS:[e.g Windows 10]

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:
  ```
  
  ```

**Comment by shuzijun** [comment]
请参考[自定义代码](https://github.com/shuzijun/leetcode-editor/blob/master/doc/CustomCode_ZH.md#%E9%85%8D%E7%BD%AE)
