### ISSUE TITLE
重复打开同一道题时，md文件会发生格式错乱

### ISSUE THREAD

**Issue by yuanleyuanleyuan** [shuzijun/leetcode-editor#525]
![image](https://user-images.githubusercontent.com/89004253/178102503-ba0b86ed-b64e-4297-9cfb-bae8bb1f2957.png)

只有第一次打开是正常的，后面每次打开打开过的问题，格式都会乱，
实测删除生成的md文件不能解决，但是重启idea会恢复正常

**Comment by Qiyuanc** [comment]
一样的问题，我的md文件还会直接加载不出来

**Comment by shuzijun** [comment]
提供一下具体的版本和复现步骤

**Comment by Qiyuanc** [comment]
我是第一次打开时正常，然后切换了临时文件路径，再打开了第二次出现了这个问题。
重启IDEA后问题解决，目前不切换临时文件路径没有问题。

**Comment by yuanleyuanleyuan** [comment]
插件版本8.1，idea版本2021.2.2

**Comment by yuanleyuanleyuan** [comment]
> 提供一下具体的版本和复现步骤

版本是8.1，idea是2021.2.2

**Comment by shuzijun** [comment]
> > 提供一下具体的版本和复现步骤
> 
> 版本是8.1，idea是2021.2.2，只要同一题多次去打开，就会出现，且只有第一次是正确的，目前看来应该是每生成一次md文件，md文件每行的最开始就会多两个“//"，图上就是打开了3次的结果

这个问题现在的代码修复了，可以先用一下快照版https://github.com/shuzijun/leetcode-editor/actions/runs/2643852947

**Comment by yuanleyuanleyuan** [comment]
> > > 提供一下具体的版本和复现步骤
> > 
> > 
> > 版本是8.1，idea是2021.2.2，只要同一题多次去打开，就会出现，且只有第一次是正确的，目前看来应该是每生成一次md文件，md文件每行的最开始就会多两个“//"，图上就是打开了3次的结果
> 
> 这个问题现在的代码修复了，可以先用一下快照版https://github.com/shuzijun/leetcode-editor/actions/runs/2643852947

好的，谢谢回复，期待新版本上线

**Comment by shuzijun** [comment]
fix [v8.2](https://github.com/shuzijun/leetcode-editor/releases/tag/v8.2)
