### ISSUE TITLE
模板 ${question.titleSlug} 与 ${question.code} 中的预期不符

### ISSUE THREAD

**Issue by unkoe** [shuzijun/leetcode-editor#530]
**Describe the bug**

由于题目标记 `${question.titleSlug}` 使用的是 question 的 url 路径，可能无法用于提供预期的 code function name 用于调试。

模板
```
${question.content}

${question.code}

if __name__ == "__main__":
    so = Solution()
    so.$!velocityTool.smallCamelCaseName(${question.titleSlug})()
```
以 [12. 整数转罗马数字](https://leetcode.cn/problems/integer-to-roman/) 为例，生成的结果：

```
# leetcode submit region begin(Prohibit modification and deletion)
class Solution:
    def intToRoman(self, num: int) -> str:
# leetcode submit region end(Prohibit modification and deletion)


if __name__ == "__main__":
    so = Solution()
    so.integerToRoman()
```

**Software versions(*Help* -> *About*)**
- Product: IDEA 2021.1
- Runtime version: 11.0.10+9-b1341.41 amd64
- VM: Dynamic Code Evolution 64 -Bit Server VM by JetBrains s.r.o.
- OS: Windows 10

**Question(Optional)**
- URL: leetcode.cn
- Code Type: Python3

**Comment by shuzijun** [comment]
titleSlug是题目标记，并不是代码的方法名
