### ISSUE TITLE
关于模板中${question.content}的用法

### ISSUE THREAD

**Issue by yuanleyuanleyuan** [shuzijun/leetcode-editor#531]
虽然现在每次手动改也不算麻烦，但是希望可以考虑支持一下这个

在使用${question.content}时，每行自动携带“//”，导致现在直接在文档注释中使用时如下：
![image](https://user-images.githubusercontent.com/89004253/178963581-fdd36291-4438-493f-aa1d-0c189d187c36.png)

如果不带“//”，则可以做到如下效果，idea也可以缩起来看，比较清爽些
![image](https://user-images.githubusercontent.com/89004253/178963947-77090a79-fd23-4315-b8d4-824951100a7e.png)
![image](https://user-images.githubusercontent.com/89004253/178964084-490a21c8-ed3e-45a9-8fce-4c638198f00c.png)

**Comment by shuzijun** [comment]
配置里开启多行注释

**Comment by shuzijun** [comment]
${question.xxx}只是一个占位符，在渲染时替换成对应内容，无法识别到外面的内容进行适配。
另一个解决方案是可以在外面对这个内容进行再次加工,例如在头部加入其他内容
```
/** 题目编号:${question.frontendQuestionId} $!velocityTool.substring(${question.content},3)
```

**Comment by shuaixiaomi** [comment]
![image](https://user-images.githubusercontent.com/77660384/180119702-c9833ec0-36fe-4785-b442-8d09fd6429a5.png)


> 配置里开启多行注释

请问//leetcode submit region begin 和 //leetcode submit region end 能自动去掉吗，或者像您示例里面那样是--begin-- --end--

**Comment by yuanleyuanleyuan** [comment]
> ![image](https://user-images.githubusercontent.com/77660384/180119702-c9833ec0-36fe-4785-b442-8d09fd6429a5.png)
> 
> > 配置里开启多行注释
> 
> 请问//leetcode submit region begin 和 //leetcode submit region end 能自动去掉吗，或者像您示例里面那样是--begin-- --end--

鼠标放上去，快捷键ctrl + -，就可以了
