### ISSUE TITLE
Leetcode editor未登录时文字乱码

### ISSUE THREAD

**Issue by yangtzech** [shuzijun/leetcode-editor#537]
**Describe the bug**
打开clion，Leetcode editor未登录时文字乱码

**To Reproduce**
1. 打开clion
2. 点击工具栏Leetcode
3. 看到错误
![image](https://user-images.githubusercontent.com/41911522/180691145-d6d1e541-409e-42a4-bd34-5536ed37eab4.png)

**Software versions(*Help* -> *About*)**
- Product: CLion 2022.1.3
- Runtime version:11.0.15+10-b2043.56 amd64
- VM:OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- OS:Windows 10 10.0

**Comment by Liuxin-hub** [comment]
同问

**Comment by shuzijun** [comment]
还没复现这个错误，可以尝试在Help->Edit Custom VM options中增加或者修改-Dfile.encoding=utf-8

**Comment by yangtzech** [comment]
有效果
