### ISSUE TITLE
我要隐藏题目，但是每次重新打开IDEA，都要重新配置才能隐藏题目

### ISSUE THREAD

**Issue by Liuxin-hub** [shuzijun/leetcode-editor#538]
![1](https://user-images.githubusercontent.com/62970199/180722957-7c15b06e-dee7-451e-a59a-9d8bdca1f690.png)

**Comment by yangtzech** [comment]
设置题目在右边，重新打开IDE后，题目会在左边打开，需重新更改设置后点击应用。

**Comment by shuzijun** [comment]
可以尝试在配置文件leetcode-config.xml中删除QuestionEditor的配置项，重启IDE后再次配置。

**Comment by Liuxin-hub** [comment]
大佬不太理解，可以出一个小白教程吗

**Comment by yangtzech** [comment]
> 可以尝试在配置文件leetcode-config.xml中删除QuestionEditor的配置项，重启IDE后再次配置。

不行

**Comment by mffseal** [comment]
我也有同样的问题，这个配置项在重启idea后会恢复到默认值。

**Comment by Liuxin-hub** [comment]
> 可以尝试在配置文件leetcode-config.xml中删除QuestionEditor的配置项，重启IDE后再次配置。

leetcode-config.xml中，没有questionEditor配置项，即便在xml中添加该配置项，重启IDEA登录后questionEditor设置项并不会从文件中读取，在保存图形化的设置时，该配置也不会被写入到配置文件中。
![P~607YAEU@~2CNE~LM5M5}S](https://user-images.githubusercontent.com/62970199/183253987-354ac549-8578-4f9e-b323-b6c2c4b8877c.png)
该配置项没有写到文件中：
![ML_Y%)3BM{JFN4F5$K3F5Y5](https://user-images.githubusercontent.com/62970199/183254059-1753caf7-f2c2-471e-9a6c-e1b8bcee6eb2.png)

**Comment by shuzijun** [comment]
> > 可以尝试在配置文件leetcode-config.xml中删除QuestionEditor的配置项，重启IDE后再次配置。
> 
> leetcode-config.xml中，没有questionEditor配置项，即便在xml中添加该配置项，重启IDEA登录后questionEditor设置项并不会从文件中读取，在保存图形化的设置时，该配置也不会被写入到配置文件中。 

新版本已修复
