### ISSUE TITLE
包含题目程序的java的文件，名字的后缀前多了一些空格

### ISSUE THREAD

**Issue by mohalikeyou** [shuzijun/leetcode-editor#541]
![image](https://user-images.githubusercontent.com/77050354/181405278-ed5d5c86-1f88-4061-9ee5-169b4d1ae3bf.png)

因为这个原因IDEA在这个类会标红报错，如下：
![image](https://user-images.githubusercontent.com/77050354/181405365-54505c16-28d4-43cd-8096-458fd14a858f.png)

请问这个怎么解决

**Comment by shuzijun** [comment]
在自定义模版里，检查文件名最后是不是多了一个空格

**Comment by mohalikeyou** [comment]
> 在自定义模版里，检查文件名最后是不是多了一个空格

感谢大佬回复。已解决
