### ISSUE TITLE
The page failed to load, please check the network and open it again

### ISSUE THREAD

**Issue by FLightZGit** [shuzijun/leetcode-editor#543]
**Describe the bug**
.com点击登录弹出The page failed to load, please check the network and open it again

**To Reproduce**

**Software versions(*Help* -> *About*)**
- Product: [e.g IDEA 2020.2]
- Runtime version:[e.g 11.0.7+10-b944.20 amd64]
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS:[e.g Windows 10]

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:
  ```
  
  ```

**Comment by shuzijun** [comment]
该提示是无法访问力扣的网页，检查下网络

**Comment by FLightZGit** [comment]
网络没问题啊，Login页面空白打不开

**Comment by shuzijun** [comment]
如果浏览器无法显示，可以尝试使用cookie登录,在配置中打开cookie登录，参考[LoginHelp](https://github.com/shuzijun/leetcode-editor/blob/master/doc/LoginHelp_ZH.md)获取cookie

**Comment by FLightZGit** [comment]
![Screenshot 2022-07-31 151805](https://user-images.githubusercontent.com/91889802/182014711-7e51cbce-09dd-42de-91e9-81f2ca0e0dc3.png)
这个框就点不了

**Comment by shuzijun** [comment]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/27667179/182015166-d975ab18-21fd-4df8-98ba-f08371f993cd.png">
在配置中打开这个，再点击登录按钮就会弹出输入cookie的窗口了

**Comment by FLightZGit** [comment]
好了，谢谢！
