### ISSUE TITLE
v8.2 侧栏的初始页面乱码

### ISSUE THREAD

**Issue by Ergofly** [shuzijun/leetcode-editor#544]
如图所示，侧栏初始页乱码
![image](https://user-images.githubusercontent.com/43678037/181921159-18729943-a05e-4aad-be00-b15616f020d1.png)

环境：
Clion 2021.2.3 语言英文
插件版本 v8.2

**Comment by shuzijun** [comment]
参考 #537

**Comment by Ergofly** [comment]
> 参考 #537
有效，但是这个问题在上一个版本v8.1中不存在，更新之后才出现。
