### ISSUE TITLE
关于执行时间和内存消耗问题

### ISSUE THREAD

**Issue by lxxself** [shuzijun/leetcode-editor#55]
![image](https://user-images.githubusercontent.com/8406766/64310088-5c969e00-cfd1-11e9-9ef5-d9d69044fd35.png)
同样的java代码，第一行是网站上提交的，第二行是通过插件提交的。
不知道大家有没有遇到，这是正常现象么

**Comment by shuzijun** [comment]
同样的代码运行情况受到很多因素的影响，可以尝试在不同时间段提交，得到的结果也不相同。
