### ISSUE TITLE
选择运行代码，控制台报错Code does not exist

### ISSUE THREAD

**Issue by GitJumping** [shuzijun/leetcode-editor#556]
**Describe the bug**

**To Reproduce**
如下图所示
选择运行代码，控制台报错 Code does not exist
<img width="1270" alt="1" src="https://user-images.githubusercontent.com/67416087/184532340-7aaa006a-00df-4478-bcfa-b5105e106ed6.png">
<img width="196" alt="2" src="https://user-images.githubusercontent.com/67416087/184532344-40fe58b6-7c2e-4ff8-962a-4658a4ac2e0c.png">

**Software versions(*Help* -> *About*)**

- Product: [IDEA 2022.1.2]
- Runtime version:[11.0.15+10-b2043.56 x86_64]
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS:[e.g macOS]

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:
  ```
  
  ```

**Comment by shuzijun** [comment]
尝试从插件窗口里重新打开题目
