### ISSUE TITLE
webstorm上无法登陆国内版平台

### ISSUE THREAD

**Issue by angleliuxue** [shuzijun/leetcode-editor#557]
**Describe the bug**

- 
![image](https://user-images.githubusercontent.com/28160787/184615544-fc768765-72ca-46b3-817c-a0c2eac3ff60.png)

![image](https://user-images.githubusercontent.com/28160787/184616164-075680bd-02aa-4287-92cb-66a8a78c8072.png)

国内平台域名已换成 leetcode.cn 。

配置上选项里还是旧的域名。不清楚是不是没同步域名导致的不能登陆

**Comment by shuzijun** [comment]
参考#491 安装新版本
