### ISSUE TITLE
【bug】登录对话框无法输入 cookie

### ISSUE THREAD

**Issue by xozoz** [shuzijun/leetcode-editor#558]
**Describe the bug**
登录时，输入 cookie 的弹窗显示为白色，无法输入 cookie，导致无法登录
昨日还可正常使用，今日突然出现这种情况

**To Reproduce**
![CleanShot 2022-08-16 at 23 41 18@2x](https://user-images.githubusercontent.com/21237993/184921505-97e6059f-2709-4300-bd7a-a969f04914fd.png)

确认当前网络环境正常，不然怎么提 issue 呢

**Software versions(*Help* -> *About*)**
- Product:  IDEA 2022.2
- OS: mac monterey version 12.5

昨日插件使用正常，今日不正常，期间 os 以及 idea 版本均为变更

**补充**
- 而且点击登录按钮后，弹窗偶发性会变成下图这样，放大对话框后，同样会出现上图 **全白**的情况

<img width="458" alt="CleanShot 2022-08-16 at 23 48 41@2x" src="https://user-images.githubusercontent.com/21237993/184923138-8b221fe2-b925-49f0-bb3d-cef3e4f71e4e.png">

**Comment by shuzijun** [comment]
新版本默认浏览器登录，使用cookie登录需要在配置里开启

**Comment by xozoz** [comment]
感谢，已解决
