### ISSUE TITLE
【bug】使用快捷键提交代码失败

### ISSUE THREAD

**Issue by Jemair** [shuzijun/leetcode-editor#56]
为 Run code 和 Submit 添加了快捷键，使用快捷键提交时报错，在右键菜单点击提交正常

![image](https://user-images.githubusercontent.com/20502467/64316394-4b588c00-cfe7-11e9-92c2-2cc0420ea668.png)

**Comment by shuzijun** [comment]
目前窗口的定位必须在leetcode的导航里才可以使用对应的快捷键，后续优化此部分
