### ISSUE TITLE
自动生成的类名Solution容易重复导致本地编译报错

### ISSUE THREAD

**Issue by sunshine98** [shuzijun/leetcode-editor#561]
插件对于每一个题目生成的java类名称都叫Solution，造成想在本地调试时，会一直报：
java: 类重复: Solution
我的想法是能不能在Solution后面加上题目的ID，例如第11题生成的java类名就叫：Solution11
尽量避免冲突呢？

**Comment by shuzijun** [comment]
参考[自定义代码](https://github.com/shuzijun/leetcode-editor/blob/master/doc/CustomCode_ZH.md)
