### ISSUE TITLE
可以出一个分组的功能吗

### ISSUE THREAD

**Issue by yunlongn** [shuzijun/leetcode-editor#563]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

将每一种类型都进行分组。放在列表里边。这样可以针对类型进行练习

**Comment by shuzijun** [comment]
是指什么维度的分组？可以尝试使用搜索中的一些筛选条件

**Comment by yunlongn** [comment]
抱歉，我找了许久没有留意到此功能。
