### ISSUE TITLE
goland 没有代码提示 代码也无高亮

### ISSUE THREAD

**Issue by Hylio** [shuzijun/leetcode-editor#565]
在pycharm中可以正常使用，但在goland中没有代码提示，也只有部分高亮。
这是在插件中写的代码：
![Snipaste_2022-09-07_12-34-19](https://user-images.githubusercontent.com/49382531/188790051-0991ddba-a260-4608-8b3e-acf75a3af8a3.png)
这是在其他文件中的代码：
![Snipaste_2022-09-07_12-34-28](https://user-images.githubusercontent.com/49382531/188790058-a1fe2b86-7ec0-401e-93f5-f539d9798c3e.png)

**Comment by shuzijun** [comment]
参考 https://github.com/shuzijun/leetcode-editor/blob/master/doc/CustomCode_ZH.md

**Comment by Hylio** [comment]
好的，解决了
