### ISSUE TITLE
题目列表里第一列状态显示不全

### ISSUE THREAD

**Issue by curiositer** [shuzijun/leetcode-editor#567]
**Desc**
请教一下如何调整每一列的宽度。

- Product: [Clion 2022.2]

- OS:[ Windows 10]

![image](https://user-images.githubusercontent.com/34828878/189510345-52c5e4c2-3cf1-477d-94fc-113b94116f38.png)

第一列的状态栏显示不全，拖拉也是没有反应的，该怎么解决呢？谢谢！

**Comment by szxypi** [comment]
我的也是这样，我的环境是 IntelliJ IDEA 2022.2.2 (Ultimate Edition)
