### ISSUE TITLE
【enhancement】希望能显示log

### ISSUE THREAD

**Issue by Jemair** [shuzijun/leetcode-editor#57]
如题，在网站上打印的Log在 run code 之后是会显示的
但是在插件中并没有显示 stdout

接口中实际是有返回的  应该工作量不大
![image](https://user-images.githubusercontent.com/20502467/64323416-0c323700-cff7-11e9-9228-060dedff399a.png)

**Comment by Jemair** [comment]
还有error希望也能显示

![image](https://user-images.githubusercontent.com/20502467/64403986-0303a180-d0ad-11e9-95a1-e9af93bda430.png)

**Comment by shuzijun** [comment]
![20190909092652](https://user-images.githubusercontent.com/27667179/64501088-806c2380-d2f2-11e9-9e6d-5a72f1e153e7.png)
是这种提示？

**Comment by Jemair** [comment]
是的

还有event log里面
我一般提交之后直接看event log   不过我的理解是这两个地方的日志应该是一致的..

**Comment by shuzijun** [comment]
目前提交成功之后是有日志提示的，一般是在窗口的右下角，如果没有看到通知，可以手动点开。
![20190909160608](https://user-images.githubusercontent.com/27667179/64513886-16687400-d31c-11e9-9370-807fc1a454fa.png)

**Comment by Jemair** [comment]
啊..你误会了  我说的就是这个日志  但是现在这个日志中缺两个字段
一个是 code_output 对应 JS里的 console.log  是代码中打印的日志
一个是 runtime_error 返回的是代码报错时输出的报错内容

**Comment by shuzijun** [comment]
可以提供下有这两个字段的运行代码么？

**Comment by Jemair** [comment]
206 题   执行环境 Javascript

var reverseList = function(head) {
    console.log(123123)
    throw new Error(123)
};

**Comment by shuzijun** [comment]
[V5.2](https://github.com/shuzijun/leetcode-editor/blob/dev/doc/leetcode-editor-V5.2.zip) 开发版临时加了一下，可以先离线安装一下

**Comment by Jemair** [comment]
好的 谢谢大佬
