### ISSUE TITLE
LeetCode Editor v6.9 登录失败

### ISSUE THREAD

**Issue by kider** [shuzijun/leetcode-editor#572]
**Desc**
配置里有设置用户名密码，但是未登录成功，log显示:
**info: 无法判断登陆状态，请尝试登陆网页版后，再次重试。**
然后点击SignIn，粘贴cookie信息进来，弹框提示:**登录失败**

**Software versions**
idea v2018.3
LeetCode Editor v6.9

**Comment by shuzijun** [comment]
力扣域名更改，版本已失效，参考https://github.com/shuzijun/leetcode-editor/issues/497#issuecomment-1123443731 安装
