### ISSUE TITLE
8.1版本为什么没有具体题目在list中的定位功能了？

### ISSUE THREAD

**Issue by ghost** [shuzijun/leetcode-editor#579]
现在功能tab只有
![image](https://user-images.githubusercontent.com/55909871/195185007-ded9d59c-6ed4-40e9-8a44-47bc1c2d3bcf.png)
原本的版本是有
![image](https://user-images.githubusercontent.com/55909871/195185065-8b140964-75df-4117-bb70-d5ced4622a8e.png)
用于定位题目的，为什么删了？很好用的功能

**Comment by shuzijun** [comment]
更新一下版本，新版加上了
