### ISSUE TITLE
在2020.3的idea上用8.4版本的leetcode，题目内容是乱码

### ISSUE THREAD

**Issue by ghost** [shuzijun/leetcode-editor#580]
如下
![image](https://user-images.githubusercontent.com/55909871/195318086-984271f6-60b2-4cad-a7f9-11fe19153a20.png)

**Comment by Eric-Li-2356** [comment]
win10系统

**Comment by shuzijun** [comment]
参考https://github.com/shuzijun/leetcode-editor/issues/53
