### ISSUE TITLE
增加默认不分屏幕选项的视图

### ISSUE THREAD

**Issue by 847850277** [shuzijun/leetcode-editor#581]
大佬能不能在某个版本支持一下默认不分屏幕的视图。
    需要使用该场景的时候，比如我在IDEA中使用了IDEA的分屏功能。同时插件也进行了分屏幕，此时就比较窄了。
    
![WechatIMG1403](https://user-images.githubusercontent.com/12622645/195526268-9bad2be1-6657-4635-9b2e-8f702aade228.png)

**Comment by 847850277** [comment]
> 新打开的文件拆分行为是上次设置的结果，例如当前题目是只显示题目的，新文件也是只显示题目

上次设置指的是？ 以前老版本的插件是能支持只展示这一个视图的。
![image](https://user-images.githubusercontent.com/12622645/195543698-11cdf4b6-8925-460c-8774-0fd660616da4.png)

**Comment by shuzijun** [comment]
是指可以选择一下右上角的只展示代码区，然后新打开的题目也会只展示代码区。
如果想关闭这个拆分，可以去配置选择关闭。

**Comment by 847850277** [comment]
好的，3Q大佬！
