### ISSUE TITLE
Python3生成的代码不符合PEP8

### ISSUE THREAD

**Issue by danerlt** [shuzijun/leetcode-editor#589]
**Describe the bug**

设置中CodeType,随便选择一个题目,生成的的代码,默认生成的方法是驼峰命名法,
![image](https://user-images.githubusercontent.com/14197717/197845058-b4e0968f-e2ff-4a92-9396-aa32817d0a65.png)
![image](https://user-images.githubusercontent.com/14197717/197845538-e6b51b99-ad08-4cba-ba67-fbb0bf5460ce.png)

**Software versions(*Help* -> *About*)**
- Product: [Pycharm2020.2]
- Runtime version: 17.0.4.1+7-b469.62 amd64
- VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- OS:[e.g Windows 10]

问题1:
Python PEP8中 方法建议使用下划线分隔,这个要怎么配置?
问题2:
能否自动导入tying相关的包

```
  # leetcode submit region begin(Prohibit modification and deletion)
class Solution:
    def heightChecker(self, heights: List[int]) -> int:
    
    # 能否自动生成下面的格式
    def height_checker(self, heights: List[int]) -> int:
        pass
# leetcode submit region end(Prohibit modification and deletion)


```

**Comment by shuzijun** [comment]
1. 不支持， **leetcode submit region xxx** 之间的代码是力扣提供的，方法名与参数都不能修改
2. 如果是**from xxx import xxxx**的导入方式，参考[自定义代码格式](https://github.com/shuzijun/leetcode-editor/blob/master/doc/CustomCode_ZH.md#%E9%85%8D%E7%BD%AE)

**Comment by danerlt** [comment]
@shuzijun 谢谢解答
