### ISSUE TITLE
Run Code超出时间限制时候显示 “运行失败null”

### ISSUE THREAD

**Issue by JackCoulson** [shuzijun/leetcode-editor#59]
![image](https://user-images.githubusercontent.com/44354018/64679628-b0602600-d4ae-11e9-922b-7e844cb716da.png)
![image](https://user-images.githubusercontent.com/44354018/64679695-d08fe500-d4ae-11e9-9d96-609dfd95ce6e.png)

**Comment by shuzijun** [comment]
https://github.com/shuzijun/leetcode-editor/issues/57#issuecomment-529806017 参考这个，安装一下开发版
