### ISSUE TITLE
如何加入开发

### ISSUE THREAD

**Issue by gz-justdoit** [shuzijun/leetcode-editor#594]
1.${question.title}中存在空格，导致文件报错，若修改手动文件名称，则无法提交
我想着是在VelocityTool中添加，如下
`
/**
 * Convert Chinese space to underline <br>
 * 将汉字中空格替换下划线
 *
 * @param str
 * @return
 */
public static String spaceToUnderline(String str) {
    return str.replace(" ", "_");
}
`
2.${question.code}无默认返回值
VelocityTool中添加方法，是否可行？
3.code template中template constant不能整体缩进
VelocityTool中添加方法，是否可行？
4.VelocityTool后面的三个方法，未添加到设置里面的template constant

**Comment by arron-rgb** [comment]
VelocityTool是用的apache的工具，见https://velocity.apache.org/tools/3.1/。文件名建议使用titleSlug。
仔细阅读README.md中的使用建议能够解决你的问题

**Comment by gz-justdoit** [comment]
标题中的空格已经用replaceAll操作成功。
但对于问题2和问题3，没有找到对应的方法

**Comment by shuzijun** [comment]
2. code是对应的代码，默认值的意义是什么？
3. 可以直接在模版里配置，例如要缩进content.将所有的换行换成换行+缩进的空格
```
#set( $new = "
" )
    $q.content.replaceAll("$new", "$new    ")

${q.code}
```
