### ISSUE TITLE
content乱码

### ISSUE THREAD

**Issue by ppxiaodi** [shuzijun/leetcode-editor#597]
打开content，显示乱码，使用leetcode.cn登录的
![image](https://user-images.githubusercontent.com/27324380/205849613-f357018d-013f-4532-8a2e-3dc9edd80d9b.png)

![image](https://user-images.githubusercontent.com/27324380/205849531-88d12e46-d409-4b47-bf15-14934cdbe986.png)

**Comment by ppxiaodi** [comment]
已解决

**Comment by chengweng** [comment]
> 已解决

怎么解决的，我这边也是这个问题，版本是8.1，idea是2020.2.1
