### ISSUE TITLE
可以加上List条目吗

### ISSUE THREAD

**Issue by ohkimchi** [shuzijun/leetcode-editor#6]
可以把top 100 liked questions加到左边栏吗 谢啦

**Comment by shuzijun** [comment]
@ohkimchi  可以提供一下网页上的入口么？我不太确认你说的是那个列表

**Comment by ohkimchi** [comment]
@shuzijun https://leetcode.com/problemset/all/?listId=79h8rn6 要的是这个吗

**Comment by ohkimchi** [comment]
@shuzijun 我的刷题习惯是找tag刷，比如array + backtracking，我会找出题目既有array的tag，也有backtracking的tag，要是大神能再加一个这样自由组合tag的功能就更好啦 哈哈我好贪啊

**Comment by shuzijun** [comment]
@ohkimchi  Lists 分类已添加，暂未上传到插件库，直接安装吧https://github.com/shuzijun/leetcode-editor/blob/master/doc/leetcode-editor-V3.1.zip。自定义分类查询后续更新。

**Comment by ohkimchi** [comment]
wow 好速度啊！！谢谢大神！！我现在来安装看一下

**Comment by ohkimchi** [comment]
@shuzijun 可以教我怎么帮的吗

**Comment by shuzijun** [comment]
@ohkimchi  https://jingyan.baidu.com/article/acf728fd7d964bf8e510a33a.html 最后一步选择上面下载的zip安装，不需要解压

**Comment by ohkimchi** [comment]
@shuzijun 装好了，谢谢你！！

**Comment by ohkimchi** [comment]
@shuzijun 数字君可以在左边再加一个company条目吗？比如我最近在刷Microsoft的，如果可以把每个公司的列出来就更好啦 API在这里https://leetcode.com/problemset/all/?companySlugs=microsoft

**Comment by shuzijun** [comment]
@ohkimchi  这部分为付费项目，我没有订阅，看不到这部分的请求内容

**Comment by ohkimchi** [comment]
@shuzijun 酱紫！还是要谢谢大神啦！
