### ISSUE TITLE
Idea 新ui的编辑菜单只能右键显示吗？没法悬浮？

### ISSUE THREAD

**Issue by Blockbuster-X** [shuzijun/leetcode-editor#602]
![image](https://user-images.githubusercontent.com/61620802/206843974-374b1fd5-d85f-4f86-9b54-96052fe99202.png)

**Comment by KEPADEDAIDAI** [comment]
Clion也有同样的问题

**Comment by shuzijun** [comment]
应该与后面3次提交有关，最新版还没包含修复的内容
https://github.com/JetBrains/intellij-community/commits/master/platform/platform-impl/src/com/intellij/openapi/fileEditor/TextEditorWithPreview.java
