### ISSUE TITLE
登录后每日一题总会显示“D”，无论是否做过

### ISSUE THREAD

**Issue by Haoxi2002** [shuzijun/leetcode-editor#604]
**Describe the bug**
登录后每日一题总会显示“D”，无论是否做过

**To Reproduce**
1. 关闭IDEA
2. 打开IDEA
3. 登录账号并刷新列表
4. 即使做过的每日一题仍会显示‘D’而非‘√’

**Comment by shuzijun** [comment]
这是每日一题的固定标识，与题目提交状态无关。
