### ISSUE TITLE
Remove "Related Topics" from Question's content

### ISSUE THREAD

**Issue by danielpaz6** [shuzijun/leetcode-editor#606]
**Desc**
Every question description ("Content" tab) at the bottom has a "Related Topics" section which to be honest reveal or give you significant hint on how to solve the problem.

In LeetCode web this section is hidden by default and you can choose whether or not if want to see it by pressing on it.

So my suggestion is to remove it completely, or make it hideable somehow (which should be a default) either by Leetcode settings or by a pressing button besides that.

**Comment by shuzijun** [comment]
Open **Custom code template**, replace ${question.content} with $question.content.replaceAll("Related\sTopics.*","") in CodeTemplate

**Comment by danielpaz6** [comment]
It deletes it only from the code and not the description no? anyway It didn't work for me, wouldn't it remove the thumbs up/down as well?

By the way, maybe it could be a default? I think it should be

**Comment by shuzijun** [comment]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/27667179/209630476-5be831a7-8986-4b41-85cc-a6003c4d9bfc.png">
<img width="677" alt="image" src="https://user-images.githubusercontent.com/27667179/209630581-d9a0a314-a262-46d5-9750-b5c3e79ed58a.png">

Is that so?
You can try the[ pro version](https://plugins.jetbrains.com/plugin/17166-leetcode-editor-pro
). Sync to here in the future.

**Comment by danielpaz6** [comment]
Oh is it a pro feature? I used the free one
