### ISSUE TITLE
登录不成功

### ISSUE THREAD

**Issue by ydhgbcqz123** [shuzijun/leetcode-editor#607]
昨天还能正常登录，今天怎么就登不上了，更改密码也不行，可以网页登入力扣

**Comment by ydhgbcqz123** [comment]
很奇怪，晚上登了一下，登上去了，今天白天登录，又登不上去了

**Comment by shuzijun** [comment]
> 很奇怪，晚上登了一下，登上去了，今天白天登录，又登不上去了

插件版本，力扣的网站等信息提供一下

**Comment by ydhgbcqz123** [comment]
插件版本8.6，之前是8.1现在升级到8.6依然同样问题，力扣选的leetcode.cn，还有一个细节，而且无法加载题目

**Comment by ydhgbcqz123** [comment]
应该是网络问题，不知道为啥，连上公司网络，就没法登录了，换个网就可以了
