### ISSUE TITLE
SQL未格式化导致提交失败

### ISSUE THREAD

**Issue by jia9iZhang** [shuzijun/leetcode-editor#609]
**Describe the bug**
Leetcode-183的SQL答案在本地提交控制台报错,在LeetCode官网提交显示成功.
`> 2022/12/30 14:19:42	
运行失败:
	Line 1: error: class, interface, enum, or record expected
select Customers.Name as 'Customers'
^
Line 1: error: unclosed character literal
select Customers.Name as 'Customers'
                         ^
Line 1: error: illegal line end in character literal
select Customers.Name as 'Customers'
                                   ^
3 errors`

**To Reproduce**
1. 打开SQL提
2. 输入SQL回答
`select Customers.Name as 'Customers'
from Customers
where Customers.Id not in (
        select CustomerId
        from Orders)`
3. 点击运行按钮
4. 控制台提示报错:
`> 2022/12/30 14:19:42	
运行失败:
	Line 1: error: class, interface, enum, or record expected
select Customers.Name as 'Customers'
^
Line 1: error: unclosed character literal
select Customers.Name as 'Customers'
                         ^
Line 1: error: illegal line end in character literal
select Customers.Name as 'Customers'
                                   ^
3 errors`
<img width="930" alt="image" src="https://user-images.githubusercontent.com/50917145/210041861-dce21bff-8a3a-4f11-afa9-471c3c1e51b3.png">

**Software versions(*Help* -> *About*)**
- Product:  IDEA 2022.2.4 UE
- Runtime version:17.0.5+7-b469.71 aarch64
- VM:OpenJDK 64-Bit Server VM，JetBrains s.r.o.
- OS: macOS 12.1

**Comment by shuzijun** [comment]
代码里应该提示了//There is no code of Go type for this problem
如果要提交其他类型的代码，需要先在配置里修改代码类型

**Comment by jia9iZhang** [comment]
是的 需要先配置代码类型
