### ISSUE TITLE
编辑器区如果打开的是部分框架源码的java文件,点击题目没反应,无法弹出题目的页面

### ISSUE THREAD

**Issue by AmberYouth** [shuzijun/leetcode-editor#610]
**Describe the bug**

**To Reproduce**

**Software versions(*Help* -> *About*)**
- Product: [e.g IDEA 2020.2]
- Runtime version:[e.g 11.0.7+10-b944.20 amd64]
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS:[e.g Windows 10]

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:
  ```
  
  ```

**Comment by shuzijun** [comment]
请完善下模版里的软件版本和插件版本，以便复现问题。
同时检查下右下角是否有红色叹号的错误。
