### ISSUE TITLE
题目HTML格式显示

### ISSUE THREAD

**Issue by ChristinaChenyiwen** [shuzijun/leetcode-editor#611]
我不知道碰了哪里，题目变成html格式显示了，该怎么还原
<img width="644" alt="截屏2023-01-12 20 34 03" src="https://user-images.githubusercontent.com/53345712/212067644-8efc6ccc-72f1-4058-8846-5cf4230ab82f.png">

**Comment by shuzijun** [comment]
设置里有个选项
<img width="176" alt="image" src="https://user-images.githubusercontent.com/27667179/212226778-6cbff148-0adb-44e4-bb95-05cce70e822d.png">

**Comment by ChristinaChenyiwen** [comment]
谢谢你的回答，我昨天☑️这个选项后，其他题目恢复了正常显示，但是这道题目没有恢复（关闭这个题目后再打开/重启pycharm，以上两种方式都尝试过），不知道是不是一个bug。

**Comment by shuzijun** [comment]
已经缓存的题目是不会再修改了，你可以把这个题目的文件删了，重新打开一次

**Comment by LightlyFly** [comment]
> 已经缓存的题目是不会再修改了，你可以把这个题目的文件删了，重新打开一次
能不能把C++版本的题目单行斜线注释改成/** */的多行注释?

**Comment by shuzijun** [comment]
> > 能不能把C++版本的题目单行斜线注释改成/** */的多行注释?
@LightlyFly 配置里有多行注释的选项
