### ISSUE TITLE
在idea中使用插件中的笔记（Note）功能，无法编辑

### ISSUE THREAD

**Issue by lijyy** [shuzijun/leetcode-editor#616]
![图片1](https://user-images.githubusercontent.com/65594722/218795908-98f56b51-0d63-4ed1-a634-cf1a223825d1.png)

idea版本：2022.2.1

**Comment by shuzijun** [comment]
<img width="151" alt="image" src="https://user-images.githubusercontent.com/27667179/218913627-ca5aba0a-dc08-462e-8a89-e73d373c028b.png">
试试点击一下这几个按钮

**Comment by lijyy** [comment]
都点过了，依然无效。


在公司用的idea版本2021的，是可以的





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shuzijun/leetcode-editor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月15日(星期三) 上午10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shuzijun/leetcode-editor] 在idea中使用插件中的笔记（Note）功能，无法编辑 (Issue #616)





 

 试试点击一下这几个按钮

**Comment by lijyy** [comment]
多谢，问题已解决
