### ISSUE TITLE
希望能提供跨设备刷题的功能

### ISSUE THREAD

**Issue by ajiesw** [shuzijun/leetcode-editor#617]
在公司的笔记本刷题，代码在git，写一半，回来在台式上更新代码不能够继续。leetcode插件不识别
就像这样
![Snipaste_2023-02-17_22-48-29](https://user-images.githubusercontent.com/24909939/219687141-520d1578-5e18-4d0b-afbf-ef749db57e7e.jpg)
不知道如何让插件识别

**Comment by shuzijun** [comment]
把.idea/leetcode或者.idea/leetcode-pro的文件也同步一下
