### ISSUE TITLE
Support customize doc files location and offer more variables like "question.titleSlug"

### ISSUE THREAD

**Issue by paigeman** [shuzijun/leetcode-editor#620]
**Is your feature request related to a problem? Please describe.**
The doc directory is in java directory may discomfort somebody like me, and it's inconvenient for me to paste the package name in the code template when I am using java.

**Describe the solution you'd like**
1. add a textfield to customize doc files location. 
2. offer more variables like `${question.titleSlug}` . For example, I want to use `$currentPackage()` in code template to get the package name instead of pasting by myself.  I think the IDEA Live Template may be a good example.

**Additional context**

**Comment by shuzijun** [comment]
1.  You can try [Leetcode Editor Pro](https://plugins.jetbrains.com/plugin/17166-leetcode-editor-pro), which provides content directory configuration. The documentation location can be adjusted using a relative directory, for example: 
```
../../../../doc/${q.title}
```
2. Need to enumerate the specific content, of course, you can also use the provided api for simple text processing.

**Comment by paigeman** [comment]
Thank you for your reply, I will think about it.
