### ISSUE TITLE
打开题目后public类名红标提示需要重命名，自动重命名后插件功能失效

### ISSUE THREAD

**Issue by 1tex** [shuzijun/leetcode-editor#621]
**Desc**
对不起，这可能是蠢问题，但是我查了半天搞不懂，求帮助。
1. 双击题目打开编辑器，在class solution中写好题解。
2. public类标红，项目结构中中显示LongestValidParentheses.java下有个LongestValidParentheses文件，此时无法本地调试，可以使用悬浮插件进行run code和submit。
3. 点击标红的重命名文件，可以看到项目结构正常了，只有LongestValidParentheses文件，此时可以本地调试运行，但是插件的run code等功能失效。
<img width="1266" alt="截屏2023-03-06 16 18 11" src="https://user-images.githubusercontent.com/39019376/223057646-09e3d597-bdfd-4476-93d9-c879005bf1e2.png">
<img width="1297" alt="截屏2023-03-06 16 32 25" src="https://user-images.githubusercontent.com/39019376/223057754-348680fe-fd61-4f82-8abc-87f9dfa5b6f2.png">

**设备**
IntelliJ IDEA 2022.3.2 (Ultimate Edition)
MacBook pro m1pro

**Comment by shuzijun** [comment]
文件名配置里最后有一个空格，删除了就可以了

**Comment by 1tex** [comment]
> 文件名配置里最后有一个空格，删除了就可以了

啊，解决了！谢谢。
以后我会更加爱护自己的👀。
