### ISSUE TITLE
ListNode 相关报错

### ISSUE THREAD

**Issue by G-rookie** [shuzijun/leetcode-editor#624]
IDE2021,1
用LeetCode editor在刷二叉树的时候用到了TreeNode这个类
但是老是报这个错，有没有大佬遇到的，或者已经解决的，求大佬解答
Line 7: error: incompatible types: TreeNode cannot be converted to Solution.TreeNode [in __Driver__.java]
      List<Integer> ret = new Solution().postorderTraversal(param_1);

PS：关闭了自动导包（Javax.swing.tree）防止二者冲突

**Comment by shuzijun** [comment]
贴一下编辑器里代码

**Comment by G-rookie** [comment]
> 贴一下编辑器里代码

昨天捣鼓了一晚上，已解决。
解决办法：把力扣注释的TreeNode类打开，并将其定义成一个类，用它给的treeNode类就行。

  public class TreeNode {
      int val;
      TreeNode left;
      TreeNode right;
      TreeNode() {}
      TreeNode(int val) { this.val = val; }
      TreeNode(int val, TreeNode left, TreeNode right) {
          this.val = val;
          this.left = left;
       this.right = right;
      }
  }
