### ISSUE TITLE
IDE 使用该插件无法打开问题

### ISSUE THREAD

**Issue by jungre19** [shuzijun/leetcode-editor#625]
**Describe the bug**
无法打开问题，打开问题报错
![image](https://user-images.githubusercontent.com/57485297/225868832-cd92a36e-e56a-4871-90c1-c53fb235f0c7.png)

**To Reproduce**

**Software versions(*Help* -> *About*)**
- Product: [WEBSTORM 2022.3]
- Runtime version:[e.g 11.0.7+10-b944.20 amd64]
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS:[MACOS  13.2]

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:
  ```
  
  ```

**Comment by shuzijun** [comment]
这个应该只是一个警告信息，不会影响加载题目，还有其他错误么
