### ISSUE TITLE
idea 2023.1版本适配

### ISSUE THREAD

**Issue by zhanglubin721** [shuzijun/leetcode-editor#627]
目前2023.1版本打开之后插件显示登陆按钮的那个tab现在是完全空白的

**Comment by shuzijun** [comment]
测试了两个网站的登录，可以正常弹出网页。可以检查下日志里有其他错误提示么

**Comment by zhanglubin721** [comment]
没有问题了，可能是因为我用官方的toolbox工具直接更新的软件。在重装插件之后问题就消失了
