### ISSUE TITLE
为什么要是用钥匙串？？？

### ISSUE THREAD

**Issue by DarkFlameMasterDev** [shuzijun/leetcode-editor#628]
**Desc**
Start a discussion or ask for help

IntelliJ IDEA 2022.3 (Ultimate Edition)
Build #IU-223.7571.182, built on November 29, 2022
Licensed to signup scooter
You have a perpetual fallback license for this version.
Subscription is active until August 1, 2025.
Runtime version: 17.0.5+1-b653.14 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.3
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 8
Non-Bundled Plugins:
    leetcode-editor (8.7)
    MavenRunHelper (4.23.222.2964.0)
    cn.yiiguxing.plugin.translate (3.4.2)

Kotlin: 223-1.7.20-release-201-IJ7571.182

**为什么要是用钥匙串？？？**

我在设置登录密码的时候提醒我的
<img width="434" alt="image" src="https://user-images.githubusercontent.com/36620503/228454388-35890a51-8661-4f22-bdec-40e1e200adf6.png">

**Comment by shuzijun** [comment]
用于保存密码的，相关介绍参考https://www.jetbrains.com/help/idea/reference-ide-settings-password-safe.html
