### ISSUE TITLE
在网页提交和用该插件提交执行时间差异

### ISSUE THREAD

**Issue by wordfeng** [shuzijun/leetcode-editor#63]
## 在网页上提交执行1ms的题解beats 100%，但是用插件提交会运行2ms，beats 99%。在网页上反复提交都是1ms，在插件都是2ms。。。
希望能出实现一个能本地debug的功能。

**Comment by shuzijun** [comment]
理论上插件提交与网页提交没有差异。
本地调试参考 [自定义代码生成](https://github.com/shuzijun/leetcode-editor/blob/master/CustomCode_ZH.md)

**Comment by shuzijun** [comment]
如果有问题可以添加描述再打开这个Issues
