### ISSUE TITLE
多语言模板切换

### ISSUE THREAD

**Issue by Robotxm** [shuzijun/leetcode-editor#630]
**Desc**
有时候会在 Java 和 Kotlin 之间换着刷题，自定义模板能否适配多语言呢？

**Software versions(*Help* -> *About*)(Optional)**
- Product: [e.g IDEA 2020.2]
- Runtime version:[e.g 11.0.7+10-b944.20 amd64]
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS:[e.g Windows 10]

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:
  ```
  
  ```

**Comment by shuzijun** [comment]
[pro版本](https://plugins.jetbrains.com/plugin/17166-leetcode-editor-pro)是支持的，开源的版本暂时没有计划
