### ISSUE TITLE
关于${question.code}缩进部分的疑问

### ISSUE THREAD

**Issue by xuchuyanglove** [shuzijun/leetcode-editor#632]
请问我用了你们给的自定义示例代码模板，但是在idea生成出来的代码缩进有问题
code:
#/**
  * 题目Id：${question.frontendQuestionId}
  * 题目：${question.title}
  * 日期：$!velocityTool.date()
*/
${question.content}
package com.xcy.leetcode.editor.cn;
public class $!velocityTool.camelCaseName(${question.titleSlug}){
    public static void main(String[] args) {
        Solution solution = new $!velocityTool.camelCaseName(${question.titleSlug})().new Solution();
    }
    ${question.code}
}
以上模板生成出来的代码和你们gif图里产生的代码不一样，可以看到只有前面的--begin--缩进了，代码主体却没有缩进，具体如下
<img width="438" alt="Y)%_41)YQY`8 UNTUPN)8G" src="https://user-images.githubusercontent.com/69040314/230897158-d63d0c7f-ed99-4640-ac5c-4ab451d5a41f.png">
请问怎么解决这部分缩进问题，每次都用ctrl+alt+L有点麻烦

**Comment by shuzijun** [comment]
code是一个多行的内容，按照模版的配置，只会缩进第一行，暂时没有办法修改多行的缩进。
如果不想每次格式化代码，可以参考下IDEA的保存时自动格式化功能[reformat-on-save](https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html#reformat-on-save)

**Comment by xuchuyanglove** [comment]
> code是一个多行的内容，按照模版的配置，只会缩进第一行，暂时没有办法修改多行的缩进。 如果不想每次格式化代码，可以参考下IDEA的保存时自动格式化功能[reformat-on-save](https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html#reformat-on-save)

好的，十分感谢
