### ISSUE TITLE
代码模板中一写#include就消失

### ISSUE THREAD

**Issue by renlei-leon** [shuzijun/leetcode-editor#640]
代码模板中写#include <iostream>，双击题目生成的代码中就只剩下<iostream>，整个#include消失了；
如果在#和include之间加一个空格，则可以保留下来，

这是个bug吗，如何写模板能生成含有#include的代码？

**Comment by shuzijun** [comment]
参考#163 #235

**Comment by renlei-leon** [comment]
Interesting，昨晚在自己电脑上我就试了转义，试过/  //  \  \\  `  `` ##等没成功，现在在公司电脑上转义竟然是OK的。。
