### ISSUE TITLE
語法提示功能

### ISSUE THREAD

**Issue by andy840119** [shuzijun/leetcode-editor#643]
![image](https://github.com/shuzijun/leetcode-editor/assets/9100368/dc347570-cc95-41f8-8f51-9c4e58a480f5)
我是用 jetbrain rider
在 leetcode 用 C# 刷題只能出現根物件屬性無關的提示
這個功能是沒有實作嗎? 還是可以在哪邊設定?
感謝 🙏🏼

**Comment by andy840119** [comment]
![image](https://github.com/shuzijun/leetcode-editor/assets/9100368/7e8f3c7e-ea43-4635-b4c3-46fe3ba1ff77)
目前想到解決方法了
把暫存文件直接變成專案後打開就解決了 👌🏼

**Comment by shuzijun** [comment]
我不了解C# ，但是一般都是因为项目或者文件格式不符合规则，IDE无法进行正确的提示。
可以参考[自定义代码](https://github.com/shuzijun/leetcode-editor/blob/master/doc/CustomCode_ZH.md)，建立一个单独的项目.
