### ISSUE TITLE
如果能有个将以前的代码直接覆盖的功能就好了

### ISSUE THREAD

**Issue by Lin-Felix** [shuzijun/leetcode-editor#645]
有时候二刷题目时，进入题目后会看见题目的代码

如果有一个功能，可以一键覆盖掉本题之前提交过的代码的就好了

**Comment by shuzijun** [comment]
可以清除缓存的文件，缓存目录在配置中可以看到，但是这样做会删除所有题目的本地解答。
或者在题目上选择删除单个题目的缓存，然后再进入题目。

**Comment by Lin-Felix** [comment]
> 可以清除缓存的文件，缓存目录在配置中可以看到，但是这样做会删除所有题目的本地解答。 或者在题目上选择删除单个题目的缓存，然后再进入题目。

好的，谢谢您的解答
