### ISSUE TITLE
webstrom下插件的搜索框无法弹出

### ISSUE THREAD

**Issue by akanes0ra** [shuzijun/leetcode-editor#649]
OSX环境，版本号：WebStorm 2023.1.3

点击搜索按钮，可以弹出标签选择器，但是无法输入搜索内容

![Screenshot 2023-07-12 at 06 38 53](https://github.com/shuzijun/leetcode-editor/assets/44017689/609e53bb-58eb-416b-a1d5-744a513960b5)

**Comment by akanes0ra** [comment]
请确认是否可以复现该问题，webstorm版本号：223.8836.50

https://plugins.jetbrains.com/docs/intellij/webstorm.html

**Comment by shuzijun** [comment]
看选择是codetop列表，这个应该不支持搜索。
可以通过按钮切换到leetcode列表。
<img width="56" alt="image" src="https://github.com/shuzijun/leetcode-editor/assets/27667179/2703f8d5-12b5-4269-9b77-7870ed5c39d3">

**Comment by akanes0ra** [comment]
> 看选择是codetop列表，这个应该不支持搜索。 可以通过按钮切换到leetcode列表。 <img alt="image" width="56" src="https://user-images.githubusercontent.com/27667179/253740063-2703f8d5-12b5-4269-9b77-7870ed5c39d3.png">
