### ISSUE TITLE
一直提示请先登录

### ISSUE THREAD

**Issue by zhaoyunlovelife** [shuzijun/leetcode-editor#65]
使用的是官网下载的最新的5.1版本，测试用例和运行代码的时候都提示请先登录
![image](https://user-images.githubusercontent.com/32433578/65244554-6b2a9c80-db1d-11e9-9b13-ed04dc3c99bc.png)，确认账号和密码是没有问题的

**Comment by bynum5566** [comment]
我也有這問題，URL我設定https://leetcode.com。如果改用瀏覽器連則沒有問題，沒有用任何第三方登入，純粹帳號密碼複製貼上，瀏覽器可以進去但IDEA不行呢

**Comment by zXpp** [comment]
我也碰到这个问题有解决方案吗

**Comment by bynum5566** [comment]
@zXpp 
我後來解決了事情經過有分享上來，您參考一下看有沒有幫助
https://github.com/shuzijun/leetcode-editor/issues/148

**Comment by LearningGp** [comment]
我最近也遇到了这个问题，不过不确定完全一样。我是可以刷新拉取题目，但是运行以及提交时提示请先登录，后来发现问题在于每次打开idea后需要点击
![插件工具栏](https://user-images.githubusercontent.com/38268859/89125476-5a0a3480-d511-11ea-8085-200b76cc74b7.png)
最左边的sign in登录，然后就可以提交代码了

**Comment by bynum5566** [comment]
沒錯，就我的經驗，每次開機、開啟IDEA後，的確是要重新登入沒錯

我想登入跟看題目是兩件事，在leetcode官網上，也是不用登入就能看題目，要提交則必須先登入，所以這應該是正常現象才是



ArvinHe <notifications@github.com> 於 2020年8月2日 週日 22:42 寫道：
