### ISSUE TITLE
The keyword 'nonlocal' can not be executed successfully.

### ISSUE THREAD

**Issue by michael5182** [shuzijun/leetcode-editor#659]
Problem:
In python code, the keyword 'nonlocal' can not be executed successfully. The error message:
```
Compile Error
SyntaxError: invalid syntax
                  ^
    nonlocal solved
...
```

Situation:
When I write the question [37]Sudoku Solver, I can't run the code copied from the editorial page successfully but the Leetcode browser compiler does.

Environment:
LeetCode Editor Pro: 2023.1.2
Pycharm: 2023.1.4 Professional Edition.
OS: macOS Monterey 12.6.8.

When I write the code containing `nonlocal` keyword, I copied the code into the Leetcode browser compiler to get the pass.
Does anyone know how to to deal with this problem?

Thanks.

**Comment by shuzijun** [comment]
It is a keyword introduced by python3, check whether the configuration is correct.
<img width="368" alt="image" src="https://github.com/shuzijun/leetcode-editor/assets/27667179/6415bf03-7b8f-44a2-bab2-f1f5cf353d89">

**Comment by michael5182** [comment]
Solved!

Thank you for your help.
