### ISSUE TITLE
可以修改console中的文字或格式吗

### ISSUE THREAD

**Issue by yuhuoji** [shuzijun/leetcode-editor#663]
**Desc**
可以修改console中的文字或格式吗，目前测试用例、测试结果、stdout的退格格式比较乱，不知道可以修改吗，输入输出的最好是退格一样

**Software versions(*Help* -> *About*)(Optional)**
- Product: [Clion 2023.2]
- OS:[Windows 11]
![image](https://github.com/shuzijun/leetcode-editor/assets/72241577/45f4a4e9-28c3-4dd7-92dc-9aff06eb4f16)

**Comment by shuzijun** [comment]
格式不太好控制，现在是通过[info_zh.properties](https://github.com/shuzijun/leetcode-editor/blob/master/src/main/resources/i18n/info_zh.properties)文件格式化的输出内容。
