### ISSUE TITLE
IntelliJ IDEA 题目描述阅读模式

### ISSUE THREAD

**Issue by deewong7** [shuzijun/leetcode-editor#668]
**Is your feature request related to a problem? Please describe.**
IntelliJ IDEA Ultimate中，题目描述（content）不支持阅读模式 （Rendered View）。
![image](https://github.com/shuzijun/leetcode-editor/assets/92027789/1e85e672-b14a-4877-a001-1ed0b9f5f9e1)

**Describe the solution you'd like**
在IntelliJ IDEA Ultimate中支持，问题描述支持阅读模式

**Additional context**
这是启用阅读模式的一个例子：
<img width="684" alt="image" src="https://github.com/shuzijun/leetcode-editor/assets/92027789/fefe74ed-2eb1-47f4-a574-e6b482bca885">

**Comment by shuzijun** [comment]
试下在配置中开启使用HtmlContent

**Comment by deewong7** [comment]
> 试下在配置中开启使用HtmlContent
开启后还是没有render javadoc。但是不管开启还是不开启，下面的 content （class Solution）部分，总是会支持render javadoc
<img width="1319" alt="image" src="https://github.com/shuzijun/leetcode-editor/assets/92027789/abf66d4e-923c-4ef6-a9a8-4a1407e3b1d4">

**Comment by shuzijun** [comment]
<img width="439" alt="image" src="https://github.com/shuzijun/leetcode-editor/assets/27667179/f4468e79-fbbc-4409-b1a3-23f936ea6e6f">
这一部分是内容是来自力扣的代码区，不会修改，本身格式不支持阅读模式。
