### ISSUE TITLE
登录后点击新的题目，内容不刷新

### ISSUE THREAD

**Issue by EWING-ZHANG** [shuzijun/leetcode-editor#673]
不登录，点击新的题目可以刷新，但登录后不刷新。

**Comment by EWING-ZHANG** [comment]
![Uploading 题目不刷新.png…]()

**Comment by EWING-ZHANG** [comment]
![image](https://github.com/shuzijun/leetcode-editor/assets/77788406/5693abb3-6af2-4ee1-b7f0-d0e8e624f76c)

**Comment by EWING-ZHANG** [comment]
![image](https://github.com/shuzijun/leetcode-editor/assets/77788406/889036c6-014d-4965-a7d1-725e42c0510c)
之前的题目是回文，点击搜索二维矩阵，没刷新出来

**Comment by EWING-ZHANG** [comment]
来源换成leetcode.com没有这个问题，但是leetcode.cn存在这个问题

**Comment by EWING-ZHANG** [comment]
IDEA 2023.1
VM:[JDK1.8]
OS:[ Windows 11]

**Comment by shuzijun** [comment]
检查下配置，特别是文件目录和自定义代码配置。
检查下右下角是否有错误提示。
