### ISSUE TITLE
IntelliJ Idea 升级到2023.3以后 open solution 点击没有反应

### ISSUE THREAD

**Issue by jingeyijie** [shuzijun/leetcode-editor#682]
IntelliJ Idea 升级到2023.3以后 open solution 点击没有反应
![image](https://github.com/shuzijun/leetcode-editor/assets/4556255/8bef0556-3d3e-4973-b659-77d835d936f9)

**Comment by Yang-meow** [comment]
same here

**Comment by WayneJuu** [comment]
same here

**Comment by MoChengZi** [comment]
对对对，最新版是用不了的，什么都没有显示的，打不开题目的界面

**Comment by WayneJuu** [comment]
> 对对对，最新版是用不了的，什么都没有显示的，打不开题目的界面
今天更新了8.9版本插件 已经恢复正常了
