### ISSUE TITLE
Pycharm plugin fail to login (leetcode.com domain) at start

### ISSUE THREAD

**Issue by davidgao7** [shuzijun/leetcode-editor#686]
**Describe the bug**
点击Sign in 会提示 <font color=green>Failed to send request</font>

**Software versions(*Help* -> *About*)**
- Product: PyCharm 2023.3.2 (Professional Edition)
- Runtime version:17.0.9+7-b1087.9 x86_64
- VM:OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- OS: Mac OS Sonoma 14.2.1

  
<img width="1367" alt="Screenshot 2023-12-27 at 5 06 12 PM" src="https://github.com/shuzijun/leetcode-editor/assets/39502459/85acef40-b34c-4750-aefb-75d359c5499d">

**Comment by michael5182** [comment]
me too.

**Comment by neptunejing** [comment]
Same here.

**Comment by xx333fEthan** [comment]
IDEA Same here.

**Comment by shuzijun** [comment]
测试了一下登录是可以，尝试点击退出后重新登录下

**Comment by michael5182** [comment]
It work now though I do nothing.

Thanks.

**Comment by davidgao7** [comment]
It works today, closing.
