### ISSUE TITLE
获取题目失败

### ISSUE THREAD

**Issue by yklove** [shuzijun/leetcode-editor#69]
点击登录登录成功(https://leetcode-cn.com/)，点击刷新按钮报错，题目无法加载

>  15:35	warning: 请求题目出错,将加载本地缓存
>  15:35	error: 加载题目失败

![image](https://user-images.githubusercontent.com/12585320/65751078-5d3bd380-e13c-11e9-897c-5122ba29aaa0.png)
![image](https://user-images.githubusercontent.com/12585320/65751101-688eff00-e13c-11e9-9061-152986b9fc3d.png)

版本信息：
插件版本：5.1
![image](https://user-images.githubusercontent.com/12585320/65751229-af7cf480-e13c-11e9-96f3-bf5a06eca843.png)

**Comment by HansonYan** [comment]
我的也是，leetcode英文站能顺利显示列表，中文站不行，看提示貌似是网页解析不正确。

**Comment by yklove** [comment]
排序的时候报错了

https://github.com/shuzijun/leetcode-editor/blob/3842bb7f9415cc31b85513d49acb56929993ee5a/src/com/shuzijun/leetcode/plugin/manager/QuestionManager.java#L221

![image](https://user-images.githubusercontent.com/12585320/65757712-4ac89680-e14a-11e9-989f-6d2855af225e.png)

**Comment by shuzijun** [comment]
插件已临时更新到5.2版本，插件库需要审核一段时间，可以先通过硬盘安装，[下载地址](https://raw.githubusercontent.com/shuzijun/leetcode-editor/master/doc/leetcode-editor-V5.2.zip)
