### ISSUE TITLE
I Can't login leetcode.com, the Leetcode Console Pro shows `Failed to get code` repeatedly.

### ISSUE THREAD

**Issue by michael5182** [shuzijun/leetcode-editor#697]
**Desc**

Hi there,

Could anyone can help me to deal with this problem?

Pycharm inner error log is below:

```
java.lang.Throwable: Request userStatus  failed, status:403
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.shuzijun.leetcode.plugin.manager.QuestionManager.getUser(QuestionManager.java:353)
	at com.shuzijun.leetcode.plugin.window.NavigatorTabsPanel.getUser(NavigatorTabsPanel.java:161)
	at com.shuzijun.leetcode.plugin.window.NavigatorTabsPanel.lambda$new$0(NavigatorTabsPanel.java:88)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Software versions(*Help* -> *About*)(Optional)**
- Product: PyCharm 2023.3.4 (Professional Edition)
- Runtime version: 17.0.10+1-b1087.17 aarch64
- VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- OS: MacOS Sonoma 14.3.1

**Comment by HZSHZSHZS** [comment]
same as me

**Comment by woung717** [comment]
I think Leetcode changed their auth method. Other project also stop working.

**Comment by shuzijun** [comment]
leetcode.com adds cloudflare verification, resulting in failure to request data。 
<img width="810" alt="image" src="https://github.com/shuzijun/leetcode-editor/assets/27667179/41de3032-6979-4132-b6b2-533590b966ce">

**Comment by michael5182** [comment]
Thanks for the reply.

I can use the browsers to login leetcode.com with passing the cloudflare checking.

But I still have the same problem in Pycharm when I open it.

Any suggestion for this problem?

**Comment by shuzijun** [comment]
> Thanks for the reply.
> 
> I can use the browsers to login leetcode.com with passing the cloudflare checking.
> 
> But I still have the same problem in Pycharm when I open it.
> 
> Any suggestion for this problem?

I need some time to resolve this issue

**Comment by Drugsosos** [comment]
same problem, any request will cause 403 from cloudflare
The first solution that comes to mind is using jcef with setOffScreenRendering set to true 🤷🏻‍♂️

**Comment by shuzijun** [comment]
The plug-in library is under approval. You can download and install it through the link first.

https://github.com/shuzijun/leetcode-editor/releases/tag/v2024.1.1-pub
https://github.com/shuzijun/leetcode-editor/releases/tag/v8.10

**Comment by anshah85** [comment]
How to install through the link?

**Comment by michael5182** [comment]
> How to install through the link?

https://www.jetbrains.com/help/pycharm/managing-plugins.html#install_plugin_from_disk

**Comment by anshah85** [comment]
I installed through the disk, but it has below issue. I installed the instrumented-leetcode-editor-8.10.jar file from the disk.

<img width="818" alt="image" src="https://github.com/shuzijun/leetcode-editor/assets/112987704/089aa230-694b-4f89-a30e-c7fef928bf61">

**Comment by shuzijun** [comment]
@anshah85 Do not unzip, choose zip installation directly.

> I installed through the disk, but it has below issue. I installed the instrumented-leetcode-editor-8.10.jar file from the disk.
> 
> <img alt="image" width="818" src="https://private-user-images.githubusercontent.com/112987704/311472948-089aa230-694b-4f89-a30e-c7fef928bf61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMjYwNjQsIm5iZiI6MTcxMDEyNTc2NCwicGF0aCI6Ii8xMTI5ODc3MDQvMzExNDcyOTQ4LTA4OWFhMjMwLTY5NGItNGY4OS1hMzBlLWM3ZmVmOTI4YmY2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQwMjU2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTk3Y2QxODI2YzA1ZDQwNTZhM2JlMzdiNmVjM2M3NjNjYzI2NmIwMGVkZGZlMDc3ZDlkMTg0NmY2ZGUzNGUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iErYI4Xd7_Oa3hLeULWsEjqLx8vhxKVwWlKr-dR2cIk">

**Comment by Mayb11223** [comment]
I've installed plug-in through the link, but i can't submit code or run code and it has no any error info in IDEA, how can I fix this problem

**Comment by LRike** [comment]
> I've installed plug-in through the link, but i can't submit code or run code and it has no any error info in IDEA, how can I fix this problem

me too....Although the button can click, it will display the request 400.

**Comment by MaryLiu832** [comment]
Cannot login leetcode from intellij. Login page pop up after some time, verify catcha many times, at last "verified" displayed but login button is grey. Click "login", after a long time, it said verification expired.
