### ISSUE TITLE
中文搜索显示有一些问题

### ISSUE THREAD

**Issue by weblzf** [shuzijun/leetcode-editor#7]
我idea版本是2019.1 
例如搜索'中序遍历'， 显示出的列表要向下滚动几个项，才是真正匹配的题
这是我直接搜索中序遍历，所展示的列
![image](https://user-images.githubusercontent.com/23424487/55668197-e9112900-5898-11e9-9dcc-8585e56e451e.png)

向下滚动几个项才能显示正确
![image](https://user-images.githubusercontent.com/23424487/55668207-11992300-5899-11e9-94a3-00d88833d76c.png)

而且直接搜索题ID  就完全不对了

**Comment by shuzijun** [comment]
@weblzf  屏幕的分辨率 可以提供一下么？目前搜索结果展示位置是根据一个节点的高度进行计算滚动的。

**Comment by shuzijun** [comment]
@weblzf  试一下这个版本,麻烦把结果告诉我一下。https://github.com/shuzijun/leetcode-editor/blob/master/doc/leetcode-editor-V3.2.zip

**Comment by weblzf** [comment]
现在显示对了
![image](https://user-images.githubusercontent.com/23424487/55670041-e53dd080-58b1-11e9-9850-b77fb1290e33.png)
![image](https://user-images.githubusercontent.com/23424487/55670045-f2f35600-58b1-11e9-9a8b-adee958c4c0b.png)

**Comment by weblzf** [comment]
> @weblzf 屏幕的分辨率可以提供一下么？目前搜索结果展示位置是根据一个节点的高度进行计算滚动的。


分辨率是这个
![image](https://user-images.githubusercontent.com/23424487/55670052-18805f80-58b2-11e9-88bb-b6ef3624605f.png)

**Comment by shuzijun** [comment]
尝试新版是否还有问题。
