### ISSUE TITLE
 The raw html tags are showed in the desc after installing the new release v2024.1.1.

### ISSUE THREAD

**Issue by michael5182** [shuzijun/leetcode-editor#700]
**Desc**

Hi there,

Thanks for solving a problem #697.

There is subtle problem that the raw html tags are showed in the desc after installing the new release v2024.1.1.

I took leetcode problem (5)  as a example:

Before: 
![image](https://github.com/shuzijun/leetcode-editor/assets/5361089/0a2fee4c-5ece-4292-a7a5-8bb391f64e35)

After: 
![image](https://github.com/shuzijun/leetcode-editor/assets/5361089/5988c335-8baf-4368-b9ab-a58573208e20)

**Software versions(*Help* -> *About*)(Optional)**
Product: PyCharm 2023.3.4 (Professional Edition)
Runtime version: 17.0.10+1-b1087.17 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
OS: MacOS Sonoma 14.3.1

**Comment by shuzijun** [comment]
<img width="776" alt="image" src="https://github.com/shuzijun/leetcode-editor/assets/27667179/d5929263-0b29-4f98-b4ab-b9952dedc5e0">
Check this configuration.

**Comment by michael5182** [comment]
Thanks. 

It is solved!
