### ISSUE TITLE
题库列表第一个一直是[1379]号题, 无法移除

### ISSUE THREAD

**Issue by O5-7** [shuzijun/leetcode-editor#710]
**Describe the bug**
题库列表第一个一直是[1379]号题, 无法移除, 无论是排序, 筛选,翻页等都无法移除
![image](https://github.com/shuzijun/leetcode-editor/assets/40710644/34a29e6e-d393-4966-b55b-884d6897e9ec)

**To Reproduce**
1. 启动并登录, 转到题库
2. 题库第一个一直是[1379]号题

**Software versions(*Help* -> *About*)**
- Product: Clion 2021.2.3
- Runtime version: 11.0.12+7-b1504.40 amd64
- VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o.
- OS: Windows 10

**Question(Optional)**
- URL: leetcode.cn
- Code Type: c++

**Comment by shuzijun** [comment]
这是每日一题，不受筛选的控制
