### ISSUE TITLE
idea升级到2024.1版本后。leetcode插件报错ActionUpdateThread.OLD_EDT is deprecated and going to be removed soon.

### ISSUE THREAD

**Issue by wanglei13975** [shuzijun/leetcode-editor#712]
**Describe the bug**
idea在升级到2024.1版本后Leecode插件登录报错
![image](https://github.com/shuzijun/leetcode-editor/assets/12521704/d16f14d6-fe4e-4217-bf81-5fe7bf412e10)
插件版本：8.11，报错信息如下
![image](https://github.com/shuzijun/leetcode-editor/assets/12521704/c68bb6f5-92da-4ae2-8676-0640d1fd7d9e)

**Comment by zhanggang807** [comment]
+1

**Comment by zhanggang807** [comment]
可以参考https://github.com/redhat-developer/lsp4ij/pull/142/files 修复一下，感觉不复杂
