### ISSUE TITLE
[建议] 希望点击搜索按钮时可以自动聚焦到搜索框

### ISSUE THREAD

**Issue by pheotry** [shuzijun/leetcode-editor#713]
点击搜索按钮说明是要输入文字了，焦点自动聚焦到搜索框比较合理
![image](https://github.com/shuzijun/leetcode-editor/assets/43376740/4fccce4a-8f4f-4eea-8ebb-f6250f1ccdb9)

**Comment by kris0325** [comment]
最新版插件更新后， 最重要的搜索按钮功能无法使用了，无法通过leetcode 题号来搜索题目了吗？
 连搜索框都不见了，是bug, 还是去掉搜索功能呢呀？
<img width="755" alt="Screenshot 2024-08-31 at 23 20 03" src="https://github.com/user-attachments/assets/875677e2-3676-4c00-9e77-8f6ebc4c7ff5">

**Comment by kris0325** [comment]
不是bug
因为切换为 ”togglist “， 搜索框被隐藏了。
