### ISSUE TITLE
插件提交的代码有延迟

### ISSUE THREAD

**Issue by JackCoulson** [shuzijun/leetcode-editor#76]
经常提交代码报错了，然后改好再提交运行时候，执行的还是以前那个错误代码，要等会或者关掉重新打开才行。是缓存还是idea保存的原因呢？插件能解决一下吗，感谢！

**Comment by shuzijun** [comment]
目前建议提交之前先手动保存一下，后续更换一下读取文件的方式

**Comment by shuzijun** [comment]
新版本已经增加自动保存功能，如果有问题可以添加描述再打开这个Issues
