### ISSUE TITLE
non blocking requests 

### ISSUE THREAD

**Issue by rinormaloku** [shuzijun/leetcode-editor#8]
When you click logging in, running the code etc. The entire UI of IntelliJ gets blocked. (not a huge problem as in the end u are waiting for the result.)

This seems to be solved simply by adding the code within executeOnPooled thread:

For example we can include the whole code in LoginAction.actionPerformed as shown below:

```java
        ApplicationManager.getApplication().executeOnPooledThread(() -> {
            //code to login
        });
```

Tested it and it works. Though have very limited IntelliJ plugin development knowledge wanted to check if this is a viable solution, and if we want this implemented?

**Comment by shuzijun** [comment]
Looking for a solution to solve this problem

**Comment by rinormaloku** [comment]
> Looking for a solution to solve this problem

If you want I can pick it up and help. I will check the documentation and maybe some implementations on GitHub

**Comment by shuzijun** [comment]
> > Looking for a solution to solve this problem
> 
> If you want I can pick it up and help. I will check the documentation and maybe some implementations on GitHub

executeOnPooledThread() solves most UI blocking problems,newversion( [V3.3](https://github.com/shuzijun/leetcode-editor/blob/master/doc/leetcode-editor-V3.3.zip)).  
Welcome to improvements and  contribute new functionalities
