### ISSUE TITLE
右侧目录是否可以增加定位当前文件的功能

### ISSUE THREAD

**Issue by binyu717** [shuzijun/leetcode-editor#83]

**Comment by shuzijun** [comment]
可以详细描述下么？这样做有什么样的应用场景

**Comment by binyu717** [comment]
> 可以详细描述下么？这样做有什么样的应用场景

之前练习过的算法，或是没写完的，往往是从本地目录进去的，完成之后需要重新测试提交至leetcode上，而提交这部分操作是在右侧leetcode目录中右键选中的文件才有入口

**Comment by shuzijun** [comment]
如果是默认的文件名应该是可以定位到题目的位置的，但是如果是开启了自定义生成代码的功能，文件名是无法逆向解析的，就可能导致无法定位问题。这个操作后续想一下实现方案，目前可以通过搜索功能快速定位到题目。

**Comment by shuzijun** [comment]
@binyu717 针对上述场景,增加了在editor里，可以直接右键操作
