### ISSUE TITLE
关于收藏功能

### ISSUE THREAD

**Issue by BoomManPro** [shuzijun/leetcode-editor#85]
本地收藏夹
目的是可以手动将题目分类,将不太会做的题目进行打标记,然后从标记中选取。
大概就和即单词一样吧。

现在有个
![image](https://user-images.githubusercontent.com/25561886/67464822-97828d00-f676-11e9-8954-533411323ccf.png)
是不能用吗，不会用这个，还有就是没有相关说明。
最后对作者大大做的这个plugins很赞.

**Comment by shuzijun** [comment]
这个收藏夹是leetcode提供的，不是收藏在本地的。箭头指示的是默认收藏夹，也可以通过网站建立新的收藏夹。使用方式是先选中一个题目，然后再选择后面的收集夹名称就好了，如果是已经收藏的题目，收藏夹名称前会有一个对号，再次点击取消收藏。

**Comment by BoomManPro** [comment]
谢谢
