### ISSUE TITLE
关于去掉 //leetcode submit region begin(Prohibit modification and deletion)注释

### ISSUE THREAD

**Issue by 1379** [shuzijun/leetcode-editor#89]
事实上，我几乎不用插件来提交题目，而是使用网页来提交。网页不仅可以让我看到我的题解耗时，还可以看到讨论以及官方solution,所以能否提供类似的开关，来去掉 //leetcode submit region begin(Prohibit modification and deletion)这行注释，毕竟对于一个强迫症来说，这实在很痛苦。我尝试过自己手动编译，然而这就不能更上插件的更新了

**Comment by shuzijun** [comment]
可以通过自定义模块功能实现，开启Costom code template 后，将代码区question.code使用正则替换掉注释或者其他文本，例如：  
$question.code.replaceAll("//leetcode\ssubmit\sregion.*","")

**Comment by zhast460** [comment]
![image](https://user-images.githubusercontent.com/12053298/68466938-49fa4880-0250-11ea-94cc-b8d66099d1c5.png)

使用了你上面建议的正则替换，template直接就不行了 
@shuzijun

**Comment by 1379** [comment]
@zhast460 我这边是可以的 
![image](https://user-images.githubusercontent.com/34785043/68472252-0b1dc000-025b-11ea-8b0a-8583377a9c4d.png)

**Comment by zhast460** [comment]
> @zhast460 我这边是可以的
> ![image](https://user-images.githubusercontent.com/34785043/68472252-0b1dc000-025b-11ea-8b0a-8583377a9c4d.png)

我发现我一时可以一时不可以，好奇怪

**Comment by shuzijun** [comment]
@zhast460 检查下自定义代码打开了么？看配置是没什么问题。
