### ISSUE TITLE
有些题没有从LeetCode.cn上加载到本地

### ISSUE THREAD

**Issue by weblzf** [shuzijun/leetcode-editor#9]
![image](https://user-images.githubusercontent.com/23424487/55692748-65ad2000-59dd-11e9-8635-610dba35dfdf.png)
![image](https://user-images.githubusercontent.com/23424487/55692757-6d6cc480-59dd-11e9-890b-2079771029fd.png)

**Comment by shuzijun** [comment]
已定位到问题，下个版本修复

**Comment by shuzijun** [comment]
@weblzf  安装一下这个版本 [V3.4](https://github.com/shuzijun/leetcode-editor/blob/master/doc/leetcode-editor-V3.4.zip)

**Comment by weblzf** [comment]
> @weblzf 安装一下这个版本[V3.4](https://github.com/shuzijun/leetcode-editor/blob/master/doc/leetcode-editor-V3.4.zip)

现在序号对了
