### ISSUE TITLE
可以更改不同难度题目的颜色吗？

### ISSUE THREAD

**Issue by zhast460** [shuzijun/leetcode-editor#90]
用这个插件的用户，大部分都是在公司刷题的。打开插件的dashboard时，不同难度题目的绿色、黄色、红色特别显眼。

可以更改这个颜色吗？或者改用不同灰度显示， 或者不用颜色去区分难度，改成在题目前加1到3个点点表示难度

**Comment by shuzijun** [comment]
下个版本吧，增加一下自定义颜色的功能。目前的颜色是和官网保持一致
