### ISSUE TITLE
每次打开IDE都必须重新输入密码

### ISSUE THREAD

**Issue by ihuangteng** [shuzijun/leetcode-editor#94]

**Comment by ihuangteng** [comment]
每次打开IDEA时候都必须在设置中重新设置leetcode的密码并登陆才能使用

**Comment by shuzijun** [comment]
默认是记住密码的，在配置完密码之后保存不同系统提示的可能不一样，需要同意才可以。

**Comment by ihuangteng** [comment]
在配置页面输入密码之后选择确定没有提示啊，我是win10的系统，IDEA是2019.2的

**Comment by shuzijun** [comment]
在IDE的Help -> About 有一行Build #IU-192***的信息，提供一下

**Comment by ihuangteng** [comment]
![图片](https://user-images.githubusercontent.com/29241148/69293660-911b0d00-0c44-11ea-91a0-d9df5b64c643.png)
是这个吧

**Comment by shuzijun** [comment]
安装一下这个版本试一下，修改了密码存储的方法。[leetcode-editor.zip](https://github.com/shuzijun/leetcode-editor/files/3872484/leetcode-editor.zip)

**Comment by ihuangteng** [comment]
还是不行啊，我重新安装之后配置都还是我原来的，重开了之后密码那项还是空的

**Comment by shuzijun** [comment]
检查一下这项配置是否打开 [settings-password](https://www.jetbrains.com/help/idea/reference-ide-settings-password-safe.html)

**Comment by ihuangteng** [comment]
可以了，打开配置项之后输入密码就可以保存了，感谢！
