### ISSUE TITLE
插件无法登陆leetcom.com

### ISSUE THREAD

**Issue by hdlldh** [shuzijun/leetcode-editor#96]
从上周末（11/23）开始，插件没法正常登陆leetcode.com，显示下面错误信息。网页登陆没有问题。
“info: Unable to determine the login status, please try to login the web and try again”

**Comment by dongfang-a** [comment]
同样的问题：info: 无法判断登陆状态，请尝试登陆网页版后，再次重试

**Comment by shuzijun** [comment]
leecode.com增加了登陆时的参数，参数的生成规则正在看

**Comment by xudongMk** [comment]
同样的问题：info: 无法判断登陆状态，请尝试登陆网页版后，再次重试~加油解决哇~

**Comment by zangruirui** [comment]
现在解决了吗

**Comment by shuzijun** [comment]
@zangruirui 版本已发布，现在测试阶段 .[v6.0-beta.1](https://github.com/shuzijun/leetcode-editor/releases/tag/v6.0-beta.1)

**Comment by shalk** [comment]
Unable to determine the login status, please try to login the web and try again
