### ISSUE TITLE
提交的代码不存在

### ISSUE THREAD

**Issue by lizhaowen72** [shuzijun/leetcode-editor#98]
在配置模板中,设置包名package leetcode.editor.cn;可以提交代码,而设置成package leetcode.editor.cn.stack;或者package leetcode.editor.cn.tree; 提示提交的代码不存在

**Comment by shuzijun** [comment]
默认路径最后是leetcode/editor/cn，如果想在这个路径之后增加路径，可以开启Custom code template,在CodeFileName中配置后续路径加文件名，例如:stack/[$!{question.frontendQuestionId}]${question.title}

**Comment by shuzijun** [comment]
如果有问题可以添加描述再打开这个Issues

**Comment by Rickzhang512** [comment]
在leetcode插件设置里面路径要对，比如我的就是D:\Code\Java\src，要和java代码所在路径对的上
